import type { Metadata } from "next";
import { Formula } from "../../components/Formula";
import { RightQaIndex } from "../../components/RightQaIndex";
import { TrainingSidebar } from "../../components/TrainingSidebar";

const title = "什么是 PPO？";
const description = "从策略梯度开始，逐步推导 LLM PPO 中的逐 Token 奖励、Return、Value、TD error、GAE、Importance Ratio 与 Clip Objective。";
export const metadata: Metadata = { title, description, openGraph: { title, description, type: "article", images: [] }, twitter: { card: "summary", title, description, images: [] } };

const chapters = [
  ["01", "先建立 LLM 策略"], ["02", "优化目标是什么"], ["03", "策略梯度怎样得到"],
  ["04", "Reward-to-Go"], ["05", "Value 与 Advantage"], ["06", "RLHF 序列目标"],
  ["07", "逐 Token Reward"], ["08", "Return 怎样累计"], ["09", "Critic 与 TD Error"],
  ["10", "GAE 怎样推导"], ["11", "Old Policy 与概率比"], ["12", "PPO Clip Objective"],
  ["13", "完整训练系统"], ["14", "问题与改进"], ["15", "关联 QA"],
];
const qaQuestions = [
  "它和人类反馈对齐是什么关系？", "为什么一个 Action 只是一枚 Token？", "策略梯度为什么使用对数概率？",
  "Reward、Return 与 Advantage 有何区别？", "只有终局分数时，前面的 Token 怎么学习？", "逐 Token Shaped Reward 是怎样得到的？",
  "折扣因子在文本生成中有什么意义？", "Critic 是在判断推理是否正确吗？", "TD Error 为什么像一步预测误差？",
  "GAE 为什么不是奖励函数？", "Old Policy 与 Reference Policy 有何区别？", "Clip 能保证新旧策略足够接近吗？",
];

export default function PPOPage() { return <div className="site-shell">
  <header className="topbar"><a className="brand" href="/" aria-label="模见首页"><span className="brand-mark">模</span><span>模见 <small>Model Atlas</small></span></a><nav className="topnav"><a className="active" href="/">知识库</a><a href="#chapter-1">训练导读</a><a href="#qa">QA 索引</a></nav><div className="top-actions"><a className="search-hint" href="#qa">⌘ K&nbsp;&nbsp;QA 速查</a><span className="edition">2026.08</span></div></header>
  <TrainingSidebar selected="ppo" />
  <main className="article rms-article">
    <section className="hero rms-hero" id="top"><div className="breadcrumbs"><a href="/">知识库</a><span>/</span>训练与对齐<span>/</span>PPO</div><div className="question-label"><span>POLICY OPTIMIZATION · 004</span></div><p className="original-question">“终局 Reward、逐 Token KL、Return、TD Error、GAE 和 Clip 为什么会按这个顺序出现？这些公式究竟是怎样连起来的？”</p><div className="eyebrow"><span></span>FROM POLICY GRADIENT TO PPO</div><h1>什么是 PPO？</h1><p className="dek">PPO 不是一组彼此独立的公式。它从策略梯度出发：先把 LLM 的生成过程写成策略与轨迹，再用 Reward、Return 和 Advantage 建立学习信号，用 Critic 与 GAE 控制估计方差，最后用 Old Policy、概率比和 Clip 控制一次更新不要走得太远。</p><div className="hero-meta"><span>重写于 2026.08.20</span><i></i><span>70 分钟阅读</span><i></i><span>文字 + 逐步推导</span></div><aside className="answer-first"><span>先记住整条因果链</span><p><b>Reward</b> 评价发生了什么，<b>Return</b> 汇总未来 Reward，<b>Value</b> 预测平均 Return，<b>Advantage</b> 衡量本次动作相对平均水平有多好，<b>GAE</b> 估计 Advantage，<b>PPO Clip</b> 决定用这个 Advantage 更新 Policy 时最多信任旧数据到什么程度。</p></aside></section>

    <section className="prose-section" id="chapter-1"><div className="prose-heading"><span>01</span><div><p>LANGUAGE GENERATION AS A POLICY</p><h2>第一步不是 PPO，而是把 LLM 写成一个随机策略</h2></div></div><p>给定 Prompt <Formula inline tex={String.raw`x`} />，模型已经生成前缀 <Formula inline tex={String.raw`y_{<t}`} />。在第 <Formula inline tex={String.raw`t`} /> 步，完整状态是 Prompt 与此前前缀，动作是下一枚 Token：</p><Formula label="LLM 中的 State、Action 与 Policy" tex={String.raw`s_t=(x,y_{<t}),\qquad a_t=y_t,\qquad \pi_\theta(a_t\mid s_t)=p_\theta(y_t\mid x,y_{<t})`} /><p>完整回答 <Formula inline tex={String.raw`y=(y_1,\ldots,y_T)`} /> 是一条 trajectory。由于自回归分解，整条轨迹的概率等于每一步条件概率的乘积：</p><Formula label="完整回答的生成概率" tex={String.raw`\pi_\theta(y\mid x)=\prod_{t=1}^{T}\pi_\theta(y_t\mid x,y_{<t})`} /><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>强化学习对象</th><th>LLM 中的对象</th><th>直觉</th></tr></thead><tbody><tr><td>State <Formula inline tex={String.raw`s_t`} /></td><td>Prompt + 已生成前缀</td><td>模型现在看见的上下文</td></tr><tr><td>Action <Formula inline tex={String.raw`a_t`} /></td><td>下一枚 Token</td><td>模型这一步作出的选择</td></tr><tr><td>Trajectory <Formula inline tex={String.raw`\tau`} /></td><td>完整 Response</td><td>许多 Token 动作组成的序列</td></tr><tr><td>Policy <Formula inline tex={String.raw`\pi_\theta`} /></td><td>下一 Token 概率分布</td><td>可训练的语言模型</td></tr></tbody></table></div><p>因此，PPO 实际更新的是每一步 Token 概率。完整回答只是这些动作共同组成的一次采样结果。</p></section>

    <section className="prose-section" id="chapter-2"><div className="prose-heading"><span>02</span><div><p>THE OBJECTIVE BEFORE THE GRADIENT</p><h2>我们真正想优化的是“高回报回答的期望”</h2></div></div><p>假设一条回答最终得到总回报 <Formula inline tex={String.raw`R(\tau)`} />。训练目标不是直接最大化某一条样本的分数，而是让模型生成回答时的<b>期望回报</b>变高：</p><Formula label="期望回报目标" tex={String.raw`J(\theta)=\mathbb E_{\tau\sim\pi_\theta}\!\left[R(\tau)\right]=\sum_\tau \pi_\theta(\tau)R(\tau)`} /><p>这里有一个关键困难：Reward Model、规则 Verifier 或外部环境通常不可微。我们无法把 Reward 的梯度直接穿过一段离散文本传回模型。但轨迹被采到的概率 <Formula inline tex={String.raw`\pi_\theta(\tau)`} /> 是由模型参数控制的，所以可以改变“哪些回答更容易被采到”。</p><aside className="boundary-box"><b>优化的不是 Reward 函数本身</b><p>Reward 可以是冻结模型或不可微程序。策略优化只需要它为采样结果打分，再提高高分轨迹的生成概率、降低低分轨迹的生成概率。</p></aside></section>

    <section className="prose-section" id="chapter-3"><div className="prose-heading"><span>03</span><div><p>THE LOG-DERIVATIVE TRICK</p><h2>策略梯度为什么自然地出现了 Log Probability？</h2></div></div><p>从期望回报对参数求导开始。使用恒等式 <Formula inline tex={String.raw`\nabla_\theta p=p\,\nabla_\theta\log p`} />，可以把“概率的导数”改写为可通过神经网络反向传播的“对数概率导数”：</p><Formula label="从期望回报到轨迹级策略梯度" className="compact-latex" tex={String.raw`\begin{aligned}\nabla_\theta J(\theta)&=\sum_\tau \nabla_\theta\pi_\theta(\tau)R(\tau)\\&=\sum_\tau \pi_\theta(\tau)R(\tau)\nabla_\theta\log\pi_\theta(\tau)\\&=\mathbb E_{\tau\sim\pi_\theta}\!\left[R(\tau)\nabla_\theta\log\pi_\theta(\tau)\right].\end{aligned}`} /><p>轨迹概率是 Token 概率的乘积，所以它的对数是求和：</p><Formula label="把轨迹梯度拆到每个 Token" className="compact-latex" tex={String.raw`\log\pi_\theta(\tau)=\sum_{t=1}^{T}\log\pi_\theta(a_t\mid s_t),\qquad \nabla_\theta J=\mathbb E\!\left[\sum_{t=1}^{T}R(\tau)\nabla_\theta\log\pi_\theta(a_t\mid s_t)\right]`} /><p>这条式子的含义很朴素：若一条轨迹回报为正，就沿着增大其中已采样 Token 对数概率的方向更新；若回报相对基准为负，则沿相反方向更新。Log 不是人为添加的技巧，而是从概率分布的期望求导自然得到的。</p></section>

    <section className="prose-section" id="chapter-4"><div className="prose-heading"><span>04</span><div><p>CAUSAL CREDIT ASSIGNMENT</p><h2>为什么总回报会变成 Reward-to-Go？</h2></div></div><p>第 <Formula inline tex={String.raw`t`} /> 步的动作不可能改变已经发生的过去 Reward，因此没有必要把 <Formula inline tex={String.raw`t`} /> 之前的奖励用于评价它。只累计从当前时刻开始的未来奖励，得到 Return，也叫 Reward-to-Go：</p><Formula label="从时刻 t 开始的 Return" tex={String.raw`G_t=\sum_{l=0}^{T-t}\gamma^l r_{t+l}=r_t+\gamma r_{t+1}+\gamma^2r_{t+2}+\cdots`} /><Formula label="使用 Reward-to-Go 的策略梯度" tex={String.raw`\nabla_\theta J(\theta)=\mathbb E\!\left[\sum_{t=1}^{T}G_t\,\nabla_\theta\log\pi_\theta(a_t\mid s_t)\right]`} /><p><Formula inline tex={String.raw`\gamma\in[0,1]`} /> 是折扣因子。它表达对更远未来 Reward 的权重；有限长度文本生成中常取接近 <Formula inline tex={String.raw`1`} /> 或直接取 <Formula inline tex={String.raw`1`} />。Return 不是额外设计出的 Reward，而是现有逐步 Reward 从当前时刻向后的累计。</p></section>

    <section className="prose-section" id="chapter-5"><div className="prose-heading"><span>05</span><div><p>FROM ABSOLUTE RETURN TO RELATIVE QUALITY</p><h2>为什么还要引入 Q、V 与 Advantage？</h2></div></div><p>同一个 Prompt 可能天然容易获得高分，另一个 Prompt 天然困难。只看绝对 Return 会让梯度方差很大。我们更想知道：在当前状态下，选中这个 Token 后的结果，是否优于当前策略通常能做到的水平。</p><Formula label="Value、Action Value 与 Advantage" className="compact-latex" tex={String.raw`\begin{aligned}V^\pi(s_t)&=\mathbb E_\pi[G_t\mid s_t],\\Q^\pi(s_t,a_t)&=\mathbb E_\pi[G_t\mid s_t,a_t],\\A^\pi(s_t,a_t)&=Q^\pi(s_t,a_t)-V^\pi(s_t).\end{aligned}`} /><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>量</th><th>回答的问题</th><th>角色</th></tr></thead><tbody><tr><td><Formula inline tex={String.raw`Q^\pi(s_t,a_t)`} /></td><td>在这里选了这个 Token，未来平均能得多少？</td><td>动作后的预期</td></tr><tr><td><Formula inline tex={String.raw`V^\pi(s_t)`} /></td><td>还没指定 Token 时，当前策略平均能得多少？</td><td>状态基线</td></tr><tr><td><Formula inline tex={String.raw`A^\pi(s_t,a_t)`} /></td><td>这个 Token 比当前策略平均选择好多少？</td><td>相对改进信号</td></tr></tbody></table></div><p>从策略梯度中减去只依赖状态的 baseline 不改变梯度的期望，因为：</p><Formula label="Baseline 不引入期望偏差" className="compact-latex" tex={String.raw`\mathbb E_{a\sim\pi}\!\left[b(s)\nabla_\theta\log\pi_\theta(a\mid s)\right]=b(s)\nabla_\theta\sum_a\pi_\theta(a\mid s)=0`} /><p>最理想的 baseline 正是 <Formula inline tex={String.raw`V^\pi(s_t)`} />。于是策略梯度可以用 Advantage 加权：高于平均的动作增大概率，低于平均的动作减小概率。</p></section>

    <section className="prose-section" id="chapter-6"><div className="prose-heading"><span>06</span><div><p>THE SEQUENCE-LEVEL RLHF OBJECTIVE</p><h2>LLM 的 Reward 与 KL 约束最初来自哪里？</h2></div></div><p>经典 <a className="term-link" href="/training/rlhf">RLHF</a> 中，Reward Model 为完整回答给出分数 <Formula inline tex={String.raw`r_\phi(x,y)`} />。如果只最大化这个分数，Policy 可能快速偏离 SFT 模型，利用 Reward Model 的漏洞。因此常加入相对冻结 Reference Policy 的 KL 正则：</p><Formula label="序列级正则化目标" className="compact-latex" tex={String.raw`J_{\mathrm{RLHF}}(\theta)=\mathbb E_{y\sim\pi_\theta(\cdot\mid x)}\!\left[r_\phi(x,y)-\beta\log\frac{\pi_\theta(y\mid x)}{\pi_{\mathrm{ref}}(y\mid x)}\right]`} /><p>这里写的是采样轨迹上的 log-ratio 估计；对 <Formula inline tex={String.raw`y\sim\pi_\theta`} /> 取期望后，对应从当前策略到 Reference Policy 的 KL。系数 <Formula inline tex={String.raw`\beta`} /> 控制“追求任务 Reward”与“不要离原模型太远”的权衡。</p><p>自回归分解让序列 log-ratio 能严格拆成 Token log-ratio：</p><Formula label="序列 Log Ratio 的 Token 分解" className="compact-latex" tex={String.raw`\log\frac{\pi_\theta(y\mid x)}{\pi_{\mathrm{ref}}(y\mid x)}=\sum_{t=1}^{T}\left[\log\pi_\theta(y_t\mid s_t)-\log\pi_{\mathrm{ref}}(y_t\mid s_t)\right]`} /><p>这一步就是逐 Token KL shaping 的来源，不是凭空造出一个奖励公式。</p></section>

    <section className="prose-section" id="chapter-7"><div className="prose-heading"><span>07</span><div><p>DECOMPOSE ONE SCORE INTO STEP REWARDS</p><h2>逐 Token Shaped Reward 是怎样从序列目标推出来的？</h2></div></div><p>为了使用时序差分、Return 和 GAE，我们希望把序列目标写成逐步 Reward 的和。把每一步 log-ratio 的负惩罚放在对应 Token 上，再把完整回答分数只加在终止步：</p><Formula label="逐 Token Shaped Reward" className="compact-latex" tex={String.raw`r_t^{\mathrm{shape}}=-\beta\!\left[\log\pi_{\mathrm{rollout}}(y_t\mid s_t)-\log\pi_{\mathrm{ref}}(y_t\mid s_t)\right]+\mathbf 1[t=T],r_\phi(x,y)`} /><p>其中 <Formula inline tex={String.raw`\mathbf 1[t=T]`} /> 只有在最后一个有效 Token 为 <Formula inline tex={String.raw`1`} />，其他时刻为 <Formula inline tex={String.raw`0`} />。单个采样 Token 的 log-ratio 可以为正或负，所以单步样本项不一定表现为负数；对当前策略的采样取期望后，完整序列 log-ratio 才对应非负的 KL divergence。当 <Formula inline tex={String.raw`\gamma=1`} /> 时，对全部 Token 求和即可回到原序列目标：</p><Formula label="分解前后总量相同" className="compact-latex" tex={String.raw`\sum_{t=1}^{T}r_t^{\mathrm{shape}}=r_\phi(x,y)-\beta\log\frac{\pi_{\mathrm{rollout}}(y\mid x)}{\pi_{\mathrm{ref}}(y\mid x)}`} /><aside className="boundary-box"><b>为什么公式里写 Rollout Policy？</b><p>理论目标常写当前策略 <Formula inline tex={String.raw`\pi_\theta`} />。实际 PPO 先由冻结的 <Formula inline tex={String.raw`\pi_{\mathrm{old}}`} /> 采一批回答，再把这批 Reward 当作固定数据进行若干次优化，所以实现中用于 Reward shaping 的采样 log-prob 往往来自 Rollout/Old Policy，并停止对 Reward 本身求梯度。具体记号随实现不同，但不能把 Reward 项与后面的 PPO 概率比混为一谈。</p></aside></section>

    <section className="prose-section" id="chapter-8"><div className="prose-heading"><span>08</span><div><p>FROM STEP REWARD TO FUTURE RETURN</p><h2>Return 公式究竟在累计什么？</h2></div></div><p>现在每个 Token 都有 <Formula inline tex={String.raw`r_t^{\mathrm{shape}}`} />，再从时刻 <Formula inline tex={String.raw`t`} /> 向后累计，就得到这个 Token 所面对的未来 Return：</p><Formula label="Shaped Reward 对应的 Return" tex={String.raw`G_t=\sum_{l=0}^{T-t}\gamma^l r_{t+l}^{\mathrm{shape}}`} /><p>索引 <Formula inline tex={String.raw`l`} /> 表示“距离当前时刻多远”：当 <Formula inline tex={String.raw`l=0`} /> 取当前 Reward，当 <Formula inline tex={String.raw`l=1`} /> 取下一个 Reward，直到终局。以三枚 Token、<Formula inline tex={String.raw`\gamma=1`} /> 为例：</p><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>时刻</th><th>逐步 Shaped Reward</th><th>从该时刻开始的 Return</th></tr></thead><tbody><tr><td><Formula inline tex={String.raw`t=3`} /></td><td><Formula inline tex={String.raw`r_3=1.03`} /></td><td><Formula inline tex={String.raw`G_3=1.03`} /></td></tr><tr><td><Formula inline tex={String.raw`t=2`} /></td><td><Formula inline tex={String.raw`r_2=-0.01`} /></td><td><Formula inline tex={String.raw`G_2=-0.01+1.03=1.02`} /></td></tr><tr><td><Formula inline tex={String.raw`t=1`} /></td><td><Formula inline tex={String.raw`r_1=-0.02`} /></td><td><Formula inline tex={String.raw`G_1=-0.02-0.01+1.03=1.00`} /></td></tr></tbody></table></div><p>终局分数因此进入所有更早 Token 的 Return；越早的 Token 还会累计更多后续 KL penalty。这完成了最基本的 credit assignment，但并不意味着系统知道哪一步推理真正有功。只有终局 Reward 时，同一条轨迹中许多 Token 仍会得到高度相关的学习信号。</p></section>

    <section className="prose-section" id="chapter-9"><div className="prose-heading"><span>09</span><div><p>LEARN A BASELINE</p><h2>Critic 与 TD Error 为什么会出现？</h2></div></div><p>直接用采样得到的 <Formula inline tex={String.raw`G_t`} /> 估计动作价值虽然直观，但方差很高。Critic 用参数 <Formula inline tex={String.raw`\psi`} /> 学习当前状态的期望 Return：</p><Formula label="Critic 的目标" tex={String.raw`V_\psi(s_t)\approx V^\pi(s_t)=\mathbb E_\pi[G_t\mid s_t]`} /><p>最直接的 Advantage 样本是 <Formula inline tex={String.raw`G_t-V_\psi(s_t)`} />。但它要等到完整回答结束才能得到。另一方面，Value 应满足 Bellman 关系：当前价值约等于当前 Reward 加上下一个状态价值。两边的差就是 TD Error：</p><Formula label="一步 Temporal-Difference Residual" tex={String.raw`\delta_t=r_t^{\mathrm{shape}}+\gamma V_\psi(s_{t+1})-V_\psi(s_t)`} /><p>可以把它读成一次“超出预期的惊喜”：<b>实际收到的当前 Reward + 到达新前缀后的最新预测 − 旧前缀的原预测</b>。若 Critic 准确，那么给定动作后的 <Formula inline tex={String.raw`\delta_t`} /> 的条件期望就是该动作的 Advantage。</p><Formula label="Critic 的回归损失" tex={String.raw`\mathcal L_V(\psi)=\mathbb E_t\!\left[\left(V_\psi(s_t)-\widehat G_t^{\mathrm{target}}\right)^2\right]`} /><p>Critic 不是在监督“这一步推理在语义上是否正确”。它只预测在当前 Policy、当前 Reward 定义下，从这个前缀继续生成的期望累计回报。</p></section>

    <section className="prose-section" id="chapter-10"><div className="prose-heading"><span>10</span><div><p>DERIVING GENERALIZED ADVANTAGE ESTIMATION</p><h2>GAE 为什么是 TD Error 的加权和？</h2></div></div><p>一步 TD Error 只向前看一步，强依赖 Critic 的预测；完整 Monte Carlo Return 看完整条轨迹，几乎不依赖中途 bootstrap，但随机性很大。先把连续 <Formula inline tex={String.raw`k`} /> 个 TD Error 相加：</p><Formula label="k-Step Advantage Estimator" className="compact-latex" tex={String.raw`\begin{aligned}\widehat A_t^{(k)}&=\sum_{l=0}^{k-1}\gamma^l\delta_{t+l}\\&=-V_\psi(s_t)+\sum_{l=0}^{k-1}\gamma^l r_{t+l}^{\mathrm{shape}}+\gamma^kV_\psi(s_{t+k}).\end{aligned}`} /><p>中间的 Value 项会两两抵消，这就是第二行的来源。当 <Formula inline tex={String.raw`k=1`} /> 时，它只是一步 TD；当 <Formula inline tex={String.raw`k`} /> 一直延伸到终点且终止状态 Value 为零时，它变成 <Formula inline tex={String.raw`G_t-V_\psi(s_t)`} />。</p><p>GAE 再对不同长度的 <Formula inline tex={String.raw`k`} />-step estimator 做指数加权。代数化简后，得到最常见的形式：</p><Formula label="Generalized Advantage Estimation" className="compact-latex" tex={String.raw`\widehat A_t^{\mathrm{GAE}(\gamma,\lambda)}=(1-\lambda)\sum_{k=1}^{\infty}\lambda^{k-1}\widehat A_t^{(k)}=\sum_{l=0}^{T-t}(\gamma\lambda)^l\delta_{t+l}`} /><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>设置</th><th>近似形式</th><th>主要权衡</th></tr></thead><tbody><tr><td><Formula inline tex={String.raw`\lambda=0`} /></td><td><Formula inline tex={String.raw`\widehat A_t=\delta_t`} /></td><td>更依赖 Critic；通常低方差、高 bootstrap 偏差</td></tr><tr><td><Formula inline tex={String.raw`0<\lambda<1`} /></td><td>混合多种时间跨度</td><td>在偏差与方差之间折中</td></tr><tr><td><Formula inline tex={String.raw`\lambda=1`} /></td><td><Formula inline tex={String.raw`\widehat A_t=G_t-V_\psi(s_t)`} /></td><td>更接近 Monte Carlo；通常高方差、少依赖中途 bootstrap</td></tr></tbody></table></div><aside className="answer-first"><span>最重要的概念纠正</span><p><Formula inline tex={String.raw`\widehat A_t^{\mathrm{GAE}}`} /> <b>不是奖励函数</b>。计算顺序是 <Formula inline tex={String.raw`r_t^{\mathrm{shape}}\rightarrow G_t`} /> 与 <Formula inline tex={String.raw`V_\psi\rightarrow\delta_t\rightarrow\widehat A_t^{\mathrm{GAE}}`} />。前者定义环境给了什么反馈，后者估计某个 Token 相对当前平均行为好多少。</p></aside></section>

    <section className="prose-section" id="chapter-11"><div className="prose-heading"><span>11</span><div><p>REUSE ROLLOUTS WITHOUT PRETENDING THEY ARE NEW</p><h2>为什么 PPO 还需要 Old Policy 与 Importance Ratio？</h2></div></div><p>如果每更新一次参数都重新生成海量文本，样本利用率会很低。PPO 先冻结一份 <Formula inline tex={String.raw`\pi_{\mathrm{old}}`} /> 生成 rollouts，再对同一批数据做多个 minibatch epoch。可是更新后的 <Formula inline tex={String.raw`\pi_\theta`} /> 已经不再是采样这些动作的分布，因此需要用概率比修正：</p><Formula label="逐 Token Importance Ratio" tex={String.raw`\rho_t(\theta)=\frac{\pi_\theta(a_t\mid s_t)}{\pi_{\mathrm{old}}(a_t\mid s_t)}=\exp\!\left(\log\pi_\theta(a_t\mid s_t)-\log\pi_{\mathrm{old}}(a_t\mid s_t)\right)`} /><p><Formula inline tex={String.raw`\rho_t>1`} /> 表示新策略比行为策略更偏爱这枚已采样 Token，<Formula inline tex={String.raw`\rho_t<1`} /> 表示更不偏爱。未经裁剪的代理目标是：</p><Formula label="Importance-Weighted Policy Surrogate" tex={String.raw`L^{\mathrm{PG}}(\theta)=\mathbb E_t\!\left[\rho_t(\theta)\widehat A_t\right]`} /><p>Old Policy 解决的是<b>数据由谁采样</b>；Reference Policy 解决的是<b>长期不希望偏离谁</b>。前者通常每轮更新快照，后者通常从 SFT 初始化后长期冻结。</p></section>

    <section className="prose-section" id="chapter-12"><div className="prose-heading"><span>12</span><div><p>THE PROXIMAL STEP</p><h2>PPO 的 Clip Objective 究竟在限制什么？</h2></div></div><p>如果在同一批旧数据上训练太久，概率比可能远离 <Formula inline tex={String.raw`1`} />，此时样本已经不能可靠代表新策略。PPO 选择“原始收益”和“裁剪后收益”中更保守的一项：</p><Formula label="PPO Clipped Surrogate Objective" className="compact-latex" tex={String.raw`L^{\mathrm{CLIP}}(\theta)=\mathbb E_t\!\left[\min\!\left(\rho_t\widehat A_t,\operatorname{clip}(\rho_t,1-\epsilon,1+\epsilon)\widehat A_t\right)\right]`} /><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>Advantage</th><th>希望发生什么</th><th>Clip 后不再额外奖励什么</th></tr></thead><tbody><tr><td><Formula inline tex={String.raw`\widehat A_t>0`} /></td><td>提高该 Token 概率</td><td>把 <Formula inline tex={String.raw`\rho_t`} /> 推得远高于 <Formula inline tex={String.raw`1+\epsilon`} /></td></tr><tr><td><Formula inline tex={String.raw`\widehat A_t<0`} /></td><td>降低该 Token 概率</td><td>把 <Formula inline tex={String.raw`\rho_t`} /> 压得远低于 <Formula inline tex={String.raw`1-\epsilon`} /></td></tr></tbody></table></div><p>这里的 <Formula inline tex={String.raw`\min`} /> 不是总选择数值更小的概率，而是选择对策略改进更悲观的 surrogate。它使“朝有利方向走得过远”失去额外收益。</p><aside className="text-note"><b>Clip 不是硬约束</b><p>它不保证每个 ratio 都在区间内，也不保证参数距离或真实 KL 严格受限。训练仍需监控 empirical KL、clip fraction、ratio 分布，并可在 KL 超过阈值时 early stop。</p></aside></section>

    <section className="prose-section" id="chapter-13"><div className="prose-heading"><span>13</span><div><p>PUT EVERY ROLE BACK TOGETHER</p><h2>一轮完整的 LLM PPO 训练怎样运行？</h2></div></div><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>模型角色</th><th>负责什么</th><th>一轮内是否更新</th></tr></thead><tbody><tr><td>Actor <Formula inline tex={String.raw`\pi_\theta`} /></td><td>输出 Token 概率，也是最终要训练的模型</td><td>更新</td></tr><tr><td>Old Policy <Formula inline tex={String.raw`\pi_{\mathrm{old}}`} /></td><td>生成当前 Rollout 并保存行为 Log Probability</td><td>冻结，下一轮再同步</td></tr><tr><td>Reference <Formula inline tex={String.raw`\pi_{\mathrm{ref}}`} /></td><td>提供长期 KL 基准</td><td>通常长期冻结</td></tr><tr><td>Reward Model <Formula inline tex={String.raw`r_\phi`} /></td><td>给完整回答打分</td><td>通常冻结</td></tr><tr><td>Critic <Formula inline tex={String.raw`V_\psi`} /></td><td>预测每个前缀的期望 Return</td><td>更新</td></tr></tbody></table></div><div className="formula-sequence"><div><span>01 · SNAPSHOT</span><Formula className="sequence-latex" tex={String.raw`\pi_{\mathrm{old}}\leftarrow\pi_\theta`} /></div><div><span>02 · ROLLOUT</span><Formula className="sequence-latex" tex={String.raw`y\sim\pi_{\mathrm{old}}(\cdot\mid x)`} /></div><div><span>03 · SCORE</span><Formula className="sequence-latex" tex={String.raw`r_\phi(x,y),\;\log\pi_{\mathrm{ref}},\;V_\psi(s_t)`} /></div><div><span>04 · SHAPE</span><Formula className="sequence-latex" tex={String.raw`r_t^{\mathrm{shape}}\leftarrow r_\phi-\beta\,\Delta\log\pi_t`} /></div><div><span>05 · ESTIMATE</span><Formula className="sequence-latex" tex={String.raw`\delta_t\rightarrow\widehat A_t^{\mathrm{GAE}},\;\widehat G_t^{\mathrm{target}}`} /></div><div><span>06 · ACTOR UPDATE</span><Formula className="sequence-latex" tex={String.raw`\min(\rho_t\widehat A_t,\operatorname{clip}(\rho_t)\widehat A_t)`} /></div><div><span>07 · CRITIC UPDATE</span><Formula className="sequence-latex" tex={String.raw`\left(V_\psi(s_t)-\widehat G_t^{\mathrm{target}}\right)^2`} /></div><div><span>08 · MONITOR</span><Formula className="sequence-latex" tex={String.raw`D_{\mathrm{KL}},\;\text{clip fraction},\;\text{reward},\;\text{length}`} /></div></div><Formula label="常见的联合损失写法" className="compact-latex" tex={String.raw`\mathcal L_{\mathrm{total}}=-L^{\mathrm{CLIP}}+c_V\mathcal L_V-c_H\mathcal H(\pi_\theta)`} /><p>实现可能把 KL 作为 Reward shaping，也可能作为显式 loss penalty，或者两者配合自适应系数；应以具体代码的符号与聚合方式为准。同一批 rollouts 做多个 epoch 能提高样本利用率，但会加剧 Policy lag，因此更新轮数不能无限增加。</p></section>

    <section className="prose-section" id="chapter-14"><div className="prose-heading"><span>14</span><div><p>WHAT PPO SOLVES AND WHAT IT DOES NOT</p><h2>LLM PPO 的主要问题与改进路线</h2></div></div><div className="reason-list compact-reasons"><article><span>01</span><div><h3>Critic 昂贵且会产生估计误差</h3><p>长文本前缀的 Value 难学，还要额外保存模型参数、激活与 Optimizer State。错误 Critic 会通过 GAE 系统性影响 Actor。</p></div></article><article><span>02</span><div><h3>Credit Assignment 仍然粗糙</h3><p>终局 Reward 能传回所有 Token，但不能自动判断哪一步推理关键。Process Reward 或更细的 Verifier 才能增加中间监督。</p></div></article><article><span>03</span><div><h3>Policy Lag 与概率比失真</h3><p>Rollout 服务和训练器不同步、同一批数据训练过久，都可能让 Old Policy 数据过期，使 Ratio 方差变大。</p></div></article><article><span>04</span><div><h3>Reward Hacking 不会被 Clip 修复</h3><p>Clip 只控制更新方式。若 Reward Model 有漏洞，PPO 仍会稳定地优化错误目标。</p></div></article><article><span>05</span><div><h3>长度与 Token 聚合会改变目标</h3><p>KL 是求和还是平均、Loss 是 Token Mean 还是 Sequence Mean，都会造成不同的长短回答偏好。</p></div></article><article><span>06</span><div><h3>超参数高度耦合</h3><p>Reward Scale、KL 系数、Clip Range、GAE 参数、Value 权重、Epoch 数与 Batch Size 会共同改变有效步长。</p></div></article></div><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>路线</th><th>改变了什么</th><th>主要动机</th></tr></thead><tbody><tr><td>Adaptive KL / Early Stop</td><td>按实际 KL 调节约束或提前停止</td><td>补足 Clip 不是硬约束的问题</td></tr><tr><td>PPO-ptx</td><td>混入预训练目标</td><td>缓解能力退化与 Alignment Tax</td></tr><tr><td>RLOO</td><td>用同 Prompt 其他采样的 Reward 作 baseline</td><td>去掉独立 Critic</td></tr><tr><td><a className="term-link" href="/training/grpo">GRPO</a></td><td>用组内相对 Reward 构造 Advantage</td><td>推理 RL 中降低 Value Model 成本</td></tr><tr><td><a className="term-link" href="/training/dpo">DPO</a> / <a className="term-link" href="/training/kto">KTO</a></td><td>把在线 RL 改成离线偏好目标</td><td>数据固定时简化训练系统</td></tr></tbody></table></div><p>在 <a className="term-link" href="/training/reasoning-rl">Reasoning RL</a> 中，可验证 Reward 支持在线探索新解法，因此 PPO 类方法依然有价值；但长 CoT 的 Critic 成本与估值难度，也解释了为什么无 Critic 的组相对方法受到重视。</p></section>

    <section className="prose-section rms-qa" id="qa"><div className="prose-heading"><span>15</span><div><p>QUESTIONS AS CONNECTIONS</p><h2>关联 QA</h2></div></div><div className="qa-list">
      <details id="qa-1" open><summary><span>Q1</span>PPO 与 <a className="term-link" href="/training/rlhf">RLHF</a> 是一回事吗？</summary><div><p>不是。<a className="term-link" href="/training/rlhf">RLHF</a> 是利用人类偏好信号对齐模型的训练范式，PPO 是其中可选的在线策略优化算法。PPO 也能优化规则 Verifier，RLHF 也能改用其他优化方法。</p></div></details>
      <details id="qa-2"><summary><span>Q2</span>为什么一个 Action 只是一枚 Token，而不是完整回答？</summary><div><p>因为自回归模型每一步真正作出的随机选择是下一枚 Token，下一状态也由这枚 Token 决定。完整回答是多个动作构成的 trajectory。也可以在更高层抽象成序列动作，但逐 Token 表示能直接使用模型已有的条件概率。</p></div></details>
      <details id="qa-3"><summary><span>Q3</span>策略梯度为什么使用 Log Probability？</summary><div><p>因为 <Formula inline tex={String.raw`\nabla p=p\nabla\log p`} />。它把对采样概率的求导转换为对模型 Log Probability 的求导，使不可微 Reward 只充当权重，梯度仍能穿过语言模型。</p></div></details>
      <details id="qa-4"><summary><span>Q4</span>Reward、Return 与 Advantage 到底有什么区别？</summary><div><p><Formula inline tex={String.raw`r_t`} /> 是当前一步收到的反馈；<Formula inline tex={String.raw`G_t`} /> 是从当前时刻开始的未来 Reward 累计；<Formula inline tex={String.raw`A_t`} /> 是执行当前动作后的预期 Return 相对状态平均 Value 的差。三者依次回答“这一步得到什么”“未来一共得到什么”“这一步选得是否比平均更好”。</p></div></details>
      <details id="qa-5"><summary><span>Q5</span>只有终局分数时，前面的 Token 怎么学习？</summary><div><p>终局分数包含在每个更早时刻的 Return 中，再通过 Advantage 加权这些 Token 的 Log Probability 梯度。因此它能传播回去，但信号很粗：同一回答中很多 Token 共享相近结果，并不等于模型准确识别了关键推理步骤。</p></div></details>
      <details id="qa-6"><summary><span>Q6</span>逐 Token Shaped Reward 为什么是“KL 惩罚 + 终局 Reward”？</summary><div><p>因为序列 Log Probability Ratio 可以严格分解成各 Token Log Ratio 的和。把每项负 KL 代价放回对应 Token，并只在终止步加入序列 Reward，在 <Formula inline tex={String.raw`\gamma=1`} /> 时逐步 Reward 的总和就等于原来的序列级正则目标。</p></div></details>
      <details id="qa-7"><summary><span>Q7</span>折扣因子 <Formula inline tex={String.raw`\gamma`} /> 在文本生成中有什么意义？</summary><div><p>它降低遥远未来 Reward 对当前动作的权重。传统无限时域任务需要它保证回报有限；文本生成是有限 Episode，常取接近 <Formula inline tex={String.raw`1`} /> 或等于 <Formula inline tex={String.raw`1`} />。若取值更小，会让早期 Token 接收到的终局信号更弱。</p></div></details>
      <details id="qa-8"><summary><span>Q8</span>Critic 是在判断一段推理是否正确吗？</summary><div><p>不是。Critic 预测的是从当前 Prompt 与生成前缀继续按 Policy 采样的期望 Return。除非 Reward 本身精确反映推理正确性，否则 Value 不能解释成步骤正确率。</p></div></details>
      <details id="qa-9"><summary><span>Q9</span>TD Error 为什么可以理解为一步预测误差？</summary><div><p>旧预测是 <Formula inline tex={String.raw`V(s_t)`} />；走一步后已观察到 <Formula inline tex={String.raw`r_t`} />，并得到新状态预测 <Formula inline tex={String.raw`V(s_{t+1})`} />。两者的差 <Formula inline tex={String.raw`r_t+\gamma V(s_{t+1})-V(s_t)`} /> 正是 Value 对这次转移预测得过高还是过低。</p></div></details>
      <details id="qa-10"><summary><span>Q10</span>为什么说 GAE 不是奖励函数？</summary><div><p>Reward 在 GAE 之前就已定义。GAE 使用 Reward 与 Critic 组成 TD Error，再把多个跨度的 TD Error 加权，得到 Advantage 的估计值。它改变的是梯度权重的估计方式，不是环境或 Reward Model 的评分标准。</p></div></details>
      <details id="qa-11"><summary><span>Q11</span>Old Policy 与 Reference Policy 有什么区别？</summary><div><p>Old Policy 是生成当前训练批次的行为策略，用于 Importance Ratio，通常每轮刷新；Reference Policy 是长期 KL 锚点，用于防止模型偏离初始对齐模型，通常冻结。二者有时权重暂时相同，但算法角色不同。</p></div></details>
      <details id="qa-12"><summary><span>Q12</span>Clip 能保证新旧策略一定足够接近吗？</summary><div><p>不能。Clip 只让某些朝有利方向越界的 Ratio 不再增加 surrogate 收益，并不裁剪模型参数，也不硬性限制所有 Token Ratio 或整体 KL。因此还需要 KL 监控、Clip Fraction 与 Early Stopping。</p></div></details>
    </div></section>

    <section className="sources-section rms-sources"><div><p className="mini-label">PRIMARY SOURCES</p><h2>推导与 LLM 应用</h2></div><ol><li><a href="https://arxiv.org/abs/1506.02438" target="_blank" rel="noreferrer">High-Dimensional Continuous Control Using Generalized Advantage Estimation</a><span>2015</span></li><li><a href="https://arxiv.org/abs/1707.06347" target="_blank" rel="noreferrer">Proximal Policy Optimization Algorithms</a><span>2017</span></li><li><a href="https://arxiv.org/abs/2203.02155" target="_blank" rel="noreferrer">Training Language Models to Follow Instructions with Human Feedback</a><span>2022</span></li><li><a href="https://arxiv.org/abs/2402.14740" target="_blank" rel="noreferrer">Back to Basics: REINFORCE Leave-One-Out</a><span>2024</span></li><li><a href="https://arxiv.org/abs/2402.03300" target="_blank" rel="noreferrer">DeepSeekMath: Pushing the Limits of Mathematical Reasoning</a><span>2024</span></li></ol></section>
    <footer className="article-footer"><div><span>继续连接知识</span><strong>现在可以沿着同一条主线，比较在线 Actor–Critic、组相对更新与离线偏好优化分别省掉了什么。</strong></div><div className="footer-links"><a href="/training/rlhf">RLHF ↗</a><a href="/training/grpo">GRPO ↗</a><a href="/training/dpo">DPO ↗</a></div></footer>
  </main>
  <aside className="right-rail" aria-label="本页目录"><p>本页目录</p>{chapters.map(([no, label]) => <a href={no === "15" ? "#qa" : `#chapter-${Number(no)}`} key={no}><span>{no}</span>{label}</a>)}<RightQaIndex questions={qaQuestions} /><div className="reading-note"><span>15 章</span><div><i></i></div><small>公式密度 · 高</small></div></aside>
</div>; }
