import type { Metadata } from "next";
import { Formula } from "../../components/Formula";
import { RightQaIndex } from "../../components/RightQaIndex";
import { TrainingSidebar } from "../../components/TrainingSidebar";

const title = "什么是 RLHF？";
const description = "从大模型为何需要人类反馈出发，完整拆解 RLHF 的 SFT、偏好数据、奖励模型、策略优化、KL 约束、失效模式与后续改进。";
export const metadata: Metadata = { title, description, openGraph: { title, description, type: "article", images: [] }, twitter: { card: "summary", title, description, images: [] } };

const chapters = [["01","为什么需要人类反馈"],["02","它是流水线而非单一算法"],["03","SFT 与偏好数据"],["04","奖励模型"],["05","策略目标与 KL"],["06","完整训练架构"],["07","一次训练如何运行"],["08","主要问题"],["09","改进与推理强化"],["10","关联 QA"]];
const qaQuestions = ["它是一种具体算法吗？","人类需要逐 token 修改回答吗？","奖励模型为何只输出一个标量？","KL 约束到底限制什么？","奖励越高，模型就一定越好吗？","它与直接偏好优化有什么关系？","它与推理强化有什么区别？","训练完后还需要奖励模型吗？","偏好概率为什么变成带负号和 log 的损失？"];

export default function RLHFPage() {
  return <div className="site-shell">
    <header className="topbar"><a className="brand" href="/" aria-label="模见首页"><span className="brand-mark">模</span><span>模见 <small>Model Atlas</small></span></a><nav className="topnav" aria-label="主导航"><a className="active" href="/">知识库</a><a href="#chapter-1">训练导读</a><a href="#qa">QA 索引</a></nav><div className="top-actions"><a className="search-hint" href="#qa">⌘ K&nbsp;&nbsp;QA 速查</a><span className="edition">2026.08</span></div></header>
    <TrainingSidebar selected="rlhf" />
    <main className="article rms-article">
      <section className="hero rms-hero" id="top"><div className="breadcrumbs"><a href="/">知识库</a><span>/</span>训练与对齐<span>/</span>RLHF</div><div className="question-label"><span>POST-TRAINING · 003</span></div><p className="original-question">“预训练模型已经学会续写，SFT 也能模仿优秀答案，为什么大模型还需要人类反馈和强化学习？”</p><div className="eyebrow"><span></span>HUMAN PREFERENCE ALIGNMENT</div><h1>什么是 RLHF？</h1><p className="dek">RLHF 把“人觉得哪一个回答更好”变成可优化信号：先用示范建立可用策略，再从成对偏好训练 Reward Model，最后在不偏离参考模型过远的约束下提高高奖励回答的概率。</p><div className="hero-meta"><span>建立于 2026.08.20</span><i></i><span>38 分钟阅读</span><i></i><span>训练范式 + 公式</span></div><aside className="answer-first"><span>先定位概念层级</span><p>RLHF 是一套<b>数据—模型—优化流水线</b>，不是某一个损失函数。经典实现常用 <a className="term-link" href="/training/ppo">PPO</a> 做最后的在线策略更新，但也可以改用别的优化器；<a className="term-link" href="/training/dpo">DPO</a> 则把其中一类偏好优化改写为无需显式 Reward Model 和在线 rollout 的离线目标。</p></aside></section>

      <section className="prose-section" id="chapter-1"><div className="prose-heading"><span>01</span><div><p>WHY NEXT-TOKEN LOSS IS NOT ENOUGH</p><h2>为什么“会续写”不等于“会帮助用户”？</h2></div></div><p>预训练最大化语料中下一个 token 的似然。互联网文本同时包含正确答案、错误观点、争论、广告和有害内容；这个目标没有天然定义 helpful、honest、harmless，也不知道当前用户更偏好简洁还是详尽。</p><Formula label="预训练目标" tex={String.raw`\mathcal L_{\mathrm{PT}}(\theta)=-\mathbb E_{x\sim\mathcal D}\sum_t\log\pi_\theta(x_t\mid x_{<t})`} /><p>SFT 能让模型模仿示范，但每个 prompt 通常只有一个目标答案；它不能高效表达“两个都能回答，但 A 比 B 更合适”的相对判断。RLHF 的起因就是把这种难以写成标准答案的偏好转成训练信号。</p><aside className="boundary-box"><b>不是在对齐抽象的全人类价值</b><p>偏好来自具体标注规范、标注者群体和采样分布。最终模型更准确地说是对齐到这套数据生成过程，而不是获得了普适、无冲突的“人类价值函数”。</p></aside></section>

      <section className="prose-section" id="chapter-2"><div className="prose-heading"><span>02</span><div><p>PIPELINE, NOT ONE LOSS</p><h2>RLHF 包含哪三个阶段？</h2></div></div><div className="formula-sequence"><div><span>01 · SFT</span><Formula className="sequence-latex" tex={String.raw`\pi_{\mathrm{base}}\xrightarrow{\text{demonstrations}}\pi_{\mathrm{SFT}}`} /></div><div><span>02 · REWARD MODEL</span><Formula className="sequence-latex" tex={String.raw`(x,y_w,y_l)\longrightarrow r_\phi(x,y)`} /></div><div><span>03 · POLICY OPT.</span><Formula className="sequence-latex" tex={String.raw`\pi_{\mathrm{SFT}}\xrightarrow{\max\;r_\phi-\beta\mathrm{KL}}\pi_{\mathrm{aligned}}`} /></div></div><p>阶段二学习“如何评分”，阶段三才用这个评分改变生成策略。Reward Model 不负责生成文字；Policy 不直接看到“人类偏好”这个抽象概念，只接收由 Reward Model 近似出来的标量。</p></section>

      <section className="prose-section" id="chapter-3"><div className="prose-heading"><span>03</span><div><p>DEMONSTRATIONS AND COMPARISONS</p><h2>SFT 数据与偏好数据分别长什么样？</h2></div></div><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>阶段</th><th>记录</th><th>监督含义</th></tr></thead><tbody><tr><td>SFT</td><td><Formula inline tex={String.raw`(x,y^*)`} /></td><td>逐 token 模仿一个高质量示范</td></tr><tr><td>Preference</td><td><Formula inline tex={String.raw`(x,y_w,y_l)`} /></td><td>同一 prompt 下，chosen 胜过 rejected</td></tr></tbody></table></div><p>偏好标注通常不要求人类逐字修订。系统从同一个 prompt 采样多个回答，标注者排序或选择较好者，再拆成 pair。它表达的是相对顺序，不直接给出“好 0.83 分、差 0.27 分”的绝对分数。</p><Formula label="一条二元偏好" tex={String.raw`y_w\succ y_l\mid x`} /></section>

      <section className="prose-section" id="chapter-4"><div className="prose-heading"><span>04</span><div><p>LEARN A SCALAR PREFERENCE MODEL</p><h2>Reward Model 怎样从比较中学习？</h2></div></div><p>Reward Model 读取 prompt 与完整 response，在末端产生标量 <Formula inline tex={String.raw`r_\phi(x,y)`} />。Bradley–Terry 假设两回答的胜率由分数差决定：</p><Formula label="偏好概率" tex={String.raw`P_\phi(y_w\succ y_l\mid x)=\sigma\!\left(r_\phi(x,y_w)-r_\phi(x,y_l)\right)`} /><Formula label="Reward Model 损失" tex={String.raw`\mathcal L_{\mathrm{RM}}(\phi)=-\mathbb E\log\sigma\!\left(r_\phi(x,y_w)-r_\phi(x,y_l)\right)`} /><p>只看差值意味着奖励的绝对零点不可辨识；真正有意义的是同一 prompt 下的排序。模型会把标注规范中的帮助性、安全性、风格等维度压缩进一个标量，这既便于优化，也会隐藏维度冲突。</p></section>

      <section className="prose-section" id="chapter-5"><div className="prose-heading"><span>05</span><div><p>REWARD WITH A TRUST REGION</p><h2>为什么不能只最大化 Reward Model 分数？</h2></div></div><Formula label="KL-regularized policy objective" className="compact-latex" tex={String.raw`\max_\theta\;\mathbb E_{x\sim\mathcal D,\,y\sim\pi_\theta(\cdot\mid x)}\!\left[r_\phi(x,y)-\beta\log\frac{\pi_\theta(y\mid x)}{\pi_{\mathrm{ref}}(y\mid x)}\right]`} /><p>第一项鼓励偏好分数，第二项惩罚策略远离冻结的参考模型。没有约束时，Policy 会搜索 Reward Model 的漏洞，把分布推到评分器没见过的区域；此时分数可能继续升，真实人类质量却下降。</p><aside className="text-note"><b><Formula inline tex={String.raw`\beta`} /> 的含义</b><p>它控制奖励与保守程度的权衡。过小容易 reward overoptimization；过大则几乎不允许策略离开参考模型，学不到明显偏好变化。</p></aside></section>

      <section className="prose-section" id="chapter-6"><div className="prose-heading"><span>06</span><div><p>THE CLASSIC FIVE-PART SYSTEM</p><h2>经典在线 RLHF 训练时同时有哪些模型？</h2></div></div><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>组件</th><th>是否更新</th><th>职责</th></tr></thead><tbody><tr><td>Policy / Actor</td><td>是</td><td>生成 response，并接收策略梯度</td></tr><tr><td>Reference Policy</td><td>否</td><td>计算 KL，定义“不要偏太远”</td></tr><tr><td>Reward Model</td><td>通常否</td><td>给完整 response 评分</td></tr><tr><td>Value / Critic</td><td>是</td><td>估计前缀的未来 return，构造 advantage</td></tr><tr><td>Rollout Engine</td><td>服务</td><td>按当前或旧 Policy 批量采样</td></tr></tbody></table></div><p>参数副本、optimizer states、长序列 activation 与在线生成共同造成很高显存和系统复杂度。这也是 <a className="term-link" href="/training/dpo">DPO</a>、RLOO 和 <a className="term-link" href="/training/grpo">GRPO</a> 等路线试图简化的部分。</p></section>

      <section className="prose-section" id="chapter-7"><div className="prose-heading"><span>07</span><div><p>ONE ONLINE ITERATION</p><h2>一轮策略训练具体发生什么？</h2></div></div><div className="formula-sequence"><div><span>01 · PROMPTS</span><Formula className="sequence-latex" tex={String.raw`x\sim\mathcal D_{\mathrm{prompt}}`} /></div><div><span>02 · ROLLOUTS</span><Formula className="sequence-latex" tex={String.raw`y\sim\pi_{\mathrm{old}}(\cdot\mid x)`} /></div><div><span>03 · SCORES</span><Formula className="sequence-latex" tex={String.raw`R=r_\phi(x,y)-\beta\,\mathrm{KL}_\mathrm{sample}`} /></div><div><span>04 · ADVANTAGES</span><Formula className="sequence-latex" tex={String.raw`\widehat A_t\leftarrow R,\,V_\psi(s_t)`} /></div><div><span>05 · UPDATE</span><Formula className="sequence-latex" tex={String.raw`\theta,\psi\leftarrow\operatorname{PPOUpdate}(\mathcal B)`} /></div></div><p>这是一种在线训练：Policy 改变后要重新采样，因为旧回答不再代表新策略的分布。复用过旧 rollout 会加大 importance ratio 方差和 policy lag。</p></section>

      <section className="prose-section" id="chapter-8"><div className="prose-heading"><span>08</span><div><p>FAILURE MODES</p><h2>RLHF 的主要问题在哪里？</h2></div></div><div className="reason-list compact-reasons"><article><span>01</span><div><h3>Reward hacking 与过优化</h3><p>Policy 学会利用评分器的盲点，而不是变得真正更好。</p></div></article><article><span>02</span><div><h3>标注者与规范偏差</h3><p>一个总分掩盖不同人群、文化和任务之间相互冲突的偏好。</p></div></article><article><span>03</span><div><h3>分布漂移</h3><p>Reward Model 只在早期候选上训练，后期 Policy 产生的新型回答可能超出其可靠范围。</p></div></article><article><span>04</span><div><h3>Alignment tax</h3><p>过强对齐可能损害预训练能力、多样性或校准；InstructGPT 以混入预训练梯度的 <a className="term-link" href="/training/ppo">PPO-ptx</a> 缓解。</p></div></article><article><span>05</span><div><h3>系统与数据成本</h3><p>需要持续采样、偏好标注、多个模型副本和稳定的在线训练基础设施。</p></div></article></div></section>

      <section className="prose-section" id="chapter-9"><div className="prose-heading"><span>09</span><div><p>IMPROVEMENTS AND REASONING</p><h2>后来有哪些改进，和 Reasoning RL 怎样呼应？</h2></div></div><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>路线</th><th>主要改动</th><th>解决什么</th></tr></thead><tbody><tr><td><a className="term-link" href="/training/dpo">DPO</a></td><td>直接优化 chosen/rejected log-ratio</td><td>省去显式 RM 与在线 rollout</td></tr><tr><td>RLAIF / Constitutional AI</td><td>用 AI 反馈与原则辅助偏好数据</td><td>扩展监督规模，但偏差不会自动消失</td></tr><tr><td>迭代式对齐</td><td>用新 Policy 候选再标注、再训 RM</td><td>缩小 Reward Model 的分布漂移</td></tr><tr><td>Reward ensembles / uncertainty</td><td>多个评分器或不确定性惩罚</td><td>降低单一评分器漏洞被利用</td></tr><tr><td><a className="term-link" href="/training/reasoning-rl">Reasoning RL</a></td><td>以答案/代码 Verifier 替代主观偏好 RM</td><td>在可验证任务上提供更客观 reward</td></tr></tbody></table></div><p><a className="term-link" href="/training/reasoning-rl">Reasoning RL</a> 仍继承策略采样、reward、KL 和探索等思想，但 reward 来源不同：它更常优化可自动验证的正确性，并可用 <a className="term-link" href="/training/grpo">GRPO</a> 省掉 Critic；开放域帮助性与安全性则更接近经典 RLHF。</p></section>

      <section className="prose-section rms-qa" id="qa"><div className="prose-heading"><span>10</span><div><p>QUESTIONS AS CONNECTIONS</p><h2>关联 QA</h2></div></div><div className="qa-list">
        <details id="qa-1" open><summary><span>Q1</span>RLHF 是一种具体算法吗？</summary><div><p>不是。它是“用人类反馈训练语言模型”的范式，包含示范、偏好比较、Reward Model 与策略优化。最后一步常用 <a className="term-link" href="/training/ppo">PPO</a>，但二者不能画等号。</p></div></details>
        <details id="qa-2"><summary><span>Q2</span>人类需要逐 token 修改回答吗？</summary><div><p>通常不需要。标注者只需在同一 prompt 的候选中排序或选优；逐 token 的监督主要来自 SFT 示范，而偏好阶段提供 response-level 相对信号。</p></div></details>
        <details id="qa-3"><summary><span>Q3</span>奖励模型为何只输出一个标量？</summary><div><p>标量让策略优化有统一目标，但会压缩帮助性、安全性、事实性和风格之间的冲突。工程上常用多维 reward、规则约束或分阶段优化补充。</p></div></details>
        <details id="qa-4"><summary><span>Q4</span>KL 约束到底限制什么？</summary><div><p>它限制新 Policy 对完整回答的概率分布偏离参考 Policy 的程度，不是限制参数欧氏距离。两个参数很近的模型也可能在某些 prompt 上产生很不同的分布。</p></div></details>
        <details id="qa-5"><summary><span>Q5</span>奖励越高，模型就一定越好吗？</summary><div><p>不一定。训练只保证在当前评分器下更高；若评分器有漏洞或输入超出训练分布，代理 reward 上升可能伴随真实人类质量下降。</p></div></details>
        <details id="qa-6"><summary><span>Q6</span>RLHF 与 <a className="term-link" href="/training/dpo">DPO</a> 有什么关系？</summary><div><p>前者是更宽的偏好对齐范式；后者是一种直接偏好优化算法。<a className="term-link" href="/training/dpo">DPO</a> 可使用相同的 chosen/rejected 数据，但不单独训练 Reward Model，也不在训练时在线采样并做传统 RL。</p></div></details>
        <details id="qa-7"><summary><span>Q7</span>RLHF 与 <a className="term-link" href="/training/reasoning-rl">Reasoning RL</a> 有什么区别？</summary><div><p>经典 RLHF 主要从人类比较学习开放域偏好；推理强化更常依赖数学答案、代码测试等 Verifier。优化器可以重叠，根本差异主要在任务分布和 reward 定义。</p></div></details>
        <details id="qa-8"><summary><span>Q8</span>训练完后还需要奖励模型吗？</summary><div><p>通常推理部署只保留最终 Policy，不需要 Reward Model 或 Critic。它们是训练期组件；但后续迭代、监控和新数据筛选仍可能继续使用。</p></div></details>
        <details id="qa-9"><summary><span>Q9</span>偏好概率为什么会变成带负号和 <Formula inline tex={String.raw`\log`} /> 的 Reward Model 损失？</summary><div>
          <p>因为前一个公式定义的是<b>单条偏好发生的概率</b>，后一个公式定义的是<b>怎样用许多已观察到的偏好训练参数</b>。它们不是两个互相替换的概率公式，而是从概率模型到最大似然训练目标的关系。</p>
          <p>先记分数差和模型预测的偏好概率为：</p>
          <Formula className="qa-latex" label="Score difference and preference probability" tex={String.raw`\Delta r_\phi=r_\phi(x,y_w)-r_\phi(x,y_l),\qquad p_\phi=\sigma(\Delta r_\phi)`} />
          <p>训练数据已经告诉我们这一对中 <Formula inline tex={String.raw`y_w`} /> 胜过 <Formula inline tex={String.raw`y_l`} />。对 <Formula inline tex={String.raw`N`} /> 个相互独立的偏好样本，模型把所有已观察结果同时解释出来的联合似然是各样本概率的乘积：</p>
          <Formula className="qa-latex" label="Dataset likelihood" tex={String.raw`\mathcal J(\phi)=\prod_{n=1}^{N}p_\phi^{(n)}=\prod_{n=1}^{N}\sigma\!\left(\Delta r_\phi^{(n)}\right)`} />
          <p>最大似然训练希望让这个乘积尽可能大。由于 <Formula inline tex={String.raw`\log`} /> 是严格单调递增函数，最大化乘积与最大化它的对数拥有相同的最优参数；同时，<Formula inline tex={String.raw`\log(ab)=\log a+\log b`} /> 会把大量小概率的乘积变成容易计算的求和：</p>
          <Formula className="qa-latex" label="Log-likelihood has the same maximizer" tex={String.raw`\arg\max_\phi\prod_{n=1}^{N}p_\phi^{(n)}=\arg\max_\phi\sum_{n=1}^{N}\log p_\phi^{(n)}`} />
          <p>训练框架通常按“最小化 loss”实现，而上式是“最大化 log-likelihood”，所以再乘一个负号，把最大化问题改写成等价的最小化问题：</p>
          <Formula className="qa-latex" label="Negative log-likelihood" tex={String.raw`\mathcal L_{\mathrm{RM}}(\phi)=-\frac{1}{N}\sum_{n=1}^{N}\log\sigma\!\left(\Delta r_\phi^{(n)}\right)=-\mathbb E\log\sigma\!\left(\Delta r_\phi\right)`} />
          <p>所以，<Formula inline tex={String.raw`\log`} /> 来自最大似然：它保持最优解不变、把连乘变成求和，并避免许多小概率直接相乘造成数值下溢；负号只是在“最大化得分”和“最小化损失”两种记法之间转换。</p>
          <p>它还有一个重要的梯度效果。对单条 chosen-wins 样本，令 <Formula inline tex={String.raw`p=\sigma(\Delta r)`} />，则：</p>
          <Formula className="qa-latex" label="Gradient with respect to the score margin" tex={String.raw`\frac{\partial[-\log\sigma(\Delta r)]}{\partial\Delta r}=\sigma(\Delta r)-1=p-1`} />
          <p>当模型严重判断错误、<Formula inline tex={String.raw`p\approx 0`} /> 时，梯度接近 <Formula inline tex={String.raw`-1`} />，会有力地增大 chosen 与 rejected 的分数差；当 <Formula inline tex={String.raw`p\approx 1`} /> 时，梯度接近 <Formula inline tex={String.raw`0`} />，说明这一对已经学会。若数据同时显式包含标签 <Formula inline tex={String.raw`z\in\{0,1\}`} />，完整形式就是二元交叉熵：</p>
          <Formula className="qa-latex" label="General binary cross-entropy" tex={String.raw`\mathcal L=-\mathbb E\left[z\log p+(1-z)\log(1-p)\right]`} />
          <p>当前偏好数据总把胜者记作 <Formula inline tex={String.raw`y_w`} />，相当于每条记录都已经重排成 <Formula inline tex={String.raw`z=1`} />，因此第二项消失，得到文档里的简写。</p>
        </div></details>
      </div></section>
      <section className="sources-section rms-sources"><div><p className="mini-label">PRIMARY SOURCES</p><h2>经典流程与后续路线</h2></div><ol><li><a href="https://arxiv.org/html/2203.02155" target="_blank" rel="noreferrer">InstructGPT · Human-feedback pipeline</a><span>2022</span></li><li><a href="https://arxiv.org/abs/1707.06347" target="_blank" rel="noreferrer">Proximal Policy Optimization Algorithms</a><span>2017</span></li><li><a href="https://arxiv.org/html/2305.18290" target="_blank" rel="noreferrer">Direct Preference Optimization</a><span>2023</span></li><li><a href="https://arxiv.org/abs/2212.08073" target="_blank" rel="noreferrer">Constitutional AI: Harmlessness from AI Feedback</a><span>2022</span></li></ol></section>
      <footer className="article-footer"><div><span>继续连接知识</span><strong>继续拆解在线优化器、离线偏好目标，以及可验证推理中的组相对更新。</strong></div><div className="footer-links"><a href="/training/reward-model">Reward Model ↗</a><a href="/training/ppo">PPO ↗</a><a href="/training/dpo">DPO ↗</a><a href="/training/grpo">GRPO ↗</a><a href="/training/reasoning-rl">Reasoning RL ↗</a></div></footer>
    </main>
    <aside className="right-rail" aria-label="本页目录"><p>本页目录</p>{chapters.map(([no,label])=><a href={no==="10"?"#qa":`#chapter-${Number(no)}`} key={no}><span>{no}</span>{label}</a>)}<RightQaIndex questions={qaQuestions}/><div className="reading-note"><span>10 章</span><div><i></i></div><small>公式密度 · 中高</small></div></aside>
  </div>;
}
