import type { Metadata } from "next";
import { Formula } from "../../components/Formula";
import { RightQaIndex } from "../../components/RightQaIndex";
import { TrainingSidebar } from "../../components/TrainingSidebar";

const title="什么是 DPO？";
const description="从大模型偏好对齐为何要摆脱显式奖励模型和在线强化学习出发，推导 DPO 损失、参考模型校正、训练架构、边界与改进。";
export const metadata:Metadata={title,description,openGraph:{title,description,type:"article",images:[]},twitter:{card:"summary",title,description,images:[]}};
const chapters=[["01","为什么直接优化偏好"],["02","数据长什么样"],["03","从 KL 偏好目标出发"],["04","消去奖励函数"],["05","DPO 损失"],["06","梯度直觉"],["07","训练架构"],["08","与 RL 和推理的边界"],["09","问题与改进"],["10","关联 QA"]];
const qaQuestions=["它是强化学习吗？","为什么还需要 Reference Model？","Chosen 必须是完全正确答案吗？","是否训练 Reward Model？","β 越大是不是学得越激进？","为什么不需要 Rollout？","它能直接替代推理强化吗？","最容易遇到什么数据问题？"];
export default function DPOPage(){return <div className="site-shell">
<header className="topbar"><a className="brand" href="/" aria-label="模见首页"><span className="brand-mark">模</span><span>模见 <small>Model Atlas</small></span></a><nav className="topnav"><a className="active" href="/">知识库</a><a href="#chapter-1">训练导读</a><a href="#qa">QA 索引</a></nav><div className="top-actions"><a className="search-hint" href="#qa">⌘ K&nbsp;&nbsp;QA 速查</a><span className="edition">2026.08</span></div></header><TrainingSidebar selected="dpo"/>
<main className="article rms-article"><section className="hero rms-hero" id="top"><div className="breadcrumbs"><a href="/">知识库</a><span>/</span>训练与对齐<span>/</span>DPO</div><div className="question-label"><span>PREFERENCE OPTIMIZATION · 005</span></div><p className="original-question">“已有 chosen/rejected 偏好对，为什么还要先训练 Reward Model，再跑昂贵又不稳定的在线 RL？能不能直接让模型更偏向 chosen？”</p><div className="eyebrow"><span></span>DIRECT PREFERENCE OPTIMIZATION</div><h1>什么是 DPO？</h1><p className="dek">DPO 从带 KL 约束的最优策略形式出发，把隐式 reward 写成 Policy 相对 Reference 的 log-ratio，再代回偏好概率模型，最终得到一个只需要 Policy、冻结 Reference 和离线偏好 pairs 的二元分类损失。</p><div className="hero-meta"><span>建立于 2026.08.20</span><i></i><span>37 分钟阅读</span><i></i><span>偏好学习 + 推导</span></div><aside className="answer-first"><span>一句话定位</span><p>DPO 保留了 <a className="term-link" href="/training/rlhf">RLHF</a> 的“偏好 + Reference + KL”结构，却省去显式 Reward Model、Critic 和在线 <a className="term-link" href="/training/ppo">PPO</a> rollout。代价是只能从给定的离线 candidates 学习，不能在训练中主动探索评分器下的新回答。</p></aside></section>

<section className="prose-section" id="chapter-1"><div className="prose-heading"><span>01</span><div><p>WHY REMOVE THE RL LOOP</p><h2>大模型偏好对齐为何需要“直接”方法？</h2></div></div><p>经典 <a className="term-link" href="/training/rlhf">RLHF</a> 要先把 comparisons 拟合成 Reward Model，再由在线 Policy 采样回答，用策略优化最大化预测 reward。这个流水线需要多个大模型副本、精细超参数和推理—训练同步；Reward Model 的绝对标度也会影响优化。</p><p>DPO 观察到：在 KL-regularized reward maximization 下，最优策略与 reward 存在闭式关系。于是无需先恢复任意绝对 reward，只需直接学习“chosen 相对 rejected 的隐式 reward margin”。</p><aside className="boundary-box"><b>“直接”指从偏好 pair 到 Policy</b><p>它不是没有目标函数，也不是不需要 Reference；它只是把 Reward Model 与 RL optimizer 的中间层代数消去。</p></aside></section>

<section className="prose-section" id="chapter-2"><div className="prose-heading"><span>02</span><div><p>OFFLINE PREFERENCE PAIRS</p><h2>DPO 的一条训练数据包含什么？</h2></div></div><Formula label="Preference dataset" tex={String.raw`\mathcal D=\{(x,y_w,y_l)\},\qquad y_w\succ y_l\mid x`} /><p><Formula inline tex={String.raw`x`} /> 是同一个 prompt，<Formula inline tex={String.raw`y_w`} /> 是 chosen，<Formula inline tex={String.raw`y_l`} /> 是 rejected。两条 response 可以来自不同模型、同一模型不同采样、人类改写或筛选系统；核心是比较必须共享 prompt。</p><div className="reason-list compact-reasons"><article><span>01</span><div><h3>Pair 必须表达稳定偏好</h3><p>若 chosen 只因格式偶然胜出，模型会学到格式 shortcut。</p></div></article><article><span>02</span><div><h3>Rejected 需要有信息量</h3><p>过于荒谬的负例很快饱和；与 chosen 接近但确有关键差异的 hard negatives 更能定义边界。</p></div></article><article><span>03</span><div><h3>候选分布决定可学范围</h3><p>离线数据从未出现的行为，DPO 不会主动探索出来。</p></div></article></div></section>

<section className="prose-section" id="chapter-3"><div className="prose-heading"><span>03</span><div><p>START FROM KL-REGULARIZED RL</p><h2>DPO 与经典 <a className="term-link" href="/training/rlhf">RLHF</a> 的数学起点是什么？</h2></div></div><Formula label="Per-prompt constrained objective" className="compact-latex" tex={String.raw`\max_{\pi}\;\mathbb E_{y\sim\pi(\cdot\mid x)}[r(x,y)]-\beta D_{\mathrm{KL}}\!\left(\pi(\cdot\mid x)\Vert\pi_{\mathrm{ref}}(\cdot\mid x)\right)`} /><p>对固定 <Formula inline tex={String.raw`x`} /> 求最优分布，可以得到指数倾斜形式：</p><Formula label="Optimal policy under reward and KL" tex={String.raw`\pi_r(y\mid x)=\frac{1}{Z(x)}\,\pi_{\mathrm{ref}}(y\mid x)\exp\!\left(\frac{r(x,y)}{\beta}\right)`} /><p>高 reward response 相对 Reference 被放大，但 <Formula inline tex={String.raw`\beta`} /> 越大，KL 惩罚越强，最优分布整体越保守。</p></section>

<section className="prose-section" id="chapter-4"><div className="prose-heading"><span>04</span><div><p>REPARAMETERIZE THE REWARD</p><h2>怎样把显式 Reward Model 消去？</h2></div></div><p>将上式取对数并整理：</p><Formula label="Policy log-ratio as an implicit reward" tex={String.raw`r(x,y)=\beta\log\frac{\pi_r(y\mid x)}{\pi_{\mathrm{ref}}(y\mid x)}+\beta\log Z(x)`} /><p>对于同一 prompt 的 chosen 与 rejected 做差，归一化常数 <Formula inline tex={String.raw`\log Z(x)`} /> 完全抵消：</p><Formula label="Implicit reward margin" className="compact-latex" tex={String.raw`r(x,y_w)-r(x,y_l)=\beta\!\left[\log\frac{\pi(y_w\mid x)}{\pi_{\mathrm{ref}}(y_w\mid x)}-\log\frac{\pi(y_l\mid x)}{\pi_{\mathrm{ref}}(y_l\mid x)}\right]`} /><p>这一步是 DPO 的关键：偏好学习只需要 reward 差，不必知道绝对 reward 或 partition function。</p></section>

<section className="prose-section" id="chapter-5"><div className="prose-heading"><span>05</span><div><p>THE BINARY CLASSIFICATION LOSS</p><h2>DPO 最终优化的公式是什么？</h2></div></div><p>定义 Policy 与 Reference 在 pair 上的 log-prob margin：</p><Formula label="Chosen–rejected margins" className="compact-latex" tex={String.raw`\Delta_\theta=\log\pi_\theta(y_w\mid x)-\log\pi_\theta(y_l\mid x),\qquad \Delta_{\mathrm{ref}}=\log\pi_{\mathrm{ref}}(y_w\mid x)-\log\pi_{\mathrm{ref}}(y_l\mid x)`} /><Formula label="DPO loss" tex={String.raw`\mathcal L_{\mathrm{DPO}}(\theta)=-\mathbb E_{(x,y_w,y_l)\sim\mathcal D}\log\sigma\!\left(\beta(\Delta_\theta-\Delta_{\mathrm{ref}})\right)`} /><p>目标不是只让 chosen 的 likelihood 上升，而是让 Policy 比 Reference <b>更偏向 chosen 而不是 rejected</b>。Reference margin 提供样本难度和初始偏好的校正。</p></section>

<section className="prose-section" id="chapter-6"><div className="prose-heading"><span>06</span><div><p>WHAT THE GRADIENT DOES</p><h2>一对样本怎样推动模型参数？</h2></div></div><Formula label="Gradient direction, schematic" className="compact-latex" tex={String.raw`-\nabla_\theta\mathcal L\;\propto\;w(x,y_w,y_l)\left[\nabla_\theta\log\pi_\theta(y_w\mid x)-\nabla_\theta\log\pi_\theta(y_l\mid x)\right]`} /><p>权重 <Formula inline tex={String.raw`w`} /> 在模型尚未建立足够 preference margin 时较大；pair 已被高置信区分后逐渐饱和。Chosen token 整体获得正向梯度、Rejected token 整体受负向梯度，因此仍是 response-level 粗监督，并不知道具体哪一句造成偏好。</p><aside className="text-note"><b>Sequence log-prob</b><p><Formula inline tex={String.raw`\log\pi_\theta(y\mid x)=\sum_t\log\pi_\theta(y_t\mid x,y_{<t})`} />。实现必须明确 sum 还是长度归一化；不同选择会影响 length bias，不能把它当作无关细节。</p></aside></section>

<section className="prose-section" id="chapter-7"><div className="prose-heading"><span>07</span><div><p>TWO FORWARD ROLES, ONE TRAINED MODEL</p><h2>DPO 训练架构为什么更简单？</h2></div></div><div className="formula-sequence"><div><span>01 · LOAD PAIR</span><Formula className="sequence-latex" tex={String.raw`(x,y_w,y_l)\sim\mathcal D`} /></div><div><span>02 · POLICY LOGPS</span><Formula className="sequence-latex" tex={String.raw`\log\pi_\theta(y_w\mid x),\;\log\pi_\theta(y_l\mid x)`} /></div><div><span>03 · REFERENCE LOGPS</span><Formula className="sequence-latex" tex={String.raw`\log\pi_{\mathrm{ref}}(y_w\mid x),\;\log\pi_{\mathrm{ref}}(y_l\mid x)`} /></div><div><span>04 · BINARY LOSS</span><Formula className="sequence-latex" tex={String.raw`\theta\leftarrow\theta-\eta\nabla_\theta\mathcal L_{\mathrm{DPO}}`} /></div></div><p>不需要在线生成、Reward Model、Critic 或 advantage estimation。Reference log-probs 还可提前离线缓存；但 Policy 仍需对 chosen/rejected 做 teacher-forced forward，并对 Policy 部分反向传播。</p></section>

<section className="prose-section" id="chapter-8"><div className="prose-heading"><span>08</span><div><p>ALGORITHM BOUNDARIES</p><h2>DPO 与 RLHF、Reasoning RL 的关系是什么？</h2></div></div><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>方法</th><th>数据是否在线变化</th><th>评分/优化</th></tr></thead><tbody><tr><td><a className="term-link" href="/training/rlhf">RLHF</a> + <a className="term-link" href="/training/ppo">PPO</a></td><td>Policy 持续生成新回答</td><td>显式 RM + Actor–Critic</td></tr><tr className="highlight-row"><td>DPO</td><td>固定 preference pairs</td><td>隐式 reward + 分类损失</td></tr><tr><td><a className="term-link" href="/training/reasoning-rl">Reasoning RL</a> + <a className="term-link" href="/training/grpo">GRPO</a></td><td>每轮采样同题多条轨迹</td><td>Verifier + group advantage</td></tr></tbody></table></div><p>DPO 很适合把已收集的偏好数据高效写入 Policy；但推理强化的价值常来自“当前模型在线探索多种解法，再由 Verifier 发现新成功轨迹”。固定 pairs 无法完整替代这种探索循环。</p></section>

<section className="prose-section" id="chapter-9"><div className="prose-heading"><span>09</span><div><p>FAILURES AND VARIANTS</p><h2>DPO 有什么问题，后来怎样改进？</h2></div></div><div className="reason-list compact-reasons"><article><span>01</span><div><h3>Offline support limitation</h3><p>只能重加权数据中已有 responses，无法向评分器查询新的策略输出。</p></div></article><article><span>02</span><div><h3>Preference noise</h3><p>chosen/rejected 标签错误、强度不同或多人偏好冲突都会被压成同一种二元目标。</p></div></article><article><span>03</span><div><h3>Length 与 style shortcuts</h3><p>若数据中 chosen 总更长、更礼貌，模型可能利用表面相关性。</p></div></article><article><span>04</span><div><h3>Distribution mismatch</h3><p>旧模型候选训练出来的 Policy 可能进入新分布，原 pairs 不再覆盖当前错误。</p></div></article></div><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>变体</th><th>主要动机</th></tr></thead><tbody><tr><td>IPO</td><td>从更一般的 preference optimization 分析出发，缓解可分数据上过拟合</td></tr><tr><td><a className="term-link" href="/training/kto">KTO</a></td><td>只需单条 desirable/undesirable 反馈，不强制成对</td></tr><tr><td>ORPO</td><td>把 SFT 与 odds-ratio preference objective 合在一个阶段</td></tr><tr><td>SimPO</td><td>去掉 Reference，并引入长度归一化与目标 margin</td></tr><tr><td>Online DPO / iterative DPO</td><td>周期性用当前 Policy 采样新 pairs，缩小离线分布漂移</td></tr></tbody></table></div></section>

<section className="prose-section rms-qa" id="qa"><div className="prose-heading"><span>10</span><div><p>QUESTIONS AS CONNECTIONS</p><h2>关联 QA</h2></div></div><div className="qa-list"><details id="qa-1" open><summary><span>Q1</span>DPO 是强化学习吗？</summary><div><p>它由 KL-regularized <a className="term-link" href="/training/rlhf">RLHF</a> 目标推导而来，但实际训练是离线监督式二元分类，不进行在线环境交互、rollout 或显式 Policy Gradient loop。称“直接偏好优化”更不易混淆。</p></div></details><details id="qa-2"><summary><span>Q2</span>为什么还需要 Reference Model？</summary><div><p>Reference 定义每个 response 原本有多可能，使目标学习相对偏好变化，并对应 KL 正则。没有它就变成另一类目标，不能直接沿用同一推导。</p></div></details><details id="qa-3"><summary><span>Q3</span>Chosen 必须是完全正确答案吗？</summary><div><p>不一定，它只需在标注准则下优于 Rejected。但若 chosen 仍有严重错误，训练只能学到“相对更好”，不会自动获得绝对正确性。</p></div></details><details id="qa-4"><summary><span>Q4</span>DPO 是否训练 Reward Model？</summary><div><p>不单独训练可部署的 Reward Model。Policy 相对 Reference 的 log-ratio 在数学上扮演隐式 reward，因此 reward 信息直接写进 Policy。</p></div></details><details id="qa-5"><summary><span>Q5</span><Formula inline tex={String.raw`\beta`} /> 越大是不是学得越激进？</summary><div><p>不能这样简单解释。在原 KL 目标里更大的 <Formula inline tex={String.raw`\beta`} /> 表示更强的 KL 惩罚；在 DPO loss 中它也缩放分类 logit，和数据、学习率、训练阶段共同影响梯度。它不是“激进程度旋钮”或学习率的同义词。</p></div></details><details id="qa-6"><summary><span>Q6</span>DPO 为什么不需要 Rollout？</summary><div><p>Chosen 与 Rejected 已经在离线数据中，训练只重算它们在 Policy 和 Reference 下的 log-probs，不必由当前 Policy 再生成 response。</p></div></details><details id="qa-7"><summary><span>Q7</span>DPO 能直接替代 <a className="term-link" href="/training/reasoning-rl">Reasoning RL</a> 吗？</summary><div><p>不能普遍替代。若已固定采集成功/失败推理 pairs，可以做直接偏好训练；若目标是让当前模型持续探索新解法并接受 Verifier 在线反馈，<a className="term-link" href="/training/grpo">GRPO</a> 等在线方法更贴合。</p></div></details><details id="qa-8"><summary><span>Q8</span>DPO 最容易遇到什么数据问题？</summary><div><p>标签噪声、过于容易的 negatives、chosen/rejected 来源差异和长度偏差。高质量 pair 构造通常比公式本身更决定最终效果。</p></div></details></div></section>
<section className="sources-section rms-sources"><div><p className="mini-label">PRIMARY SOURCES</p><h2>推导与偏好优化变体</h2></div><ol><li><a href="https://arxiv.org/html/2305.18290" target="_blank" rel="noreferrer">Direct Preference Optimization</a><span>2023</span></li><li><a href="https://arxiv.org/abs/2310.12036" target="_blank" rel="noreferrer">A General Theoretical Paradigm to Understand Learning from Human Preferences</a><span>IPO</span></li><li><a href="https://arxiv.org/abs/2402.01306" target="_blank" rel="noreferrer">Model Alignment as Prospect Theoretic Optimization</a><span>2024</span></li><li><a href="https://arxiv.org/abs/2405.14734" target="_blank" rel="noreferrer">SimPO: Simple Preference Optimization</a><span>2024</span></li></ol></section>
<footer className="article-footer"><div><span>继续连接知识</span><strong>把离线偏好分类与在线策略探索放回同一张后训练地图。</strong></div><div className="footer-links"><a href="/training/rlhf">RLHF ↗</a><a href="/training/ppo">PPO ↗</a><a href="/training/grpo">GRPO ↗</a></div></footer></main>
<aside className="right-rail" aria-label="本页目录"><p>本页目录</p>{chapters.map(([no,label])=><a href={no==="10"?"#qa":`#chapter-${Number(no)}`} key={no}><span>{no}</span>{label}</a>)}<RightQaIndex questions={qaQuestions}/><div className="reading-note"><span>10 章</span><div><i></i></div><small>公式密度 · 高</small></div></aside>
</div>}
