import type { Metadata } from "next";
import { Formula } from "../../components/Formula";
import { RightQaIndex } from "../../components/RightQaIndex";
import { TrainingSidebar } from "../../components/TrainingSidebar";

const title = "什么是 KTO？";
const description = "从单条 desirable/undesirable 反馈出发，理解 KTO 的前景理论动机、隐式奖励、KL reference point、价值函数、训练架构及其与 DPO、RLHF、Reasoning RL 的边界。";
export const metadata: Metadata = { title, description, openGraph: { title, description, type: "article", images: [] }, twitter: { card: "summary", title, description, images: [] } };

const chapters = [["01","为什么需要单条反馈"],["02","数据结构"],["03","前景理论视角"],["04","隐式 Reward"],["05","KL Reference Point"],["06","价值函数与损失"],["07","完整训练架构"],["08","与相邻算法的边界"],["09","问题与使用选择"],["10","关联 QA"]];
const qaQuestions = ["KTO 的名字是什么意思？","为什么它不需要成对偏好？","Desirable 是否等于完美答案？","没有成对比较，标签从哪里来？","Reference point 为什么使用 KL？","为什么不对 reference point 反向传播？","β、λD 与 λU 分别控制什么？","类别严重不平衡时怎么办？","它是否属于强化学习？","它能替代推理强化吗？"];

export default function KTOPage() {
  return <div className="site-shell">
    <header className="topbar"><a className="brand" href="/" aria-label="模见首页"><span className="brand-mark">模</span><span>模见 <small>Model Atlas</small></span></a><nav className="topnav" aria-label="主导航"><a className="active" href="/">知识库</a><a href="#chapter-1">训练导读</a><a href="#qa">QA 索引</a></nav><div className="top-actions"><a className="search-hint" href="#qa">⌘ K&nbsp;&nbsp;QA 速查</a><span className="edition">2026.08</span></div></header>
    <TrainingSidebar selected="kto" />
    <main className="article rms-article">
      <section className="hero rms-hero" id="top"><div className="breadcrumbs"><a href="/">知识库</a><span>/</span>训练与对齐<span>/</span>KTO</div><div className="question-label"><span>PREFERENCE OPTIMIZATION · 007</span></div><p className="original-question">“现实反馈常只是点赞、点踩、接受、拒绝，未必能为同一 Prompt 同时准备 chosen 与 rejected。只有一条回答的好坏标签，还能做大模型偏好对齐吗？”</p><div className="eyebrow"><span></span>KAHNEMAN–TVERSKY OPTIMIZATION</div><h1>什么是 KTO？</h1><p className="dek">KTO 是一种离线直接偏好优化方法：每条数据只需标记 response 是 desirable 还是 undesirable；它用 Policy 相对 Reference 的 log-ratio 定义隐式 reward，再判断该 reward 相对 KL reference point 是 gain 还是 loss，从而提高好回答、压低坏回答的相对概率。</p><div className="hero-meta"><span>建立于 2026.08.20</span><i></i><span>40 分钟阅读</span><i></i><span>二元反馈 + 公式推导</span></div><aside className="answer-first"><span>一句话定位</span><p><a className="term-link" href="/training/dpo">DPO</a> 学习“同一 Prompt 下 A 比 B 好”；KTO 学习“这条 <Formula inline tex={String.raw`(x,y)`} /> 是好还是坏”。它不训练显式 Reward Model，不运行在线 <a className="term-link" href="/training/ppo">PPO</a>，但仍借助冻结 Reference 和 KL-derived reference point 控制 Policy 的相对变化。</p></aside></section>

      <section className="prose-section" id="chapter-1"><div className="prose-heading"><span>01</span><div><p>WHY UNPAIRED FEEDBACK</p><h2>为什么大模型对齐需要不成对的二元反馈？</h2></div></div><p>偏好 pair <Formula inline tex={String.raw`(x,y_w,y_l)`} /> 信息丰富，但收集成本高：必须为同一 Prompt 准备至少两个候选，并让标注者比较。真实产品却天然积累大量单条信号，例如用户接受或重写回答、点赞或点踩、内容通过或触发安全审核。</p><Formula label="Paired preference versus binary feedback" className="compact-latex" tex={String.raw`\mathcal D_{\mathrm{pair}}=\{(x,y_w,y_l)\},\qquad \mathcal D_{\mathrm{binary}}=\{(x,y,s)\},\quad s\in\{+1,-1\}`} /><p>KTO 的起因不是证明二元标签比 pair 含有更多信息，而是为一种更便宜、更常见、容易持续收集的数据形式设计合适的 inductive bias。弱一些的单条信号可以靠更大规模的数据补偿。</p><aside className="boundary-box"><b>它不是普通的“好回答 SFT + 坏回答反向 SFT”</b><p>普通二分类只预测标签；KTO 直接改变语言模型对整个 response 的条件概率，并使用 Reference Model 与 reference point 判断相对 gain/loss。</p></aside></section>

      <section className="prose-section" id="chapter-2"><div className="prose-heading"><span>02</span><div><p>ONE RESPONSE, ONE LABEL</p><h2>KTO 的一条训练数据长什么样？</h2></div></div><Formula label="Binary-feedback record" tex={String.raw`z=(x,y,s),\qquad s=\begin{cases}+1,&y\text{ is desirable for }x,\\-1,&y\text{ is undesirable for }x.\end{cases}`} /><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>字段</th><th>内容</th><th>常见来源</th></tr></thead><tbody><tr><td><Formula inline tex={String.raw`x`} /></td><td>Prompt / instruction</td><td>真实请求或训练问题</td></tr><tr><td><Formula inline tex={String.raw`y`} /></td><td>完整 response</td><td>模型采样、人类回答或历史输出</td></tr><tr><td><Formula inline tex={String.raw`s`} /></td><td>好 / 坏二元标签</td><td>点赞点踩、审核、规则、阈值化评分</td></tr></tbody></table></div><p>若已有 <Formula inline tex={String.raw`y_w\succ y_l`} /> pair，可以朴素拆成 <Formula inline tex={String.raw`(x,y_w,+1)`} /> 与 <Formula inline tex={String.raw`(x,y_l,-1)`} />。但这会丢掉“二者为何在同一 Prompt 下构成相对关系”的信息；KTO 真正的优势是可以使用原本就没有配对的数据。</p><aside className="text-note"><b>Desirable 是阈值判断</b><p>它只表示“在当前规范下值得鼓励”，不保证回答完美；undesirable 也不一定一无是处。标签阈值和反馈来源决定模型最终学到什么。</p></aside></section>

      <section className="prose-section" id="chapter-3"><div className="prose-heading"><span>03</span><div><p>PROSPECT THEORY AS AN INDUCTIVE BIAS</p><h2>为什么它叫 Kahneman–Tversky Optimization？</h2></div></div><p>前景理论强调：人对结果的感受不是只看绝对值，而是看它相对某个 reference point 是 gain 还是 loss；对收益与损失的敏感度还可能不对称。KTO 借用这种结构设计语言模型对齐目标：</p><Formula label="Value is measured relative to a reference point" tex={String.raw`\text{subjective value}=v\!\left(\text{outcome}-\text{reference point}\right)`} /><div className="compare-columns"><article><span>DESIRABLE</span><h3>希望成为相对 Gain</h3><p>Policy 应当比 Reference 更愿意生成这条回答，而且提升幅度应超过总体策略漂移基线。</p></article><article className="accent-card"><span>UNDESIRABLE</span><h3>希望成为相对 Loss</h3><p>Policy 应当比 Reference 更不愿意生成这条回答，使它的隐式 reward 低于基线。</p></article></div><p>论文使用 logistic sigmoid 代替经典前景理论中的幂函数，以获得更稳定的训练。这里的“human-aware”是对目标结构的类比，不表示一个简单损失函数已经准确模拟了每个人对文本质量的心理过程。</p></section>

      <section className="prose-section" id="chapter-4"><div className="prose-heading"><span>04</span><div><p>POLICY LOG-RATIO AS REWARD</p><h2>没有 Reward Model，KTO 的 Reward 从哪里来？</h2></div></div><p>设可训练 Policy 为 <Formula inline tex={String.raw`\pi_\theta`} />，冻结的参考模型为 <Formula inline tex={String.raw`\pi_{\mathrm{ref}}`} />。KTO 把完整 response 在两模型下的 log-prob 差定义成隐式 reward：</p><Formula label="Implicit reward" tex={String.raw`r_\theta(x,y)=\log\frac{\pi_\theta(y\mid x)}{\pi_{\mathrm{ref}}(y\mid x)}`} /><Formula label="Autoregressive decomposition" tex={String.raw`r_\theta(x,y)=\sum_{t=1}^{|y|}\left[\log\pi_\theta(y_t\mid x,y_{<t})-\log\pi_{\mathrm{ref}}(y_t\mid x,y_{<t})\right]`} /><p>若 <Formula inline tex={String.raw`r_\theta>0`} />，说明新 Policy 相比 Reference 提高了这条 response 的概率；若小于 <Formula inline tex={String.raw`0`} />，则说明它被压低。这个 reward 不由单独网络预测，而是直接由 Policy 的概率变化产生。</p><aside className="boundary-box"><b>Reward 不是 response 的绝对质量分</b><p>它衡量“相对 Reference 的概率变化”。一个本身很差的回答如果原本概率更低，也可能出现正 log-ratio；因此还必须结合 desirable/undesirable 标签和 reference point 判断方向。</p></aside></section>

      <section className="prose-section" id="chapter-5"><div className="prose-heading"><span>05</span><div><p>THE KL REFERENCE POINT</p><h2>为什么不能直接用零作为好坏分界线？</h2></div></div><p>Policy 更新时，许多 response 的概率会共同变化。KTO 不只问某条回答相对 Reference 是否上升，而是问它的隐式 reward 是否超过“模型总体离开 Reference 的典型程度”。理论 reference point 写作：</p><Formula label="Reference point" tex={String.raw`z_0= D_{\mathrm{KL}}\!\left(\pi_\theta(\cdot\mid x)\Vert\pi_{\mathrm{ref}}(\cdot\mid x)\right)=\mathbb E_{y'\sim\pi_\theta}\!\left[\log\frac{\pi_\theta(y'\mid x)}{\pi_{\mathrm{ref}}(y'\mid x)}\right]`} /><Formula label="Gain or loss margin" tex={String.raw`m_\theta(x,y)=r_\theta(x,y)-z_0`} /><p>对 desirable response，希望 <Formula inline tex={String.raw`m_\theta>0`} />；对 undesirable response，希望 <Formula inline tex={String.raw`m_\theta<0`} />。减去 <Formula inline tex={String.raw`z_0`} /> 可以避免 Policy 仅靠整体粗暴漂移就让所有目标的 log-ratio 一起上升。</p><p>精确计算 KL 需要从当前 Policy 采样，代价很高。论文实现用同一 microbatch 中错配的 <Formula inline tex={String.raw`(x_i,y_j)`} /> 估计一个共享 reference point，并截断到非负：</p><Formula label="Practical biased estimate" className="compact-latex" tex={String.raw`\widehat z_0=\max\!\left(0,\frac{1}{m}\sum_{i=1}^{m}\log\frac{\pi_\theta(y_{j(i)}\mid x_i)}{\pi_{\mathrm{ref}}(y_{j(i)}\mid x_i)}\right),\qquad j(i)=(i+1)\bmod m`} /><aside className="text-note"><b>为什么错配 Prompt 与 Response？</b><p>真实 <Formula inline tex={String.raw`y_i`} /> 常被特意选成典型好例或坏例，reward 幅度不代表普通 Policy 输出；循环错配试图构造较中性的批内基线。它是方便但有偏的 estimator，不是真实 KL 的精确计算。</p></aside></section>

      <section className="prose-section" id="chapter-6"><div className="prose-heading"><span>06</span><div><p>VALUE AND LOSS</p><h2>KTO 的价值函数与最终损失是什么？</h2></div></div><p>记 desirable 与 undesirable 的权重为 <Formula inline tex={String.raw`\lambda_D,\lambda_U`} />，风险敏感度为 <Formula inline tex={String.raw`\beta>0`} />。两类样本使用方向相反的 sigmoid value：</p><Formula label="KTO value" className="compact-latex" tex={String.raw`v_\theta(x,y)=\begin{cases}\lambda_D\,\sigma\!\left(\beta[r_\theta(x,y)-z_0]\right),&y\text{ is desirable},\\[4pt]\lambda_U\,\sigma\!\left(\beta[z_0-r_\theta(x,y)]\right),&y\text{ is undesirable}.\end{cases}`} /><Formula label="KTO loss" tex={String.raw`\mathcal L_{\mathrm{KTO}}(\theta)=\mathbb E_{(x,y)\sim\mathcal D}\left[\lambda_y-v_\theta(x,y)\right]`} /><p><Formula inline tex={String.raw`\lambda_y`} /> 对每条记录是常数；最小化 loss 等价于最大化相应 value。对好例，梯度提高 <Formula inline tex={String.raw`r_\theta-z_0`} />；对坏例，梯度降低它。论文实现把 <Formula inline tex={String.raw`z_0`} /> 视作 stop-gradient baseline，不通过它反传，以提升稳定性。</p><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>参数</th><th>控制什么</th><th>过大时的风险</th></tr></thead><tbody><tr><td><Formula inline tex={String.raw`\beta`} /></td><td>sigmoid 饱和速度、风险敏感度</td><td>样本过快进入饱和区，难例被忽略</td></tr><tr><td><Formula inline tex={String.raw`\lambda_D`} /></td><td>desirable 样本总权重</td><td>可能过度追求 gain</td></tr><tr><td><Formula inline tex={String.raw`\lambda_U`} /></td><td>undesirable 样本总权重</td><td>可能过度保守或拒答</td></tr></tbody></table></div></section>

      <section className="prose-section" id="chapter-7"><div className="prose-heading"><span>07</span><div><p>AN OFFLINE TRAINING LOOP</p><h2>一次 KTO 训练迭代具体发生什么？</h2></div></div><div className="formula-sequence"><div><span>01 · LOAD BINARY DATA</span><Formula className="sequence-latex" tex={String.raw`(x_i,y_i,s_i)_{i=1}^{m}\sim\mathcal D`} /></div><div><span>02 · POLICY LOGPS</span><Formula className="sequence-latex" tex={String.raw`\log\pi_\theta(y_i\mid x_i)`} /></div><div><span>03 · REFERENCE LOGPS</span><Formula className="sequence-latex" tex={String.raw`\log\pi_{\mathrm{ref}}(y_i\mid x_i)`} /></div><div><span>04 · ESTIMATE BASELINE</span><Formula className="sequence-latex" tex={String.raw`\widehat z_0\leftarrow\operatorname{stopgrad}(\operatorname{BatchKLEstimate})`} /></div><div><span>05 · COMPUTE VALUES</span><Formula className="sequence-latex" tex={String.raw`v_i\leftarrow v(r_i-\widehat z_0,s_i)`} /></div><div><span>06 · UPDATE POLICY</span><Formula className="sequence-latex" tex={String.raw`\theta\leftarrow\theta-\eta\nabla_\theta\mathcal L_{\mathrm{KTO}}`} /></div></div><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>组件</th><th>是否训练</th><th>是否需要</th></tr></thead><tbody><tr><td>Policy</td><td>是</td><td>产生 log-prob 并接收梯度</td></tr><tr><td>Reference Policy</td><td>否</td><td>标准形式需要；可缓存部分 log-probs</td></tr><tr><td>Reward Model</td><td>—</td><td>不需要</td></tr><tr><td>Critic / Value Model</td><td>—</td><td>不需要</td></tr><tr><td>Online Rollout Engine</td><td>—</td><td>训练阶段不需要</td></tr></tbody></table></div><p>它在计算形态上更接近离线 supervised fine-tuning：数据固定，使用 teacher forcing 计算 response log-probs。但损失不是 next-token NLL，而是根据二元反馈和 reference-relative utility 调整整条 response 的概率。</p></section>

      <section className="prose-section" id="chapter-8"><div className="prose-heading"><span>08</span><div><p>CONCEPT BOUNDARIES</p><h2>KTO 与 DPO、RLHF、Reasoning RL 有什么关系？</h2></div></div><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>方法</th><th>最小数据单元</th><th>训练机制</th><th>是否在线探索</th></tr></thead><tbody><tr><td><a className="term-link" href="/training/rlhf">RLHF</a> + <a className="term-link" href="/training/ppo">PPO</a></td><td>偏好 pairs + 在线 responses</td><td>显式 RM + Actor–Critic</td><td>是</td></tr><tr><td><a className="term-link" href="/training/dpo">DPO</a></td><td><Formula inline tex={String.raw`(x,y_w,y_l)`} /></td><td>pairwise log-ratio margin</td><td>否</td></tr><tr className="highlight-row"><td>KTO</td><td><Formula inline tex={String.raw`(x,y,s)`} /></td><td>pointwise utility relative to KL baseline</td><td>否</td></tr><tr><td><a className="term-link" href="/training/reasoning-rl">Reasoning RL</a> + <a className="term-link" href="/training/grpo">GRPO</a></td><td>Query + 在线 group rollouts</td><td>Verifier reward + group advantage</td><td>是</td></tr></tbody></table></div><p>KTO 与 DPO 都是不训练显式 Reward Model 的直接偏好优化；差别不只是“一条还是两条 response”，而是目标的比较基准不同：DPO 直接比较 chosen/rejected margin，KTO 把每条输出分别与一个策略级 reference point 比较。</p><p>对可验证推理，可以把正确/错误轨迹转成 desirable/undesirable 数据后做 KTO；但固定离线标签不会让当前 Policy 持续探索新解法，因此不能完整替代在线 Reasoning RL。</p></section>

      <section className="prose-section" id="chapter-9"><div className="prose-heading"><span>09</span><div><p>FAILURE MODES AND CHOICE</p><h2>KTO 有哪些问题，什么时候更适合使用？</h2></div></div><div className="reason-list compact-reasons"><article><span>01</span><div><h3>Reference-point estimator 有偏</h3><p>批内错配与非负截断换来低成本和较低方差，但 <Formula inline tex={String.raw`\widehat z_0`} /> 不是真实 KL；batch 组成会直接影响训练信号。</p></div></article><article><span>02</span><div><h3>Sigmoid saturation 可能忽略难例</h3><p>margin 绝对值很大时梯度趋近于零，既可能自动降低错标噪声影响，也可能漏掉困难但必要的样本。</p></div></article><article><span>03</span><div><h3>类别比例改变目标</h3><p>大量点踩、很少点赞时，若不重设 <Formula inline tex={String.raw`\lambda_D,\lambda_U`} />，模型可能主要学会压低坏回答，而没有足够信号建立好行为。</p></div></article><article><span>04</span><div><h3>二元标签压缩偏好强度</h3><p>“勉强可接受”和“非常优秀”都可能是 desirable；阈值化会丢失评分幅度和多维偏好冲突。</p></div></article><article><span>05</span><div><h3>离线分布限制</h3><p>Policy 只能重加权已有 responses，不能主动向 Verifier 或用户查询新行为；模型变化后旧反馈也可能失去代表性。</p></div></article><article><span>06</span><div><h3>心理学类比不是普适真理</h3><p>文本质量并非金钱赌博，不同人群和任务的 gain/loss 感知未必符合一个固定 sigmoid utility。</p></div></article></div><div className="compare-columns"><article className="accent-card"><span>更适合 KTO</span><h3>天然拥有单条二元反馈</h3><p>点赞/点踩数量大、难以构造成 pairs，或 desirable/undesirable 比例显著不平衡；可以通过 class weights 表达业务中“鼓励好行为”和“阻止坏行为”的不同代价。</p></article><article><span>更适合 DPO</span><h3>高质量 Pair 本身很有价值</h3><p>同一 Prompt 的比较可靠、噪声和矛盾较少，chosen/rejected 的相对差异正是想保留的监督信息。</p></article></div><aside className="text-note"><b>论文经验不是通用保证</b><p>原论文报告的竞争力来自其具体模型、数据和评测。实际选择仍应在同一 Base/SFT checkpoint、同一数据预算与独立评测上比较，并监控 helpfulness、安全性、长度和拒答率。</p></aside></section>

      <section className="prose-section rms-qa" id="qa"><div className="prose-heading"><span>10</span><div><p>QUESTIONS AS CONNECTIONS</p><h2>关联 QA</h2></div></div><div className="qa-list">
        <details id="qa-1" open><summary><span>Q1</span>KTO 的名字是什么意思？</summary><div><p>全称是 Kahneman–Tversky Optimization，名字来自 Kahneman 与 Tversky 的前景理论。它借用“相对于 reference point 判断 gain/loss，并允许收益和损失不对称”的结构来设计对齐损失。</p></div></details>
        <details id="qa-2"><summary><span>Q2</span>为什么它不需要成对偏好？</summary><div><p>每条 response 不是与另一个 response 直接比较，而是把自身隐式 reward 与策略级 KL reference point 比较；标签只需告诉损失应把它推到 reference point 上方还是下方。</p></div></details>
        <details id="qa-3"><summary><span>Q3</span>Desirable 是否等于完美答案？</summary><div><p>不等于。它只是超过当前业务或标注规范的接受阈值。如果 desirable 数据普遍含有事实错误，KTO 仍会提高这些回答的概率。</p></div></details>
        <details id="qa-4"><summary><span>Q4</span>没有成对比较，标签从哪里来？</summary><div><p>可以来自点赞点踩、人工接受/拒绝、安全审核、规则 Verifier、评分阈值或历史编辑行为。关键是明确反馈代表什么，并审计不同来源的噪声和选择偏差。</p></div></details>
        <details id="qa-5"><summary><span>Q5</span>Reference point 为什么使用 KL？</summary><div><p>隐式 reward 是 Policy 相对 Reference 的 log-ratio；对当前 Policy 输出取期望，正好得到 <Formula inline tex={String.raw`D_{\mathrm{KL}}(\pi_\theta\Vert\pi_{\mathrm{ref}})`} />。它表示策略整体漂移的平均水平，使单条回答按“超出还是低于总体漂移”判断 gain/loss。</p></div></details>
        <details id="qa-6"><summary><span>Q6</span>为什么不对 reference point 反向传播？</summary><div><p>它在损失中承担 baseline 和饱和位置的作用。把 <Formula inline tex={String.raw`z_0`} /> stop-gradient，可以避免每条样本同时通过基线间接牵动整批数据，减少训练耦合；这是标准实现的稳定性选择，而不是数学上唯一可能的设计。</p></div></details>
        <details id="qa-7"><summary><span>Q7</span><Formula inline tex={String.raw`\beta`} />、<Formula inline tex={String.raw`\lambda_D`} /> 与 <Formula inline tex={String.raw`\lambda_U`} /> 分别控制什么？</summary><div><p><Formula inline tex={String.raw`\beta`} /> 控制 sigmoid 对 margin 的敏感度和饱和速度；<Formula inline tex={String.raw`\lambda_D`} />、<Formula inline tex={String.raw`\lambda_U`} /> 分别控制 desirable 与 undesirable 的总权重，用来表达 gain/loss 不对称和校正类别比例。</p></div></details>
        <details id="qa-8"><summary><span>Q8</span>类别严重不平衡时怎么办？</summary><div><p>不能只看样本条数。应按业务代价和类别数量共同设置 <Formula inline tex={String.raw`\lambda_D,\lambda_U`} />，并分别监控两类 loss、梯度和评测。原论文给出经验区间，但不是跨任务的固定定律。</p></div></details>
        <details id="qa-9"><summary><span>Q9</span>KTO 是否属于强化学习？</summary><div><p>它受 RLHF 的隐式 reward 与 KL-regularized policy 观点启发，但实际训练使用固定离线数据和可微闭式损失，没有在线 rollout、Critic、advantage estimation 或环境交互。称为直接偏好优化更准确。</p></div></details>
        <details id="qa-10"><summary><span>Q10</span>KTO 能替代 <a className="term-link" href="/training/reasoning-rl">Reasoning RL</a> 吗？</summary><div><p>不能普遍替代。它可以学习已经标注好的正确/错误推理轨迹，却不会让当前 Policy 在线采样多种新解法并由 Verifier 立即反馈；后者正是 Reasoning RL 的重要能力来源。</p></div></details>
      </div></section>

      <section className="sources-section rms-sources"><div><p className="mini-label">PRIMARY SOURCES</p><h2>算法、理论背景与相邻目标</h2></div><ol><li><a href="https://arxiv.org/html/2402.01306" target="_blank" rel="noreferrer">KTO: Model Alignment as Prospect Theoretic Optimization</a><span>2024</span></li><li><a href="https://arxiv.org/html/2305.18290" target="_blank" rel="noreferrer">Direct Preference Optimization</a><span>2023</span></li><li><a href="https://arxiv.org/html/2203.02155" target="_blank" rel="noreferrer">InstructGPT · Human-feedback alignment</a><span>2022</span></li><li><a href="https://www.jstor.org/stable/1914185" target="_blank" rel="noreferrer">Prospect Theory: An Analysis of Decision under Risk</a><span>1979</span></li></ol></section>
      <footer className="article-footer"><div><span>继续连接知识</span><strong>把单条二元反馈放回偏好对齐地图，继续比较 pairwise、pointwise 与 online verifier-based learning。</strong></div><div className="footer-links"><a href="/training/dpo">DPO ↗</a><a href="/training/rlhf">RLHF ↗</a><a href="/training/reasoning-rl">Reasoning RL ↗</a></div></footer>
    </main>
    <aside className="right-rail" aria-label="本页目录"><p>本页目录</p>{chapters.map(([no,label])=><a href={no==="10"?"#qa":`#chapter-${Number(no)}`} key={no}><span>{no}</span>{label}</a>)}<RightQaIndex questions={qaQuestions}/><div className="reading-note"><span>10 章</span><div><i></i></div><small>公式密度 · 高</small></div></aside>
  </div>;
}
