import type { Metadata } from "next";
import { Formula } from "../../components/Formula";
import { RightQaIndex } from "../../components/RightQaIndex";
import { TrainingSidebar } from "../../components/TrainingSidebar";

const title="什么是 GRPO？";
const description="面向大模型 Reasoning RL，深入拆解 GRPO 的组采样、Verifier reward、组内 baseline、clipped policy objective、KL、问题与 DAPO、Dr.GRPO、GSPO 等改进。";
export const metadata:Metadata={title,description,openGraph:{title,description,type:"article",images:[]},twitter:{card:"summary",title,description,images:[]}};
const chapters=[["01","为什么移除 Critic"],["02","组采样架构"],["03","Verifier Rewards"],["04","组相对 Advantage"],["05","Clipped objective 与 KL"],["06","一轮训练"],["07","Credit 与粒度"],["08","主要问题"],["08.1","组内零方差为何无信号"],["09","改进路线"],["10","关联 QA"]];
const qaQuestions=["它与 Actor–Critic 方法的核心差别是什么？","为什么同一道题要生成一组回答？","组内平均分是 Value Function 吗？","一组全对或全错怎么办？","同一个 Advantage 会给所有 token 吗？","是否一定需要规则 Reward？","为什么可能偏向长回答？","在线组优化与离线偏好优化能互相替代吗？","训练完部署时还要多采样吗？"];
export default function GRPOPage(){return <div className="site-shell">
<header className="topbar"><a className="brand" href="/" aria-label="模见首页"><span className="brand-mark">模</span><span>模见 <small>Model Atlas</small></span></a><nav className="topnav"><a className="active" href="/">知识库</a><a href="#chapter-1">训练导读</a><a href="#qa">QA 索引</a></nav><div className="top-actions"><a className="search-hint" href="#qa">⌘ K&nbsp;&nbsp;QA 速查</a><span className="edition">2026.08</span></div></header><TrainingSidebar selected="grpo"/>
<main className="article rms-article"><section className="hero rms-hero" id="top"><div className="breadcrumbs"><a href="/">知识库</a><span>/</span>训练与对齐<span>/</span>GRPO</div><div className="question-label"><span>REASONING POLICY OPTIMIZATION · 006</span></div><p className="original-question">“长 CoT 的最终答案 reward 很稀疏，Critic 又贵又难训练。能否不预测每个前缀的 Value，而用同一道题的多条回答互相比较？”</p><div className="eyebrow"><span></span>GROUP RELATIVE POLICY OPTIMIZATION</div><h1>什么是 GRPO？</h1><p className="dek">GRPO 是一种无 Critic 的在线策略优化方法：针对同一个 prompt 采样一组 responses，用组内 reward 统计量构造相对 advantage，再以 clipped importance ratio 和 KL 正则更新生成这些 responses 的 Policy。</p><div className="hero-meta"><span>建立于 2026.08.20</span><i></i><span>42 分钟阅读</span><i></i><span>Reasoning RL + 公式</span></div><aside className="answer-first"><span>核心交换</span><p>它用“每题多采样 <Formula inline tex={String.raw`G`} /> 条回答”的 rollout 成本，换掉 <a className="term-link" href="/training/ppo">PPO</a> 中与大模型规模相近的 Value/Critic。组内相对分数是采样 baseline，不是一个能给任意前缀预测 Value 的神经网络。</p></aside></section>

<section className="prose-section" id="chapter-1"><div className="prose-heading"><span>01</span><div><p>WHY REMOVE THE VALUE MODEL</p><h2>Reasoning RL 中 Critic 为什么尤其困难？</h2></div></div><p>长推理轨迹可能先走错、再回退、最后修正；从中间前缀预测最终答案是否正确，本身就是一项困难推理任务。用另一个同规模模型做 Critic，不仅增加参数、activation 与 optimizer states，也可能引入严重 value error。</p><p>DeepSeekMath 提出的 GRPO 直接用同一问题多条输出的 reward 分布估计 baseline，避免显式 Value Model。这对 <a className="term-link" href="/training/reasoning-rl">Reasoning RL</a> 尤其自然：数学和代码题可以廉价验证许多候选，而不必为每个 token 前缀构造 value target。</p><aside className="boundary-box"><b>省掉 Critic，不等于省掉采样</b><p>训练仍需在线生成大量长 responses、重算 log-probs 和调用 Verifier。GRPO 节省的是价值模型相关显存与计算，不会让 RL 变成普通 SFT。</p></aside></section>

<section className="prose-section" id="chapter-2"><div className="prose-heading"><span>02</span><div><p>ONE PROMPT, A GROUP OF TRAJECTORIES</p><h2>GRPO 的训练架构如何组织数据？</h2></div></div><Formula label="Group rollout" tex={String.raw`o_1,o_2,\ldots,o_G\overset{\mathrm{i.i.d.}}{\sim}\pi_{\mathrm{old}}(\cdot\mid x)`} /><div className="formula-sequence"><div><span>QUERY</span><Formula className="sequence-latex" tex={String.raw`x\sim\mathcal D_{\mathrm{query}}`} /></div><div><span>G ROLLOUTS</span><Formula className="sequence-latex" tex={String.raw`\{o_i,\log\pi_{\mathrm{old}}(o_i\mid x)\}_{i=1}^{G}`} /></div><div><span>VERIFY</span><Formula className="sequence-latex" tex={String.raw`r_i=R(x,o_i)`} /></div><div><span>UPDATE</span><Formula className="sequence-latex" tex={String.raw`\theta\leftarrow\operatorname{GroupPolicyUpdate}(x,o_{1:G},r_{1:G})`} /></div></div><p>“Group” 必须围绕同一个 prompt，才有可比性。把不同难度题目的 reward 混在一起做平均，会让题目难度与回答质量混淆。</p></section>

<section className="prose-section" id="chapter-3"><div className="prose-heading"><span>03</span><div><p>REWARDS DEFINE THE BEHAVIOR</p><h2>Verifier Reward 通常怎样构成？</h2></div></div><Formula label="A typical reasoning reward" tex={String.raw`r_i=\lambda_{\mathrm{acc}}r_i^{\mathrm{acc}}+\lambda_{\mathrm{fmt}}r_i^{\mathrm{fmt}}+\lambda_{\mathrm{proc}}r_i^{\mathrm{proc}}-\lambda_{\mathrm{invalid}}r_i^{\mathrm{invalid}}`} /><div className="reason-list compact-reasons"><article><span>01</span><div><h3>Outcome accuracy</h3><p>数学等价判断、选择题答案、代码 tests 等终局信号。</p></div></article><article><span>02</span><div><h3>Format / validity</h3><p>检查答案可解析、正常结束、没有超长截断或执行异常。</p></div></article><article><span>03</span><div><h3>Process signal</h3><p>若有 step verifier 或 Process Reward Model，可对中间步骤提供更细反馈。</p></div></article></div><p>GRPO 本身不要求 reward 必须是规则或二元值；learned RM 也可以使用。但推理任务偏好可验证 reward，是因为它更客观、可扩展，也较少依赖神经评分器在分布外的主观判断。</p></section>

<section className="prose-section" id="chapter-4"><div className="prose-heading"><span>04</span><div><p>GROUP-RELATIVE BASELINE</p><h2>组内 Reward 怎样变成 Advantage？</h2></div></div><Formula label="Group statistics" tex={String.raw`\bar r=\frac{1}{G}\sum_{i=1}^{G}r_i,\qquad s_r=\sqrt{\frac{1}{G}\sum_{i=1}^{G}(r_i-\bar r)^2}`} /><Formula label="Normalized group advantage" tex={String.raw`\widehat A_i=\frac{r_i-\bar r}{s_r+\varepsilon}`} /><p>同题中高于平均的 response 得正 advantage，低于平均的得负 advantage。减均值是 baseline，理论上帮助降低“题目本身难度”带来的方差；除标准差则统一不同组的尺度，但也会改变样本权重和极端组行为。</p><aside className="text-note"><b>二元 reward 示例</b><p>若 8 条回答中 2 条正确，正确回答相对同组明显更好；若 8 条全对或全错，<Formula inline tex={String.raw`s_r=0`} />，组内没有区分信息，这个 query 本轮几乎不给策略梯度。</p></aside></section>

<section className="prose-section" id="chapter-5"><div className="prose-heading"><span>05</span><div><p>CLIP THE POLICY CHANGE</p><h2>GRPO 的策略目标与 <a className="term-link" href="/training/ppo">PPO</a> 有何相同和不同？</h2></div></div><Formula label="Per-token ratio" tex={String.raw`\rho_{i,t}(\theta)=\frac{\pi_\theta(o_{i,t}\mid x,o_{i,<t})}{\pi_{\mathrm{old}}(o_{i,t}\mid x,o_{i,<t})}`} /><Formula label="GRPO objective, common form" className="compact-latex" tex={String.raw`J(\theta)=\frac{1}{G}\sum_{i=1}^{G}\frac{1}{|o_i|}\sum_t\min\!\left(\rho_{i,t}\widehat A_i,\operatorname{clip}(\rho_{i,t},1-\epsilon,1+\epsilon)\widehat A_i\right)-\beta D_{\mathrm{KL}}(\pi_\theta\Vert\pi_{\mathrm{ref}})`} /><p>它保留 <a className="term-link" href="/training/ppo">PPO</a> 式 old-policy ratio 与 clipping，但 advantage 不来自 Critic/GAE，而来自组内 rewards。原始 DeepSeekMath 目标将 KL 作为直接 penalty；不同训练框架对 KL estimator、token aggregation 和 loss normalization 的实现并不完全相同。</p></section>

<section className="prose-section" id="chapter-6"><div className="prose-heading"><span>06</span><div><p>THE ITERATIVE LOOP</p><h2>一轮 GRPO 训练具体发生什么？</h2></div></div><div className="formula-sequence"><div><span>01 · SNAPSHOT</span><Formula className="sequence-latex" tex={String.raw`\pi_{\mathrm{old}}\leftarrow\pi_\theta`} /></div><div><span>02 · GROUP SAMPLE</span><Formula className="sequence-latex" tex={String.raw`o_{b,1:G}\sim\pi_{\mathrm{old}}(\cdot\mid x_b)`} /></div><div><span>03 · REWARD</span><Formula className="sequence-latex" tex={String.raw`r_{b,i}\leftarrow\operatorname{Verifier}(x_b,o_{b,i})`} /></div><div><span>04 · NORMALIZE</span><Formula className="sequence-latex" tex={String.raw`\widehat A_{b,i}\leftarrow\operatorname{GroupNorm}(r_{b,1:G})`} /></div><div><span>05 · OPTIMIZE</span><Formula className="sequence-latex" tex={String.raw`\max_\theta J(\theta)\quad\text{for several minibatches}`} /></div><div><span>06 · REFRESH</span><Formula className="sequence-latex" tex={String.raw`\text{publish }\theta\text{ to rollout workers and repeat}`} /></div></div><p>真正系统难点在 rollout 吞吐、权重同步、Verifier 隔离、token-level old log-prob 一致性和长输出显存。算法公式短，不代表大规模实现简单。</p></section>

<section className="prose-section" id="chapter-7"><div className="prose-heading"><span>07</span><div><p>SEQUENCE REWARD, TOKEN GRADIENT</p><h2>同一个 Advantage 为什么会作用到整条回答？</h2></div></div><p>标准 outcome GRPO 通常把 sequence-level <Formula inline tex={String.raw`\widehat A_i`} /> 广播给 response 的所有生成 token：</p><Formula label="Coarse token credit" tex={String.raw`\widehat A_{i,t}=\widehat A_i,\qquad t=1,\ldots,|o_i|`} /><p>因此正确轨迹中的所有 token 倾向于一起升概率，错误轨迹中的一起降概率。它能学习高分轨迹的整体模式，但不能知道第 37 步才是关键转折，也无法避免“过程错误但最终猜对”被强化。</p><div className="compare-columns"><article><span>OUTCOME REWARD</span><h3>便宜、可扩展、credit 粗</h3><p>只验证最终答案，适合大规模采样，但无法定位中间错误。</p></article><article className="accent-card"><span>PROCESS REWARD</span><h3>信号更细、构造更难</h3><p>给步骤或片段评分，需要可靠 step labels、verifier 或搜索过程。</p></article></div></section>

<section className="prose-section" id="chapter-8"><div className="prose-heading"><span>08</span><div><p>FAILURE MODES</p><h2>GRPO 的主要问题有哪些？</h2></div></div><div className="reason-list compact-reasons"><article><span>01</span><div><h3>Zero-variance groups</h3><p>当同一 Query 的所有最终 Reward 完全相同时，组内相对信号消失。纯二元正确性 Reward 下常表现为全对或全错；但 GRPO 的 Reward 本身并不限于 <Formula inline tex={String.raw`0/1`} />。</p></div></article><article><span>02</span><div><h3>Group normalization bias</h3><p>标准差归一化会放大小方差组，并使每个 query 的权重依赖同组随机样本。</p></div></article><article><span>03</span><div><h3>Length / aggregation bias</h3><p>token 平均与 sequence 平均的选择可奖励长度；截断轨迹也会扭曲 reward 与 loss。</p></div></article><article><span>04</span><div><h3>Coarse credit assignment</h3><p>一个终局 advantage 覆盖所有 token，无法准确强化关键步骤。</p></div></article><article><span>05</span><div><h3>Policy staleness</h3><p>rollout worker 使用旧权重时 ratios 偏离 1，大量 clipping 会降低样本效率。</p></div></article><article><span>06</span><div><h3>Reward hacking and collapse</h3><p>模型可能利用答案抽取或测试漏洞；熵过低后同题 responses 失去多样性。</p></div></article></div></section>

<section className="prose-section" id="chapter-8.1">
  <div className="prose-heading"><span>08.1</span><div><p>WHY ZERO-VARIANCE GROUPS TEACH NOTHING</p><h2>为什么组内所有 Reward 相同时，学习信号会消失？</h2></div></div>
  <aside className="answer-first"><span>先纠正一个容易产生的误解</span><p><b>GRPO 的 Reward 不要求只能取 <Formula inline tex={String.raw`0`} /> 或 <Formula inline tex={String.raw`1`} />。</b>“全对或全错”只是纯二元正确性 Reward 下最常见的零方差例子。真正的一般条件是：同一 Query 的所有最终 Reward 完全相同。</p></aside>

  <h3>GRPO 可以使用哪些 Reward？</h3>
  <p>GRPO 只要求每条 Response 最终得到可比较的标量分数。这个分数可以来自规则、多个指标的加权组合，也可以来自 Learned Reward Model：</p>
  <div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>Reward 形式</th><th>可能的取值</th><th>例子</th></tr></thead><tbody><tr><td>二元 Outcome Reward</td><td><Formula inline tex={String.raw`0,1`} /></td><td>最终答案错误或正确</td></tr><tr><td>分级规则 Reward</td><td>多个离散等级或连续区间</td><td>部分正确、Tests 通过比例、答案接近程度</td></tr><tr><td>复合 Reward</td><td>多个分量的加权和</td><td>正确性 + 格式 + 长度 + 有效性</td></tr><tr><td>Learned Reward Model</td><td>一般为实数分数</td><td>偏好、帮助性或安全性评分</td></tr><tr><td>Process Reward 聚合</td><td>步骤分数累积或聚合</td><td>中间推理步骤质量</td></tr></tbody></table></div>
  <Formula label="GRPO 可以使用复合实值 Reward" className="compact-latex" tex={String.raw`r_i=\lambda_{\mathrm{acc}}r_i^{\mathrm{acc}}+\lambda_{\mathrm{fmt}}r_i^{\mathrm{fmt}}+\lambda_{\mathrm{proc}}r_i^{\mathrm{proc}}-\lambda_{\mathrm{invalid}}r_i^{\mathrm{invalid}}`} />
  <aside className="boundary-box"><b>“全对”不一定等于“所有 Reward 相同”</b><p>如果所有回答最终答案都正确，但它们的格式、过程质量、长度惩罚或 Reward Model 分数不同，组内仍有 Reward 方差，GRPO 仍能产生相对信号。反过来，即使 Reward 不是二元值，只要所有回答都得到同一个分数 <Formula inline tex={String.raw`c`} />，信号仍会消失。</p></aside>

  <h3>第一步：组内标准化减掉了什么？</h3>
  <p>对同一 Query 采样 <Formula inline tex={String.raw`G`} /> 条回答，先计算组内均值与标准差，再把绝对 Reward 转换为相对 Advantage：</p>
  <Formula label="GRPO 的组内相对 Advantage" className="compact-latex" tex={String.raw`\bar r=\frac1G\sum_{i=1}^{G}r_i,\qquad s_r=\sqrt{\frac1G\sum_{i=1}^{G}(r_i-\bar r)^2},\qquad \widehat A_i=\frac{r_i-\bar r}{s_r+\varepsilon}`} />
  <p>其中真正决定第 <Formula inline tex={String.raw`i`} /> 条回答更新方向的是分子 <Formula inline tex={String.raw`r_i-\bar r`} />：高于组内平均值得到正 Advantage，低于平均值得到负 Advantage，等于平均值则得到零。</p>

  <h3>第二步：用纯二元正确性 Reward 举例</h3>
  <div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>组内结果</th><th>Reward 向量</th><th>组均值</th><th>标准差</th><th>每条 Advantage</th></tr></thead><tbody><tr><td>全部正确</td><td><Formula inline tex={String.raw`(1,1,1,1)`} /></td><td><Formula inline tex={String.raw`\bar r=1`} /></td><td><Formula inline tex={String.raw`s_r=0`} /></td><td><Formula inline tex={String.raw`(0,0,0,0)`} /></td></tr><tr><td>全部错误</td><td><Formula inline tex={String.raw`(0,0,0,0)`} /></td><td><Formula inline tex={String.raw`\bar r=0`} /></td><td><Formula inline tex={String.raw`s_r=0`} /></td><td><Formula inline tex={String.raw`(0,0,0,0)`} /></td></tr></tbody></table></div>
  <Formula label="所有 Reward 相等时 Advantage 必为零" className="compact-latex" tex={String.raw`r_1=\cdots=r_G=c\quad\Longrightarrow\quad \bar r=c,\quad r_i-\bar r=0,\quad s_r=0,\quad \widehat A_i=\frac{0}{0+\varepsilon}=0`} />
  <p>上表中的“全对”和“全错”依赖纯二元正确性 Reward。更一般地，<Formula inline tex={String.raw`\varepsilon`} /> 只能防止除零和数值报错，不能创造回答之间原本不存在的差异。因此无论公共 Reward 是 <Formula inline tex={String.raw`1`} />、<Formula inline tex={String.raw`0`} />、<Formula inline tex={String.raw`0.73`} /> 还是其他常数，组内相对信号都为零。</p>

  <h3>第三步：Advantage 为零后，为什么策略梯度也消失？</h3>
  <p>只看某条回答、某个 Token 的 Clipped Policy 项：</p>
  <Formula label="单个 Token 的 GRPO Policy Score" className="compact-latex" tex={String.raw`\ell_{i,t}(\theta)=\min\!\left(\rho_{i,t}(\theta)\widehat A_i,\operatorname{clip}(\rho_{i,t}(\theta),1-\epsilon,1+\epsilon)\widehat A_i\right)`} />
  <p>当 <Formula inline tex={String.raw`\widehat A_i=0`} /> 时，两条候选分数恒为零：</p>
  <Formula label="零 Advantage 使相对策略项及其梯度归零" className="compact-latex" tex={String.raw`\widehat A_i=0\quad\Longrightarrow\quad\ell_{i,t}(\theta)=\min(0,0)=0,\qquad\nabla_\theta\ell_{i,t}(\theta)=0`} />
  <p>这些 Rollouts 没有告诉 Policy“组内哪条生成路径应该更常出现”。生成与 Verifier 计算已经完成，却没有产生组内排序信息，所以称为浪费 Rollout。</p>

  <h3>只要组内 Reward 有差异，信号就会重新出现</h3>
  <p>例如四条回答的二元 Reward 为 <Formula inline tex={String.raw`(1,0,0,0)`} />。此时 <Formula inline tex={String.raw`\bar r=0.25`} />、<Formula inline tex={String.raw`s_r\approx0.433`} />，因此：</p>
  <Formula label="混合正确率产生正负相对 Advantage" tex={String.raw`\widehat A_{\mathrm{correct}}\approx\frac{1-0.25}{0.433}=1.73,\qquad \widehat A_{\mathrm{wrong}}\approx\frac{0-0.25}{0.433}=-0.58`} />
  <p>现在算法得到明确的比较方向：提高正确回答中已采样 Token 的概率，降低错误回答中已采样 Token 的概率。GRPO 真正需要的不是 Reward 必须很高，而是<b>同一 Query 的组内 Reward 必须存在差异</b>。</p>

  <aside className="boundary-box"><b>“组内信号消失”不等于整个 Optimizer 的梯度一定为零</b><p>上述结论针对由 <Formula inline tex={String.raw`\widehat A_i`} /> 驱动的相对 Policy Objective。若总目标还包含相对 Reference Policy 的 KL Penalty、Entropy Bonus 或其他 Auxiliary Loss，这些项仍可能产生梯度；但它们不会凭空告诉模型本组哪条回答更正确。</p></aside>
  <aside className="text-note"><b>为什么太简单和太难的 Query 经常低效？</b><p>在以二元正确性为主的 Reward 中，太简单时 Policy 几乎次次答对，太难时几乎次次答错，因此更容易出现零方差组。若还有格式、过程或连续评分，仍可能保留一定差异。动态采样常优先保留组内 Reward 有方差的 Query，以提高有效组比例，但也要监控由此造成的数据分布变化。</p></aside>
</section>

<section className="prose-section" id="chapter-9"><div className="prose-heading"><span>09</span><div><p>WHAT CAME AFTER GRPO</p><h2>后续方法主要在改哪些环节？</h2></div></div><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>方法</th><th>关键改动</th><th>针对问题</th></tr></thead><tbody><tr><td>RLOO</td><td>用同题其余 samples 的 leave-one-out mean 作 baseline</td><td>无 Critic，同时避免样本把自己计入 baseline</td></tr><tr><td>DAPO</td><td>解耦上下 clip、动态采样、token-level loss、超长 reward shaping</td><td>大规模 RL 的熵、有效组和长度稳定性</td></tr><tr><td>Dr.GRPO</td><td>移除易引入偏差的组标准差与长度归一化</td><td>question/response-level optimization bias</td></tr><tr><td>GSPO</td><td>用 sequence likelihood ratio 做序列级 clipping 与优化</td><td>token ratio 波动，尤其 MoE RL 稳定性</td></tr></tbody></table></div><p>这些改进改变 baseline、normalization、importance ratio 或 aggregation 粒度。它们不能替代可靠数据与 reward；如果 Verifier 错了，再稳定的优化器也只会更有效地优化错误目标。</p><aside className="qwen-connection"><span>CONNECTION · QWEN</span><p>Qwen3 报告使用 GRPO 做 reasoning-stage RL；后续 GSPO 论文则报告序列级 ratio 对 MoE RL 更稳定。具体训练栈应按模型、off-policy 程度和 reward 粒度选择，而不是只看算法名字新旧。</p><a href="/training/reasoning-rl">回到 Reasoning RL 全流程 ↗</a></aside></section>

<section className="prose-section rms-qa" id="qa"><div className="prose-heading"><span>10</span><div><p>QUESTIONS AS CONNECTIONS</p><h2>关联 QA</h2></div></div><div className="qa-list"><details id="qa-1" open><summary><span>Q1</span>GRPO 与 <a className="term-link" href="/training/ppo">PPO</a> 的核心差别是什么？</summary><div><p>二者都可使用 old-policy ratios、clipping 和 KL；<a className="term-link" href="/training/ppo">PPO</a> 通常由 Critic/GAE 给每个前缀估 advantage，GRPO 用同 prompt 的一组 sequence rewards 构造相对 advantage，不训练 Critic。</p></div></details><details id="qa-2"><summary><span>Q2</span>为什么同一道题要生成一组回答？</summary><div><p>既为了探索不同推理路径，也为了建立同题 baseline。只有同一 prompt 下的 rewards 才能把“题难”与“回答相对好坏”部分分开。</p></div></details><details id="qa-3"><summary><span>Q3</span>组内平均分是 Value Function 吗？</summary><div><p>不是。它只是在该 prompt、本次随机组上的 Monte Carlo baseline，不能输入任意中间前缀并预测未来 return，也没有可训练参数。</p></div></details><details id="qa-4"><summary><span>Q4</span>一组全对或全错怎么办？</summary><div><p>纯二元 reward 下 advantage 接近 0。可用动态采样过滤、调整题目难度、增加候选、提供更细 reward 或改 baseline；但每种处理都会改变数据分布或估计偏差，需要单独监控。</p></div></details><details id="qa-5"><summary><span>Q5</span>同一个 Advantage 会给所有 token 吗？</summary><div><p>经典 outcome 形式通常是。每个 token 的 ratio 不同，但乘的 sequence advantage 相同；Process Reward 或 token/step-level returns 才提供更细 credit。</p></div></details><details id="qa-6"><summary><span>Q6</span>GRPO 是否一定需要规则 Reward？</summary><div><p>不一定，可以使用 learned Reward Model 或复合 reward。只是数学、代码等任务的规则 Verifier 更可靠可扩展，因此与该算法经常一起出现。</p></div></details><details id="qa-7"><summary><span>Q7</span>GRPO 为什么可能偏向长回答？</summary><div><p>成功轨迹可能因更多检查自然变长，同时 token/sequence aggregation、超长截断和 reward 设计也会制造 length bias。必须控制预算并比较不同长度下的真实正确率。</p></div></details><details id="qa-8"><summary><span>Q8</span>GRPO 与 <a className="term-link" href="/training/dpo">DPO</a> 可以互相替代吗？</summary><div><p>不完全。前者在线采样一组新 responses 并接受 Verifier feedback；后者从固定 chosen/rejected pairs 做离线分类。是否需要持续探索决定了更合适的路线。</p></div></details><details id="qa-9"><summary><span>Q9</span>GRPO 训练完部署时还要多采样吗？</summary><div><p>不必。组采样是训练期构造 baseline 的方法；部署时可以只生成一次。若产品需要更高 pass@k 或 self-consistency，才会额外采样，那属于 inference-time 策略。</p></div></details></div></section>
<section className="sources-section rms-sources"><div><p className="mini-label">PRIMARY SOURCES</p><h2>算法、系统与后续改进</h2></div><ol><li><a href="https://arxiv.org/html/2402.03300" target="_blank" rel="noreferrer">DeepSeekMath · Group Relative Policy Optimization</a><span>2024</span></li><li><a href="https://arxiv.org/html/2501.12948" target="_blank" rel="noreferrer">DeepSeek-R1 Technical Report</a><span>2025</span></li><li><a href="https://arxiv.org/abs/2503.14476" target="_blank" rel="noreferrer">DAPO: An Open-Source LLM Reinforcement Learning System at Scale</a><span>2025</span></li><li><a href="https://arxiv.org/abs/2507.18071" target="_blank" rel="noreferrer">Group Sequence Policy Optimization</a><span>2025</span></li></ol></section>
<footer className="article-footer"><div><span>继续连接知识</span><strong>继续从组相对 advantage 回看整个推理 rollout、Verifier 与 policy-update 系统。</strong></div><div className="footer-links"><a href="/foundations/importance-sampling">Importance Sampling ↗</a><a href="/training/reward-model">Reward Model ↗</a><a href="/training/reasoning-rl">Reasoning RL ↗</a><a href="/training/ppo">PPO ↗</a><a href="/training/dpo">DPO ↗</a></div></footer></main>
<aside className="right-rail" aria-label="本页目录"><p>本页目录</p>{chapters.map(([no,label])=><a href={no==="10"?"#qa":`#chapter-${Number(no)}`} key={no}><span>{no}</span>{label}</a>)}<RightQaIndex questions={qaQuestions}/><div className="reading-note"><span>11 个模块</span><div><i></i></div><small>公式密度 · 高</small></div></aside>
</div>}
