import type { Metadata } from "next";
import { Formula } from "../../components/Formula";
import { RightQaIndex } from "../../components/RightQaIndex";
import { TrainingSidebar } from "../../components/TrainingSidebar";

const title = "什么是重要性采样？";
const description = "从换分布恒等式、Monte Carlo 估计与 Support Condition 出发，系统讲解重要性权重、方差、自归一化、轨迹概率比，以及 PPO 中逐 Token Importance Ratio 的准确边界。";

export const metadata: Metadata = {
  title,
  description,
  openGraph: { title, description, type: "article", images: [] },
  twitter: { card: "summary", title, description, images: [] },
};

const chapters = [
  ["01", "为什么需要换分布估计"],
  ["02", "重要性采样恒等式"],
  ["03", "离散数值例子"],
  ["04", "Monte Carlo 估计量"],
  ["05", "Support Condition"],
  ["06", "方差为什么会爆炸"],
  ["07", "自归一化重要性采样"],
  ["08", "轨迹级概率比"],
  ["09", "逐决策重要性采样"],
  ["10", "PPO 的逐 Token Ratio"],
  ["11", "Ratio 与 Clip 的关系"],
  ["12", "LLM 中的准确边界"],
  ["13", "关联 QA"],
] as const;

const qaQuestions = [
  "重要性采样是在重新采样数据吗？",
  "重要性权重为什么是目标概率除以采样概率？",
  "权重大于 1 和小于 1 分别表示什么？",
  "重要性采样一定是无偏的吗？",
  "为什么目标分布支持集必须被提议分布覆盖？",
  "为什么策略相差越大，重要性采样越不稳定？",
  "Self-normalized Importance Sampling 为什么有偏却常被使用？",
  "轨迹概率比为什么是每一步 Ratio 的乘积？",
  "Per-decision Importance Sampling 为什么能降低方差？",
  "PPO 的 Ratio 是严格的完整重要性采样吗？",
  "Importance Ratio 与 KL Ratio 是同一个东西吗？",
  "PPO 使用 Ratio 后为什么仍通常被归类为 On-policy？",
];

export default function ImportanceSamplingPage() {
  return <div className="site-shell">
    <header className="topbar"><a className="brand" href="/" aria-label="模见首页"><span className="brand-mark">模</span><span>模见 <small>Model Atlas</small></span></a><nav className="topnav" aria-label="主导航"><a className="active" href="/">知识库</a><a href="#chapter-1">概率导读</a><a href="#qa">QA 索引</a></nav><div className="top-actions"><a className="search-hint" href="#qa">⌘ K&nbsp;&nbsp;QA 速查</a><span className="edition">2026.08</span></div></header>
    <TrainingSidebar selected="importance-sampling" />
    <main className="article rms-article">
      <section className="hero rms-hero" id="top"><div className="breadcrumbs"><a href="/">知识库</a><span>/</span>数学与记号规范<span>/</span>Importance Sampling</div><div className="question-label"><span>PROBABILITY ESTIMATION · 002</span></div><p className="original-question">“如果真正想评价的是新分布，但手里的样本由旧分布产生，为什么给样本乘一个概率比，就能估计新分布下的期望？”</p><div className="eyebrow"><span></span>IMPORTANCE SAMPLING</div><h1>什么是重要性采样？</h1><p className="dek">重要性采样是一种换分布估计方法：当样本来自 Proposal Distribution，却需要计算 Target Distribution 下的期望时，用目标概率与采样概率之比重新加权每个样本。</p><div className="hero-meta"><span>建立于 2026.08.25</span><i></i><span>24 分钟阅读</span><i></i><span>概率基础 + PPO / GRPO</span></div><aside className="answer-first"><span>先说结论</span><p><b>它不会把旧样本变成新样本，而是修正旧样本在平均值中的代表性：目标分布中相对更常见的样本被放大，相对更少见的样本被缩小。</b>核心恒等式与成立条件从第 02 章开始推导。</p></aside></section>

      <section className="prose-section" id="chapter-1"><div className="prose-heading"><span>01</span><div><p>THE PROBLEM BEFORE THE TRICK</p><h2>为什么会出现“想算的分布”和“采样的分布”不同？</h2></div></div><p>若能从目标分布 <Formula inline tex={String.raw`p(x)`} /> 直接采样，期望可以用普通 Monte Carlo 平均估计：</p><Formula label="目标分布下的 Monte Carlo 估计" tex={String.raw`x_1,\ldots,x_N\sim p,\qquad \mathbb E_p[f(X)]\approx\frac1N\sum_{i=1}^{N}f(x_i)`} /><p>但现实中，目标样本可能昂贵、危险、尚未生成，或者我们只有历史数据。例如 PPO 已经用 Old Policy 生成了一批 Token，做完一次参数更新后，Current Policy 已经改变；如果每更新一次都重新生成完整回答，样本成本会很高。</p><div className="compare-columns"><article><span>TARGET DISTRIBUTION</span><h3><Formula inline tex={String.raw`p(x)`} /></h3><p>我们真正想评价或优化的分布，例如更新后的 Current Policy。</p></article><article className="accent-card"><span>PROPOSAL DISTRIBUTION</span><h3><Formula inline tex={String.raw`q(x)`} /></h3><p>数据实际来自的分布，例如生成当前 Rollout 的 Old Policy。</p></article></div><aside className="answer-first"><span>重要性采样不是凭空制造新数据</span><p><b>它不能把旧样本变成真正的新样本；它只改变每条旧样本在估计量中的权重，使加权平均对应另一个分布的期望。</b></p></aside></section>

      <section className="prose-section" id="chapter-2"><div className="prose-heading"><span>02</span><div><p>CHANGE OF MEASURE</p><h2>重要性采样恒等式怎样一步步得到？</h2></div></div><p>先看离散随机变量。目标期望定义为：</p><Formula label="目标分布下的期望" tex={String.raw`\mathbb E_{X\sim p}[f(X)]=\sum_x p(x)f(x)`} /><p>在所有 <Formula inline tex={String.raw`p(x)>0`} /> 的位置，假设 <Formula inline tex={String.raw`q(x)>0`} />，于是可以乘除同一个 <Formula inline tex={String.raw`q(x)`} />：</p><Formula label="在每一项中乘除 Proposal Probability" className="compact-latex" tex={String.raw`\sum_x p(x)f(x)=\sum_x q(x)\frac{p(x)}{q(x)}f(x)`} /><p>根据期望的定义，右边正是 <Formula inline tex={String.raw`q`} /> 分布下的期望：</p><Formula label="Importance Sampling Identity" className="compact-latex" tex={String.raw`\boxed{\mathbb E_{p}[f(X)]=\mathbb E_{q}[w(X)f(X)]},\qquad w(x)=\frac{p(x)}{q(x)}`} /><p>连续分布只需把求和换成积分：</p><Formula label="连续分布版本" className="compact-latex" tex={String.raw`\int f(x)p(x)\,\mathrm dx=\int f(x)\frac{p(x)}{q(x)}q(x)\,\mathrm dx`} /><aside className="text-note"><b>“Importance” 指哪些样本对目标分布更重要</b><p>若某个样本在目标分布中比在采样分布中更常见，则 <Formula inline tex={String.raw`p(x)>q(x)`} />、权重 <Formula inline tex={String.raw`w(x)>1`} />；反之 <Formula inline tex={String.raw`w(x)<1`} />。权重修正的是出现频率差异，不是在判断样本质量好坏。</p></aside></section>

      <section className="prose-section" id="chapter-3"><div className="prose-heading"><span>03</span><div><p>A TWO-OUTCOME EXAMPLE</p><h2>一个只有 A、B 的例子怎样验证公式？</h2></div></div><p>设函数值为 <Formula inline tex={String.raw`f(A)=1`} />、<Formula inline tex={String.raw`f(B)=0`} />。目标分布更偏向 A，而采样分布是均匀的：</p><Formula label="目标分布与采样分布" className="compact-latex" tex={String.raw`p(A)=0.8,\quad p(B)=0.2,\qquad q(A)=q(B)=0.5`} /><p>直接计算目标期望：</p><Formula label="直接计算" tex={String.raw`\mathbb E_p[f(X)]=0.8\times1+0.2\times0=0.8`} /><p>Importance Weights 为：</p><Formula label="两个结果的 Importance Weights" tex={String.raw`w(A)=\frac{0.8}{0.5}=1.6,\qquad w(B)=\frac{0.2}{0.5}=0.4`} /><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>结果</th><th>在 <Formula inline tex={String.raw`q`} /> 中的概率</th><th>权重</th><th>函数值</th><th>加权贡献</th></tr></thead><tbody><tr><td>A</td><td><Formula inline tex={String.raw`0.5`} /></td><td><Formula inline tex={String.raw`1.6`} /></td><td><Formula inline tex={String.raw`1`} /></td><td><Formula inline tex={String.raw`0.5\times1.6\times1=0.8`} /></td></tr><tr><td>B</td><td><Formula inline tex={String.raw`0.5`} /></td><td><Formula inline tex={String.raw`0.4`} /></td><td><Formula inline tex={String.raw`0`} /></td><td><Formula inline tex={String.raw`0.5\times0.4\times0=0`} /></td></tr></tbody></table></div><Formula label="用 q 分布的加权期望复原 p 分布" tex={String.raw`\mathbb E_q[w(X)f(X)]=0.8+0=0.8`} /><p>如果从 <Formula inline tex={String.raw`q`} /> 抽取 100 个样本，通常约有 50 个 A、50 个 B。普通平均约为 <Formula inline tex={String.raw`0.5`} />；给 A 乘 <Formula inline tex={String.raw`1.6`} />、给 B 乘 <Formula inline tex={String.raw`0.4`} /> 后，加权平均约为 <Formula inline tex={String.raw`0.8`} />。</p></section>

      <section className="prose-section" id="chapter-4"><div className="prose-heading"><span>04</span><div><p>FROM IDENTITY TO ESTIMATOR</p><h2>有了有限样本，具体怎样计算？</h2></div></div><p>恒等式是总体层面的精确等式；实际只有从 <Formula inline tex={String.raw`q`} /> 得到的有限样本：</p><Formula label="Ordinary Importance Sampling Estimator" className="compact-latex" tex={String.raw`x_1,\ldots,x_N\sim q,\qquad \widehat\mu_{\mathrm{OIS}}=\frac1N\sum_{i=1}^{N}\frac{p(x_i)}{q(x_i)}f(x_i)`} /><p>在权重存在且期望有限的条件下：</p><Formula label="OIS 的无偏性" className="compact-latex" tex={String.raw`\mathbb E_{x_{1:N}\sim q}[\widehat\mu_{\mathrm{OIS}}]=\frac1N\sum_{i=1}^{N}\mathbb E_q[w(X_i)f(X_i)]=\mathbb E_p[f(X)]`} /><p>“无偏”只表示重复采样许多次后，估计量的平均值等于真实期望；它不表示某一次有限样本估计一定接近真值。一个无偏估计量仍可能具有极大方差。</p><aside className="boundary-box"><b>不要混淆三层对象</b><p><Formula inline tex={String.raw`\mathbb E_p[f]`} /> 是目标真值；<Formula inline tex={String.raw`\mathbb E_q[wf]`} /> 是完全相等的换分布表达式；<Formula inline tex={String.raw`N^{-1}\sum_iw_if_i`} /> 才是用有限样本计算的随机估计量。</p></aside></section>

      <section className="prose-section" id="chapter-5"><div className="prose-heading"><span>05</span><div><p>THE NON-NEGOTIABLE COVERAGE ASSUMPTION</p><h2>为什么必须满足 Support Condition？</h2></div></div><Formula label="Support / Absolute Continuity Condition" className="compact-latex" tex={String.raw`p(x)>0\quad\Longrightarrow\quad q(x)>0`} /><p>如果目标分布认为某个区域可能发生，但采样分布从不进入该区域，那么手里的数据永远不会包含它，权重 <Formula inline tex={String.raw`p(x)/q(x)`} /> 也会除以零。</p><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>情形</th><th>能否修正</th><th>原因</th></tr></thead><tbody><tr><td><Formula inline tex={String.raw`p(x)>0,\ q(x)>0`} /></td><td>原则上可以</td><td>样本可能出现，且 Ratio 有定义</td></tr><tr><td><Formula inline tex={String.raw`p(x)=0,\ q(x)>0`} /></td><td>可以</td><td>权重为零，该样本不属于目标分布</td></tr><tr><td><Formula inline tex={String.raw`p(x)>0,\ q(x)=0`} /></td><td>不可以</td><td>目标区域从未被采样，无法由加权恢复</td></tr></tbody></table></div><aside className="answer-first"><span>重要性采样只能重新分配已有覆盖范围内的权重</span><p><b>它不能为完全没见过的区域补造样本。Proposal 覆盖越差，估计越不可靠；没有覆盖时，估计问题本身不可识别。</b></p></aside></section>

      <section className="prose-section" id="chapter-6"><div className="prose-heading"><span>06</span><div><p>UNBIASED DOES NOT MEAN STABLE</p><h2>重要性权重为什么会让方差爆炸？</h2></div></div><p>OIS 单样本项为 <Formula inline tex={String.raw`Z=w(X)f(X)`} />，估计量方差为：</p><Formula label="OIS Estimator Variance" className="compact-latex" tex={String.raw`\operatorname{Var}(\widehat\mu_{\mathrm{OIS}})=\frac1N\operatorname{Var}_{q}[w(X)f(X)]`} /><p>若目标分布非常重视某个区域，但 Proposal 很少访问它，则该区域的权重可能巨大。大多数 Batch 完全采不到它，偶尔采到一次又让单个样本支配整个平均值。</p><Formula label="小 Proposal Probability 产生大权重" tex={String.raw`q(x)\ll p(x)\quad\Longrightarrow\quad w(x)=\frac{p(x)}{q(x)}\gg1`} /><p>可以用 Effective Sample Size 粗略判断权重是否集中。令归一化权重 <Formula inline tex={String.raw`\widetilde w_i=w_i/\sum_jw_j`} />：</p><Formula label="Effective Sample Size" className="compact-latex" tex={String.raw`N_{\mathrm{eff}}=\frac{1}{\sum_{i=1}^{N}\widetilde w_i^2}=\frac{(\sum_iw_i)^2}{\sum_iw_i^2}`} /><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>权重形态</th><th><Formula inline tex={String.raw`N_{\mathrm{eff}}`} /></th><th>含义</th></tr></thead><tbody><tr><td>所有 <Formula inline tex={String.raw`w_i`} /> 接近相等</td><td>接近 <Formula inline tex={String.raw`N`} /></td><td>多数样本都有效</td></tr><tr><td>少数权重很大</td><td>显著小于 <Formula inline tex={String.raw`N`} /></td><td>表面有很多样本，实际由少数样本决定</td></tr><tr><td>一个权重占据全部</td><td>接近 <Formula inline tex={String.raw`1`} /></td><td>整个 Batch 几乎退化成单样本估计</td></tr></tbody></table></div><aside className="text-note"><b>方差问题的根源是分布重叠不足</b><p>增加样本量能减小 <Formula inline tex={String.raw`1/N`} />，却不能从根本上修复极差的 Proposal。更有效的办法通常是让 <Formula inline tex={String.raw`q`} /> 更接近 <Formula inline tex={String.raw`p`} />、限制权重、分层采样，或者更频繁地重新采样。</p></aside></section>

      <section className="prose-section" id="chapter-7"><div className="prose-heading"><span>07</span><div><p>TRADE A LITTLE BIAS FOR LOWER VARIANCE</p><h2>Self-normalized Importance Sampling 做了什么？</h2></div></div><p>Ordinary IS 用 <Formula inline tex={String.raw`1/N`} /> 平均加权样本。Self-normalized / Weighted IS 则让样本权重在当前 Batch 内归一化到和为一：</p><Formula label="Self-normalized Importance Sampling" className="compact-latex" tex={String.raw`\widehat\mu_{\mathrm{SNIS}}=\frac{\sum_{i=1}^{N}w_i f(x_i)}{\sum_{i=1}^{N}w_i}=\sum_{i=1}^{N}\widetilde w_i f(x_i)`} /><p>它通常具有更低、也更可控的方差，但有限样本下一般有偏，因为“两个随机和的比值”的期望不等于“两个期望的比值”：</p><Formula label="比值估计的有限样本偏差来源" className="compact-latex" tex={String.raw`\mathbb E\!\left[\frac{\sum_iw_if_i}{\sum_iw_i}\right]\ne\frac{\mathbb E[\sum_iw_if_i]}{\mathbb E[\sum_iw_i]}`} /><p>在常见正则条件下，样本量增大时它仍是一致估计，即会收敛到正确目标。</p><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>估计量</th><th>有限样本偏差</th><th>方差</th><th>典型取舍</th></tr></thead><tbody><tr><td>Ordinary IS</td><td>通常无偏</td><td>可能非常高，甚至无界</td><td>理论直接，但易受极端权重支配</td></tr><tr><td>Self-normalized / Weighted IS</td><td>通常有偏</td><td>往往更低，若 <Formula inline tex={String.raw`f`} /> 有界则估计也被其范围约束</td><td>牺牲少量有限样本偏差换稳定性</td></tr><tr><td>Clipped / Truncated IS</td><td>有偏</td><td>通过限制大权重下降</td><td>需要选择截断阈值</td></tr></tbody></table></div></section>

      <section className="prose-section" id="chapter-8"><div className="prose-heading"><span>08</span><div><p>SEQUENCES MULTIPLY RATIOS</p><h2>强化学习中的轨迹概率比为什么是乘积？</h2></div></div><p>一条长度为 <Formula inline tex={String.raw`T`} /> 的轨迹记作 <Formula inline tex={String.raw`\tau=(s_0,a_0,\ldots,s_T)`} />。在同一个环境动力学 <Formula inline tex={String.raw`P`} /> 下，策略 <Formula inline tex={String.raw`\pi`} /> 生成它的概率为：</p><Formula label="Trajectory Probability" className="compact-latex" tex={String.raw`P_\pi(\tau)=d_0(s_0)\prod_{t=0}^{T-1}\pi(a_t\mid s_t)P(s_{t+1}\mid s_t,a_t)`} /><p>Target Policy 与 Behavior Policy 使用相同初始状态分布和环境，因此概率比中这些项消掉，只剩动作选择概率：</p><Formula label="Trajectory Importance Ratio" className="compact-latex" tex={String.raw`\frac{P_{\pi}(\tau)}{P_b(\tau)}=\prod_{t=0}^{T-1}\frac{\pi(a_t\mid s_t)}{b(a_t\mid s_t)}=\prod_{t=0}^{T-1}\rho_t`} /><p>于是可以用 Behavior Policy 的轨迹估计 Target Policy 的 Return：</p><Formula label="Trajectory-level Off-policy Evaluation" className="compact-latex" tex={String.raw`J(\pi)=\mathbb E_{\tau\sim P_b}\!\left[\left(\prod_{t=0}^{T-1}\rho_t\right)G(\tau)\right]`} /><aside className="boundary-box"><b>长轨迹会放大连乘问题</b><p>即使每个 <Formula inline tex={String.raw`\rho_t`} /> 只略微偏离 <Formula inline tex={String.raw`1`} />，很多 Ratio 连乘后也可能趋近零或变得巨大。LLM 回答包含成百上千 Token，所以完整序列 Ratio 的方差尤其危险。</p></aside></section>

      <section className="prose-section" id="chapter-9"><div className="prose-heading"><span>09</span><div><p>ONLY CORRECT THE PREFIX THAT CAN AFFECT THE REWARD</p><h2>Per-decision Importance Sampling 为什么能降低方差？</h2></div></div><p>轨迹终点的总 Return 可以拆成各时刻 Reward：</p><Formula label="Discounted Return" tex={String.raw`G_0=\sum_{t=0}^{T-1}\gamma^t r_t`} /><p>时刻 <Formula inline tex={String.raw`t`} /> 已经获得的 <Formula inline tex={String.raw`r_t`} /> 不会受到未来动作 <Formula inline tex={String.raw`a_{t+1:T-1}`} /> 的影响，因此无需给它乘整条轨迹后半段的 Ratio。逐决策形式只修正产生该 Reward 之前的策略差异：</p><Formula label="Per-decision Importance Sampling" className="compact-latex" tex={String.raw`J(\pi)=\mathbb E_{\tau\sim P_b}\!\left[\sum_{t=0}^{T-1}\gamma^t\left(\prod_{k=0}^{t}\rho_k\right)r_t\right]`} /><p>与每个 Reward 都乘 <Formula inline tex={String.raw`\prod_{k=0}^{T-1}\rho_k`} /> 相比，它删除了与该 Reward 因果上无关的未来随机 Ratio，因此通常降低方差，同时保持相应估计的正确换分布逻辑。</p><aside className="text-note"><b>Per-decision 不等于 PPO 的 Per-token Surrogate</b><p>Per-decision IS 仍会为时刻 <Formula inline tex={String.raw`t`} /> 的 Reward 乘从轨迹开头到 <Formula inline tex={String.raw`t`} /> 的 Ratio 前缀；PPO 常见 surrogate 只显式使用当前动作的单步 Ratio <Formula inline tex={String.raw`\rho_t`} />，并把 Old Policy 下估出的 Advantage 固定下来。二者不能只因为都“逐步计算”就视为同一个估计量。</p></aside></section>

      <section className="prose-section" id="chapter-10"><div className="prose-heading"><span>10</span><div><p>WHAT PPO BORROWS AND WHAT IT APPROXIMATES</p><h2>PPO 的逐 Token Importance Ratio 到底修正了什么？</h2></div></div><p>固定一个已经由 Old Policy 访问到的状态 <Formula inline tex={String.raw`s_t`} />，新策略下的动作期望可以改写为：</p><Formula label="给定状态下的 Action Distribution Correction" className="compact-latex" tex={String.raw`\sum_a\pi_\theta(a\mid s_t)A^{\mathrm{old}}(s_t,a)=\mathbb E_{a\sim\pi_{\mathrm{old}}}\!\left[\frac{\pi_\theta(a\mid s_t)}{\pi_{\mathrm{old}}(a\mid s_t)}A^{\mathrm{old}}(s_t,a)\right]`} /><p>PPO 因此定义：</p><Formula label="PPO Per-token Importance Ratio" className="compact-latex" tex={String.raw`\rho_t(\theta)=\frac{\pi_\theta(a_t\mid s_t)}{\pi_{\mathrm{old}}(a_t\mid s_t)}=\exp\!\left(\log\pi_\theta(a_t\mid s_t)-\log\pi_{\mathrm{old}}(a_t\mid s_t)\right)`} /><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th><Formula inline tex={String.raw`\rho_t`} /></th><th>当前 Token 概率怎样变化</th><th>是否说明动作好坏</th></tr></thead><tbody><tr><td><Formula inline tex={String.raw`1`} /></td><td>新旧策略概率相同</td><td>不说明</td></tr><tr><td><Formula inline tex={String.raw`1.4`} /></td><td>新策略概率是旧策略的 <Formula inline tex={String.raw`1.4`} /> 倍</td><td>仍需查看 Advantage</td></tr><tr><td><Formula inline tex={String.raw`0.6`} /></td><td>新策略概率降为旧策略的 <Formula inline tex={String.raw`60\%`} /></td><td>仍需查看 Advantage</td></tr></tbody></table></div><Formula label="Unclipped PPO Surrogate" tex={String.raw`L^{\mathrm{PG}}(\theta)=\mathbb E_t[\rho_t(\theta)\widehat A_t]`} /><p>这里的 <Formula inline tex={String.raw`\widehat A_t`} /> 通常由 Old Policy 的 Rollout、Reward 与 Critic/GAE 预先计算并 Stop-Gradient。Ratio 只修正“在相同已访问状态下，新旧策略选择这个动作的相对概率”。</p><aside className="answer-first"><span>PPO 不是精确的完整轨迹重要性采样</span><p><b>它没有在 surrogate 中显式乘完整轨迹 Ratio，也没有完全修正新旧策略导致的状态/前缀访问分布变化。</b>它依赖新旧策略足够接近，使 Old Policy 的状态分布与 Advantage 仍能近似服务于 Current Policy。</p></aside><p><a className="term-link" href="/training/ppo#chapter-11">PPO 第 11 章</a>继续解释 Old Policy、Current Policy 和 Reference Policy 的角色；本页负责给出 Ratio 背后的通用换分布原理。</p></section>

      <section className="prose-section" id="chapter-11"><div className="prose-heading"><span>11</span><div><p>WHY PPO DOES NOT TRUST LARGE WEIGHTS</p><h2>Importance Ratio 与 PPO Clip 是什么关系？</h2></div></div><p>未经限制的 Importance Weight 可以远离 <Formula inline tex={String.raw`1`} />。PPO 在同一批 Rollout 上做多次更新时，Current Policy 与 Old Policy 的差距逐渐扩大，Ratio 变得更不可靠：</p><Formula label="PPO Clipped Surrogate Objective" className="compact-latex" tex={String.raw`L^{\mathrm{CLIP}}(\theta)=\mathbb E_t\!\left[\min\!\left(\rho_t\widehat A_t,\operatorname{clip}(\rho_t,1-\epsilon,1+\epsilon)\widehat A_t\right)\right]`} /><p>Clip 的动机与重要性采样的高方差问题相通：不要让某些已经偏离 Old Policy 很远的样本继续提供无限增大的 surrogate 收益。但二者不能简单等同：</p><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>机制</th><th>做了什么</th><th>没有保证什么</th></tr></thead><tbody><tr><td>Importance Ratio</td><td>衡量新旧策略对已采样动作的概率比</td><td>不保证 Advantage 正确，也不限制参数距离</td></tr><tr><td>PPO Clip</td><td>截平沿 Advantage 一致方向越界后的额外 surrogate 收益</td><td>不是把所有 Ratio 强制塞回区间</td></tr><tr><td>KL Monitoring / Early Stop</td><td>监控整个策略分布是否偏离过大</td><td>不能修复 Reward 或 Advantage 的方向错误</td></tr></tbody></table></div><aside className="boundary-box"><b>Clipping 会引入偏差</b><p>一旦把原始权重或 surrogate 截断，就不再保留 Ordinary IS 的精确无偏性质。PPO 有意接受这种近似，换取更稳定的有限 Batch 策略优化。</p></aside></section>

      <section className="prose-section" id="chapter-12"><div className="prose-heading"><span>12</span><div><p>LLM-SPECIFIC BOUNDARIES</p><h2>放进大模型训练后，最容易混淆哪些 Ratio？</h2></div></div><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>Ratio</th><th>比较对象</th><th>用途</th></tr></thead><tbody><tr><td><Formula inline tex={String.raw`\rho_t=\pi_\theta(a_t\mid s_t)/\pi_{\mathrm{old}}(a_t\mid s_t)`} /></td><td>Current 与生成本批数据的 Old Policy</td><td>PPO / GRPO surrogate 与 clipping</td></tr><tr><td><Formula inline tex={String.raw`\pi_{\mathrm{rollout}}(a_t\mid s_t)/\pi_{\mathrm{ref}}(a_t\mid s_t)`} /></td><td>短期 Rollout Policy 与长期 Reference Policy</td><td>KL Reward Shaping</td></tr><tr><td><Formula inline tex={String.raw`\pi_\theta(y\mid x)/\pi_{\mathrm{old}}(y\mid x)=\prod_t\rho_t`} /></td><td>整条回答在两个策略下的序列概率</td><td>完整序列换分布概念；长文本中方差很高</td></tr><tr><td><Formula inline tex={String.raw`\log\pi_\theta(y\mid x)-\log\pi_{\mathrm{ref}}(y\mid x)`} /></td><td>序列 Log Probability 差</td><td>KL 正则、DPO/KTO 等目标中的相对锚点</td></tr></tbody></table></div><p>还要区分 Ratio 与 Log Ratio：</p><Formula label="Ratio 与 Log Ratio 的转换" tex={String.raw`\rho_t=\exp(\Delta\log\pi_t),\qquad \Delta\log\pi_t=\log\rho_t`} /><p>概率 Ratio 永远为正；Log Ratio 可以为正、零或负。实践中先保存和相减 Log Probability，再取指数得到 Ratio，能避免直接相除极小概率造成数值不稳定。</p><aside className="qwen-connection"><span>CONNECTION · PPO / GRPO</span><p><a className="term-link" href="/training/ppo">PPO</a> 与 <a className="term-link" href="/training/grpo">GRPO</a> 都使用 Old-policy Ratio 和 Clip；主要差别不在重要性采样，而在 Advantage 的来源：PPO 常用 Critic/GAE，GRPO 使用同 Prompt 的组内相对 Reward。</p><a href="/training/ppo#chapter-11">继续回到 PPO 的 Ratio 与 Clip 推导 ↗</a></aside></section>

      <section className="prose-section rms-qa" id="qa"><div className="prose-heading"><span>13</span><div><p>QUESTIONS AS CONNECTIONS</p><h2>关联 QA</h2></div></div><div className="qa-list">
        <details id="qa-1" open><summary><span>Q1</span>重要性采样是在重新采样数据吗？</summary><div><p>不是。原始样本仍来自 <Formula inline tex={String.raw`q`} />；重要性采样只在计算平均值时给每条样本乘 <Formula inline tex={String.raw`p(x)/q(x)`} />。Importance Resampling 是另一个可能根据权重重新抽样的具体方法。</p></div></details>
        <details id="qa-2"><summary><span>Q2</span>重要性权重为什么是目标概率除以采样概率？</summary><div><p>因为样本平均天然带有 <Formula inline tex={String.raw`q(x)`} /> 的出现频率。乘 <Formula inline tex={String.raw`p(x)/q(x)`} /> 后，<Formula inline tex={String.raw`q(x)`} /> 被约掉，留下目标频率 <Formula inline tex={String.raw`p(x)`} />：<Formula inline tex={String.raw`q(x)\,[p(x)/q(x)]=p(x)`} />。</p></div></details>
        <details id="qa-3"><summary><span>Q3</span>权重大于 1 和小于 1 分别表示什么？</summary><div><p><Formula inline tex={String.raw`w>1`} /> 表示该样本在目标分布中比在采样分布中更常见，需要放大贡献；<Formula inline tex={String.raw`w<1`} /> 表示它在采样数据中过度出现，需要缩小贡献。它不直接表示样本好或坏。</p></div></details>
        <details id="qa-4"><summary><span>Q4</span>重要性采样一定是无偏的吗？</summary><div><p>标准 Ordinary IS 在覆盖、可积和正确权重等条件下通常无偏；Self-normalized、Clipped、Truncated IS 一般会引入有限样本偏差。无偏也不等于低方差。</p></div></details>
        <details id="qa-5"><summary><span>Q5</span>为什么目标分布支持集必须被提议分布覆盖？</summary><div><p>若 <Formula inline tex={String.raw`p(x)>0`} /> 却有 <Formula inline tex={String.raw`q(x)=0`} />，该区域永远不会出现在样本中，且权重除以零。重新加权不能恢复完全缺失的数据。</p></div></details>
        <details id="qa-6"><summary><span>Q6</span>为什么策略相差越大，重要性采样越不稳定？</summary><div><p>分布重叠下降时，大多数权重接近零，少数权重极大，估计由极少数样本支配；轨迹任务还会把多个单步 Ratio 连乘，使差异随长度放大。</p></div></details>
        <details id="qa-7"><summary><span>Q7</span>Self-normalized Importance Sampling 为什么有偏却常被使用？</summary><div><p>它把权重归一化为和等于一，通常显著降低极端权重造成的方差，并让有界函数的估计保持在样本函数值范围内。有限样本有偏，但在常见条件下是一致估计。</p></div></details>
        <details id="qa-8"><summary><span>Q8</span>轨迹概率比为什么是每一步 Ratio 的乘积？</summary><div><p>自回归/序列概率由条件概率连乘得到。新旧策略共享环境动力学时，状态转移项在两个轨迹概率相除后抵消，只剩每一步动作概率比的乘积。</p></div></details>
        <details id="qa-9"><summary><span>Q9</span>Per-decision Importance Sampling 为什么能降低方差？</summary><div><p>时刻 <Formula inline tex={String.raw`t`} /> 的 Reward 不依赖未来动作，因此只乘到 <Formula inline tex={String.raw`t`} /> 为止的 Ratio 前缀；删除无关的未来随机 Ratio，通常能降低方差。</p></div></details>
        <details id="qa-10"><summary><span>Q10</span><a className="term-link" href="/training/ppo">PPO</a> 的 Ratio 是严格的完整重要性采样吗？</summary><div><p>不是。PPO surrogate 通常只使用当前动作的单步 Ratio，并依赖 Old Policy 下估计的 Advantage；它没有完整修正状态分布变化，也没有使用整条轨迹 Ratio。</p></div></details>
        <details id="qa-11"><summary><span>Q11</span>Importance Ratio 与 KL Ratio 是同一个东西吗？</summary><div><p>可能使用相似的概率比形式，但角色不同。PPO Importance Ratio 比较 Current 与 Old Policy；RLHF 的 KL 项通常比较 Rollout/Current 与长期 Reference Policy。必须先看分子、分母分别是哪两个策略。</p></div></details>
        <details id="qa-12"><summary><span>Q12</span>PPO 使用 Ratio 后为什么仍通常被归类为 On-policy？</summary><div><p>因为 Rollout 来自刚刚冻结的最新策略快照，只在少量 Epoch 内短暂复用，然后丢弃并重新采样。它确实产生轻度 Off-policy 偏移，但不长期复用大型 Replay Buffer 中的旧策略数据。</p></div></details>
      </div></section>

      <section className="sources-section rms-sources"><div><p className="mini-label">PRIMARY SOURCES</p><h2>重要性采样、Off-policy 与策略优化</h2></div><ol><li><a href="https://proceedings.neurips.cc/paper_files/paper/2014/hash/1c64ee92596e8ea5050fc435a1d57459-Abstract.html" target="_blank" rel="noreferrer">Weighted Importance Sampling for Off-policy Learning</a><span>NeurIPS 2014</span></li><li><a href="https://www.jmlr.org/papers/v21/20-124.html" target="_blank" rel="noreferrer">Importance Sampling Techniques for Policy Optimization</a><span>JMLR 2020</span></li><li><a href="https://arxiv.org/abs/1707.06347" target="_blank" rel="noreferrer">Proximal Policy Optimization Algorithms</a><span>2017</span></li><li><a href="https://proceedings.neurips.cc/paper_files/paper/2005/hash/f75526659f31040afeb61cb7133e4e6d-Abstract.html" target="_blank" rel="noreferrer">Off-policy Learning with Options and Recognizers</a><span>NeurIPS 2005</span></li></ol></section>
      <footer className="article-footer"><div><span>继续连接知识</span><strong>把换分布估计放回策略更新中，继续理解 Ratio、Advantage 与 Clip 怎样组成 PPO。</strong></div><div className="footer-links"><a href="/training/ppo#chapter-11">PPO Ratio ↗</a><a href="/training/grpo#chapter-5">GRPO Ratio ↗</a><a href="/training/rlhf">RLHF ↗</a></div></footer>
    </main>
    <aside className="right-rail" aria-label="本页目录"><p>本页目录</p>{chapters.map(([no,label])=><a href={no==="13"?"#qa":`#chapter-${Number(no)}`} key={no}><span>{no}</span>{label}</a>)}<RightQaIndex questions={qaQuestions}/><div className="reading-note"><span>13 章</span><div><i></i></div><small>公式密度 · 高</small></div></aside>
  </div>;
}
