import type { Metadata } from "next";
import { RightQaIndex } from "../../components/RightQaIndex";
import { TrainingSidebar } from "../../components/TrainingSidebar";

const title = "LLM Agent：概念、架构与工程实践";
const description = "从系统工程视角综述 LLM Agent：使用边界、分层架构、执行循环、模型与 Tool 协议、MCP、状态与 Memory、控制模式、多 Agent、主流框架、安全、运行时和评测。";
export const metadata: Metadata = { title, description, openGraph: { title, description, type: "article", images: [] }, twitter: { card: "summary", title, description, images: [] } };

const chapters = [
  ["01", "Agent 到底是什么"], ["02", "何时应该使用 Agent"], ["03", "整体分层架构"],
  ["04", "一次 Run 的执行时序"], ["05", "模型调用与输出协议"], ["06", "Tools、ACI 与 MCP"],
  ["07", "Context、State 与 Memory"], ["08", "常见控制模式"], ["09", "单 Agent 与多 Agent"],
  ["10", "主流框架与选型"], ["11", "可靠性与安全边界"], ["12", "运行基础设施"],
  ["13", "Tracing、评测与调试"], ["14", "生产案例与设计清单"], ["15", "关联 QA"],
];

const qaQuestions = [
  "一次 LLM 调用算 Agent 吗？", "Agent 与 Workflow 的根本区别是什么？", "RAG 系统算 Agent 吗？",
  "为什么不应该把所有 LLM 应用都做成 Agent？", "Tool Calling 等于 Tool 已执行吗？", "Structured Output 与 Tool Calling 有什么区别？",
  "MCP 是 Agent 框架吗？", "State、Context 与 Memory 有什么区别？", "什么时候需要 Planning？",
  "什么时候值得使用多 Agent？", "Manager 与 Handoff 有什么区别？", "LangChain 与 LangGraph 有什么区别？",
  "一定要使用 Agent 框架吗？", "怎样防止 Agent 无限循环？", "为什么最终答案正确仍可能是失败？",
  "一个 Agent 上线前最少要具备什么？",
];

export default function AgentPage() {
  return <div className="site-shell">
    <header className="topbar"><a className="brand" href="/" aria-label="模见首页"><span className="brand-mark">模</span><span>模见 <small>Model Atlas</small></span></a><nav className="topnav"><a className="active" href="/">知识库</a><a href="#chapter-3">架构总览</a><a href="#qa">QA 索引</a></nav><div className="top-actions"><a className="search-hint" href="#qa">⌘ K&nbsp;&nbsp;QA 速查</a><span className="edition">2026.08</span></div></header>
    <TrainingSidebar selected="agent" />
    <main className="article rms-article">
      <section className="hero rms-hero" id="top"><div className="breadcrumbs"><a href="/">知识库</a><span>/</span>Agent 与应用<span>/</span>Agent 基础</div><div className="question-label"><span>AGENT SYSTEMS · 001</span></div><p className="original-question">“Agent 不是一个新的模型名称。那么，当 LLM、Tools、Memory、Workflow 和运行时被组合到一起时，系统究竟是怎样工作的？”</p><div className="eyebrow"><span></span>AN ENGINEERING OVERVIEW OF LLM AGENTS</div><h1>LLM Agent</h1><p className="dek">Agent 是一种让模型参与控制流程的应用架构：模型根据目标和当前环境反馈选择下一步动作，运行时负责执行、保存状态、施加权限和控制循环。它的难点不在某个公式，而在模型与确定性软件之间如何分工。</p><div className="hero-meta"><span>重写于 2026.08.25</span><i></i><span>80 分钟阅读</span><i></i><span>架构图 + 时序 + 工程实践</span></div><aside className="answer-first"><span>一句话先建立边界</span><p><b>LLM 负责处理难以穷举的判断，Runtime 负责执行必须正确的控制。</b>模型可以选择 Tool、提出计划和解释结果；鉴权、事务、审批、重试、幂等、状态持久化和停止条件不能只依赖模型。</p></aside></section>

      <section className="prose-section" id="chapter-1"><div className="prose-heading"><span>01</span><div><p>DEFINITION AND BOUNDARY</p><h2>Agent 到底是什么？先把它与相近系统分开</h2></div></div><p>“Agent”在行业里经常被宽泛使用。工程上最有用的定义是：<b>一个面向目标、能够观察环境、选择动作、接收动作结果并继续决策的闭环系统。</b>模型是决策部件，Agent Runtime 才是把模型、Tools、State 和安全策略连接起来的执行主体。</p><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>系统形态</th><th>控制下一步的是谁</th><th>是否形成环境反馈闭环</th><th>典型例子</th></tr></thead><tbody><tr><td>Single LLM Call</td><td>没有下一步</td><td>否</td><td>摘要、改写、分类、抽取</td></tr><tr><td>RAG Application</td><td>代码固定“检索 → 生成”</td><td>通常没有动态循环</td><td>知识库问答</td></tr><tr><td>Workflow</td><td>代码预先定义节点和分支</td><td>可以有，但路径主要固定</td><td>审核流水线、固定客服流程</td></tr><tr className="highlight-row"><td>Agent</td><td>模型根据目标与 Observation 动态选择</td><td>有</td><td>开放式研究、编码、复杂客服处理</td></tr><tr><td>Agentic Workflow</td><td>代码骨架 + 局部模型决策</td><td>有</td><td>多数生产系统的实际形态</td></tr></tbody></table></div><aside className="boundary-box"><b>Agent 与 Workflow 不是互斥的产品类别</b><p>生产系统通常把二者组合：代码固定高风险主干，在 Router、Tool Selection、信息抽取或异常处理节点交给模型判断。真正需要设计的是<b>控制权放在哪里</b>，不是给系统贴哪个标签。</p></aside></section>

      <section className="prose-section" id="chapter-2"><div className="prose-heading"><span>02</span><div><p>WHEN TO USE IT</p><h2>什么问题值得使用 Agent，什么问题不值得？</h2></div></div><p>Agent 用多轮模型调用和动态 Tool Use 换取任务灵活性，因此通常更慢、更贵，也更难测试。若一个任务可以通过单次模型调用、RAG 或固定 Workflow 稳定完成，增加 Agent Loop 往往只会增加故障表面积。</p><div className="compare-columns"><article><span>GOOD FIT</span><h3>适合 Agent 的任务</h3><ul><li>完成路径无法提前完全枚举</li><li>必须根据 Tool Results 持续修正下一步</li><li>有可查询的环境或可验证的成功条件</li><li>允许模型在受控范围内做局部决策</li><li>失败可以重试、回滚、澄清或转人工</li></ul></article><article className="accent-card"><span>POOR FIT</span><h3>不适合 Agent 的任务</h3><ul><li>固定规则已经可以准确完成</li><li>要求极低延迟或严格确定性</li><li>没有可靠工具和环境反馈</li><li>动作不可逆且无法设置审批</li><li>任务成功标准本身无法判断</li></ul></article></div><div className="text-note"><b>选择顺序</b><p>优先尝试 Single Call → Retrieval / Structured Output → Deterministic Workflow → Agentic Workflow → Autonomous Agent。只有前一层无法满足效果时，再增加控制自由度。</p></div></section>

      <section className="prose-section" id="chapter-3"><div className="prose-heading"><span>03</span><div><p>SYSTEM ARCHITECTURE</p><h2>一个生产级 Agent 的整体架构由哪些层组成？</h2></div></div><p>从架构上看，Agent 不是“Prompt + Function Calling”，而是一个分层系统。下面每一层都可以替换技术实现，但职责边界应保持清楚。</p><div className="agent-architecture-board" role="img" aria-label="生产级 LLM Agent 的分层架构"><div className="agent-arch-layer"><strong>EXPERIENCE</strong><div><article><b>Web / App / API</b><small>用户输入、流式输出、交互反馈</small></article><article><b>Request Gateway</b><small>身份、租户、限流、Run ID</small></article><article><b>Approval UI</b><small>高风险动作确认与修改</small></article></div></div><div className="agent-arch-layer"><strong>AGENT RUNTIME</strong><div><article><b>Control Loop</b><small>Model → Action → Observation → Repeat</small></article><article><b>Router / Planner</b><small>下一步、分支、委派与停止</small></article><article><b>State Machine</b><small>Run、Thread、Task 与 Checkpoint</small></article><article><b>Middleware</b><small>Guardrails、Retry、Budget、HITL</small></article></div></div><div className="agent-arch-layer"><strong>CONTEXT</strong><div><article><b>Instructions</b><small>角色、规则、输出契约</small></article><article><b>Working State</b><small>当前任务事实和中间结果</small></article><article><b>Retrieval</b><small>知识、用户信息与历史经验</small></article><article><b>Tool Registry</b><small>当前可用能力及其 Schema</small></article></div></div><div className="agent-arch-layer"><strong>MODEL LAYER</strong><div><article><b>Model Adapter</b><small>Provider API、Messages / Items</small></article><article><b>Model Routing</b><small>能力、成本、延迟与回退</small></article><article><b>Structured Output</b><small>Schema 约束与解析</small></article></div></div><div className="agent-arch-layer"><strong>CAPABILITIES</strong><div><article><b>Function Tools</b><small>数据库、业务 API、搜索</small></article><article><b>MCP Servers</b><small>标准化 Tools、Resources、Prompts</small></article><article><b>Sandbox</b><small>文件、代码、Shell、Browser</small></article><article><b>Other Agents</b><small>Agent-as-Tool 或 Handoff</small></article></div></div><div className="agent-arch-layer"><strong>STATE & DATA</strong><div><article><b>Checkpoint Store</b><small>暂停、恢复、并发和锁</small></article><article><b><a className="term-link" href="/agents/memory">Memory Store</a></b><small>跨会话事实、偏好与经历</small></article><article><b>Event / Audit Log</b><small>原始证据与可回放轨迹</small></article><article><b>Artifact Store</b><small>文件、报告和任务产物</small></article></div></div><div className="agent-arch-layer"><strong>OPERATIONS</strong><div><article><b>Tracing</b><small>Model、Tool、State、Handoff Spans</small></article><article><b>Evaluation</b><small>结果、轨迹、成本和安全</small></article><article><b>Policy & Secrets</b><small>权限、凭证、数据边界</small></article></div></div></div><p>这张图最重要的不是组件数量，而是两条边界：第一，模型不会直接拥有真实世界权限；第二，Context 只是某次调用中模型看见的内容，长期 State 和真实业务数据必须有独立的 Source of Truth。</p></section>

      <section className="prose-section" id="chapter-4"><div className="prose-heading"><span>04</span><div><p>ONE RUN, MANY STEPS</p><h2>用户发送一次请求以后，Agent Run 怎样执行？</h2></div></div><div className="agent-loop-board" role="img" aria-label="Agent Run 的闭环执行流程"><article><span>01</span><b>Receive</b><small>创建 Run，解析身份与目标</small></article><article><span>02</span><b>Assemble</b><small>构建 Instructions、State、Tools</small></article><article><span>03</span><b>Call Model</b><small>获得 Text、Data 或 Tool Calls</small></article><article><span>04</span><b>Dispatch</b><small>结束、澄清、执行或委派</small></article><article><span>05</span><b>Execute</b><small>验证权限并调用外部能力</small></article><article><span>06</span><b>Observe</b><small>保存 Result、Error 与 State</small></article><article><span>07</span><b>Continue</b><small>回到模型或生成最终响应</small></article></div><p>一次用户请求可能包含多次模型调用。模型第一次选择查询订单，Runtime 执行查询后把结果交回模型；模型可能继续检查退款规则，再提出退款动作；若需要审批，Run 会暂停，待用户确认后从 Checkpoint 恢复。</p><div className="agent-sequence"><table><thead><tr><th></th><th>User</th><th>Agent Runtime</th><th>Model</th><th>Order Tool</th><th>State Store</th></tr></thead><tbody><tr><td>01</td><td className="active-cell">“帮我退 A123”</td><td>创建 Run，加载 Thread</td><td></td><td></td><td>读取 Checkpoint</td></tr><tr><td>02</td><td></td><td>发送 Context + Tool Schemas</td><td className="active-cell">选择 get_order</td><td></td><td></td></tr><tr><td>03</td><td></td><td>校验身份与参数</td><td></td><td className="active-cell">返回订单状态</td><td>保存 Tool Result</td></tr><tr><td>04</td><td></td><td>把 Observation 再交给模型</td><td className="active-cell">提出 refund_order</td><td></td><td></td></tr><tr><td>05</td><td className="active-cell">确认退款</td><td>暂停并等待审批</td><td></td><td></td><td>保存 Pending Approval</td></tr><tr><td>06</td><td></td><td>恢复、执行并验证回执</td><td className="active-cell">依据结果生成答复</td><td className="active-cell">退款成功</td><td>提交最终状态</td></tr></tbody></table></div><aside className="boundary-box"><b>Agent Run 与 Chat Turn 不是同一个概念</b><p>一个 Chat Turn 是用户界面上的一问一答；一个 Run 是服务端完成该请求的整段执行，可能包含多次 Model Call、多个 Tool Calls、暂停、恢复和 Handoff。成本、延迟与成功率应该按 Run 统计。</p></aside></section>

      <section className="prose-section" id="chapter-5"><div className="prose-heading"><span>05</span><div><p>MODEL INTERFACE</p><h2>Agent Runtime 与 LLM 通过什么格式通信？</h2></div></div><p>不同模型 Provider 的字段名称不同，但语义基本一致：Runtime 提供 Instructions、历史 Items、当前输入和可用 Tools；模型返回自然语言、结构化数据、Tool Call，或它们组成的事件流。</p><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>输出形态</th><th>含义</th><th>Runtime 怎样处理</th></tr></thead><tbody><tr><td>Text</td><td>给用户看的自然语言</td><td>检查是否可作为 Final Output</td></tr><tr><td>Structured Output</td><td>符合 Schema 的业务数据</td><td>解析、校验并交给下游代码</td></tr><tr><td>Tool Call</td><td>模型提出调用某个能力</td><td>校验、授权、执行，再回传 Result</td></tr><tr><td>Handoff / Agent Call</td><td>转交任务或调用 Specialist</td><td>切换所有权或建立子 Run</td></tr><tr><td>Streaming Events</td><td>增量文本、Tool 参数、状态事件</td><td>更新 UI、调度执行并记录 Trace</td></tr></tbody></table></div><div className="protocol-grid"><article className="protocol-card"><header><b>Messages-oriented request</b><span>ROLE SEQUENCE</span></header><pre className="protocol-code"><code>{"{\n  \"messages\": [\n    {\"role\": \"system\", \"content\": \"...\"},\n    {\"role\": \"user\", \"content\": \"查订单 A123\"}\n  ],\n  \"tools\": [{\"name\": \"get_order\", \"parameters\": {...}}]\n}"}</code></pre></article><article className="protocol-card"><header><b>Typed-item tool round trip</b><span>ACTION / OBSERVATION</span></header><pre className="protocol-code"><code>{"MODEL → function_call(call_id, name, arguments)\nRUNTIME → validate + authorize + execute\nRUNTIME → function_call_output(call_id, result)\nMODEL → final message or another function_call"}</code></pre></article></div><p>OpenAI Responses 使用 Message、Function Call、Function Call Output 等 Typed Items；Chat Completions 围绕 Messages 组织；Claude 使用 <code>tool_use</code> 与 <code>tool_result</code> Content Blocks；Gemini 使用 <code>functionCall</code> 与 <code>functionResponse</code> Parts。框架通常会把它们归一化，但调试时仍应能看到 Provider 原始请求与响应。</p><aside className="answer-first"><span>两个经常混淆的概念</span><p><b>Structured Output 让模型交付数据；Tool Calling 让模型提出动作。</b>模型输出一个合法退款 JSON，不代表退款已经发生。只有 Runtime 调用真实系统并获得成功回执，才能宣称动作完成。</p></aside></section>

      <section className="prose-section" id="chapter-6"><div className="prose-heading"><span>06</span><div><p>AGENT-COMPUTER INTERFACE</p><h2>Tools 为什么比 Prompt 更接近 Agent 的产品接口？</h2></div></div><p>Tool 是模型与外部世界之间的 Agent-Computer Interface（ACI）。它既要便于模型正确选择，也要便于 Runtime 安全执行。一个 Tool 至少需要稳定名称、清楚描述、严格参数 Schema、明确返回结构、错误语义、权限要求和副作用说明。</p><div className="agent-checklist"><article><span>01</span><h3>让用途容易区分</h3><p>避免多个名称相近、职责重叠的 Tools；描述清楚何时用、何时不能用。</p></article><article><span>02</span><h3>让非法状态难以表达</h3><p>使用 Enum、必填字段和互斥结构，不要把所有内容塞进自由文本。</p></article><article><span>03</span><h3>读写能力分离</h3><p>查询 Tool 与产生副作用的 Tool 分开授权，写操作提供 Dry-run 或 Proposal。</p></article><article><span>04</span><h3>返回可行动的错误</h3><p>区分参数错误、权限不足、可重试故障、业务拒绝与未知失败。</p></article><article><span>05</span><h3>实现幂等与审计</h3><p>写操作使用 Idempotency Key，记录身份、参数、回执和外部事务 ID。</p></article><article><span>06</span><h3>限制结果体积</h3><p>返回结构化摘要与引用，避免把巨量原始数据直接压入 Context。</p></article></div><h3>MCP 放在这一层的什么位置？</h3><p>MCP 不是 Agent Runtime，也不负责 Planning。它是 Host、Client、Server 之间连接能力和上下文的协议：Server 可以暴露 Tools、Resources 和 Prompts，Agent 应用作为 Host 管理一个或多个 MCP Clients。MCP 解决“怎样发现和调用能力”，但工具授权、用户确认、结果可信度和整个控制循环仍由 Host 负责。</p><div className="engineering-stack"><article><span>MCP HOST</span><b>Agent Application / IDE / Desktop</b><small>管理模型、控制循环、权限和多个 Clients</small></article><article><span>MCP CLIENT</span><b>One connection per MCP Server</b><small>能力发现、协议消息、Transport 与认证</small></article><article><span>MCP SERVER</span><b>Tools · Resources · Prompts</b><small>本地 STDIO 或远程 Streamable HTTP</small></article></div></section>

      <section className="prose-section" id="chapter-7"><div className="prose-heading"><span>07</span><div><p>INFORMATION LIFECYCLES</p><h2>Context、State、Memory、Trace 与 Artifact 怎样分工？</h2></div></div><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>对象</th><th>它回答的问题</th><th>生命周期</th><th>例子</th></tr></thead><tbody><tr><td>Context</td><td>这一次 Model Call 看见什么？</td><td>单次调用</td><td>Instructions、Messages、Tool Results</td></tr><tr><td>Run State</td><td>本次执行进行到哪里？</td><td>一次 Run</td><td>当前节点、预算、Pending Calls</td></tr><tr><td>Thread State</td><td>同一会话已发生什么？</td><td>多轮会话</td><td>消息、任务进度、Checkpoint</td></tr><tr><td><a className="term-link" href="/agents/memory">Memory</a></td><td>未来其他任务还需要知道什么？</td><td>跨 Run / 跨 Thread</td><td>用户偏好、事实、历史经验</td></tr><tr><td>Trace</td><td>系统实际上执行了什么？</td><td>审计与调试</td><td>Model、Tool、State、Guardrail Spans</td></tr><tr><td>Artifact</td><td>任务产生了什么可交付物？</td><td>由产品决定</td><td>报告、代码、表格、文件</td></tr></tbody></table></div><p>框架里的 Session 或 Checkpointer 通常解决 Thread Continuity，并不自动构成长时 <a className="term-link" href="/agents/memory">Memory</a>。长期 Memory 还需要选择写入、跨会话检索、版本冲突、权限和删除策略。</p><aside className="qwen-connection"><span>CONNECTION · MEMORY SYSTEM</span><p>如果你想继续理解短期 State、长期 Store、检索、写入与遗忘的区别，可以进入独立的工程文档。</p><a href="/agents/memory">进入 Agent Memory 文档 ↗</a></aside></section>

      <section className="prose-section" id="chapter-8"><div className="prose-heading"><span>08</span><div><p>CONTROL PATTERNS</p><h2>Agentic System 常见的控制模式有哪些？</h2></div></div><p>不是所有多步系统都应该使用开放式 Agent Loop。下面这些模式从确定性较强到自主性较强，可以组合使用。</p><div className="agent-pattern-grid"><article className="agent-pattern-card"><span>PATTERN 01</span><h3>Prompt Chaining</h3><div className="pattern-flow"><b>Draft</b><i>→</i><b>Check</b><i>→</i><b>Rewrite</b></div><p>步骤固定、前一步输出进入下一步。适合可以清晰拆解的任务。</p></article><article className="agent-pattern-card"><span>PATTERN 02</span><h3>Routing</h3><div className="pattern-flow"><b>Classify</b><i>→</i><b>A / B / C</b></div><p>把不同输入送往专门 Prompt、Model、Workflow 或 Agent。</p></article><article className="agent-pattern-card"><span>PATTERN 03</span><h3>Parallelization</h3><div className="pattern-flow"><b>Split</b><i>→</i><b>Workers</b><i>→</i><b>Aggregate</b></div><p>并行处理独立子任务，或用多个判断提高覆盖率。</p></article><article className="agent-pattern-card"><span>PATTERN 04</span><h3>Evaluator–Optimizer</h3><div className="pattern-flow"><b>Generate</b><i>→</i><b>Evaluate</b><i>↺</i></div><p>当评价标准明确且反馈确实能改善输出时迭代。</p></article><article className="agent-pattern-card"><span>PATTERN 05</span><h3>Orchestrator–Workers</h3><div className="pattern-flow"><b>Decompose</b><i>→</i><b>Delegate</b><i>→</i><b>Synthesize</b></div><p>子任务无法预先确定，由 Orchestrator 根据输入动态拆分。</p></article><article className="agent-pattern-card"><span>PATTERN 06</span><h3>Autonomous Tool Loop</h3><div className="pattern-flow"><b>Observe</b><i>→</i><b>Act</b><i>↺</i><b>Stop</b></div><p>模型持续决定下一动作，适合路径开放但反馈充分的任务。</p></article></div><p>Planning 也不是一个必须存在的独立 Agent。短任务可直接逐步选择 Tool；长任务可以维护结构化 Plan；高风险任务应让代码固定关键阶段，只允许模型在局部节点选择。</p></section>

      <section className="prose-section" id="chapter-9"><div className="prose-heading"><span>09</span><div><p>MULTI-AGENT IS AN ORCHESTRATION CHOICE</p><h2>什么时候需要多个 Agents？常见拓扑有什么区别？</h2></div></div><p>多 Agent 的价值主要来自上下文隔离、专业 Tool Surface、权限分离和任务所有权，而不是让多个模型互相聊天。若单 Agent 能稳定完成任务，多 Agent 往往只会增加路由、上下文传递和调试成本。</p><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>拓扑</th><th>控制权</th><th>适合场景</th><th>主要风险</th></tr></thead><tbody><tr><td>Agent as Tool</td><td>Manager 始终保持控制</td><td>调用研究、代码、数据等 Specialist</td><td>Manager 汇总失败、子任务契约模糊</td></tr><tr><td>Handoff</td><td>任务所有权转交给 Specialist</td><td>客服分流、角色边界明确</td><td>上下文丢失、责任边界不清</td></tr><tr><td>Sequential Team</td><td>按固定顺序传递产物</td><td>研究 → 写作 → 审核</td><td>早期错误向后传播</td></tr><tr><td>Parallel Workers</td><td>Orchestrator 分发并汇总</td><td>可独立搜索、分析或验证的子任务</td><td>重复工作、结果冲突</td></tr><tr><td>Group Chat / Shared Bus</td><td>Selector、规则或群体协作</td><td>探索性研究和实验</td><td>Token 膨胀、循环、难以归责</td></tr></tbody></table></div><aside className="text-note"><b>先问一个问题</b><p>这个“新 Agent”是否真的需要独立 Instructions、Tools、Context、权限或任务所有权？如果只是并行调用三个搜索接口，那么它们是 Tools，不需要变成三个 Agents。</p></aside></section>

      <section className="prose-section" id="chapter-10"><div className="prose-heading"><span>10</span><div><p>FRAMEWORK LANDSCAPE · 2026.08</p><h2>LangChain、LangGraph、Agents SDK 等框架怎样选择？</h2></div></div><p>框架主要提供运行时抽象，不提供业务正确性。选型时应观察 State 模型、Tool Loop 是否透明、能否暂停恢复、Tracing 是否完整、Provider 是否可替换，以及团队能否调试到底层请求。</p><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>方案</th><th>定位</th><th>适合什么</th><th>注意点</th></tr></thead><tbody><tr><td>Provider SDK + 自写 Runtime</td><td>直接控制 Model API 与 Tool Loop</td><td>小型系统、协议研究、极强定制</td><td>Checkpoint、Tracing、HITL 都要自己建设</td></tr><tr><td>LangChain Agents</td><td>高层模型、Tools、Middleware 与常见 Agent Loop</td><td>快速构建通用单 Agent</td><td>复杂拓扑通常需要下沉 LangGraph</td></tr><tr><td>LangGraph</td><td>长运行、有状态的低层编排 Runtime</td><td>Graph、Checkpoint、HITL、恢复和自定义分支</td><td>需要团队显式设计 State 与 Nodes</td></tr><tr><td>OpenAI Agents SDK</td><td>较轻量的 Agent / Runner 原语</td><td>Tools、Handoffs、Guardrails、Sessions、Tracing</td><td>业务持久化与权限仍由应用负责</td></tr><tr><td>Microsoft Agent Framework</td><td>生产级、多语言 Agent 与 Workflow 框架</td><td>Python/.NET/Go、图编排、HITL、可观测性</td><td>AutoGen 已进入维护模式，新项目应评估其继任者 MAF</td></tr><tr><td>Google ADK</td><td>Code-first Agent Development Kit</td><td>Graph Runtime、Workflow、评测和部署</td><td>优化 Gemini 生态，但官方定位为 Model-agnostic</td></tr></tbody></table></div><aside className="boundary-box"><b>框架不是越“全家桶”越好</b><p>如果一个 Tool Loop 用少量代码就能清楚表达，直接 SDK 往往更容易调试。只有当 Durable Execution、复杂分支、人工中断、多 Agent、统一 Tracing 或部署治理成为真实需求时，引入编排框架才有明确收益。</p></aside></section>

      <section className="prose-section" id="chapter-11"><div className="prose-heading"><span>11</span><div><p>RELIABILITY AND SAFETY</p><h2>可靠 Agent 为什么不能只靠 System Prompt？</h2></div></div><div className="agent-checklist"><article><span>01</span><h3>Least Privilege</h3><p>按用户、任务阶段和环境动态暴露最小 Tool Surface。</p></article><article><span>02</span><h3>Schema + Business Validation</h3><p>参数合法不等于业务允许，仍需检查资源归属、额度和状态。</p></article><article><span>03</span><h3>Human Approval</h3><p>付款、退款、删除、发布和外部消息在提交前暂停。</p></article><article><span>04</span><h3>Sandboxing</h3><p>代码、Shell、Browser 与文件操作运行在受限环境中。</p></article><article><span>05</span><h3>Idempotency and Transactions</h3><p>重试不能重复扣款、建单、发券或发送通知。</p></article><article><span>06</span><h3>Budgets and Termination</h3><p>限制模型调用、Tool Calls、时间、成本、重复动作和总步数。</p></article><article><span>07</span><h3>Prompt Injection Boundary</h3><p>网页、邮件、文档和 Tool Results 都是数据，不得覆盖高优先级规则。</p></article><article><span>08</span><h3>Evidence-based Completion</h3><p>只有观察到真实成功回执，才能对用户宣称动作完成。</p></article></div><p>Guardrail 也要区分位置：Input Guardrail 检查请求是否允许进入；Model Output Guardrail 检查文本或动作提案；Tool Guardrail 在真实副作用前验证权限；Post-condition Check 在执行后确认环境确实达到目标状态。</p></section>

      <section className="prose-section" id="chapter-12"><div className="prose-heading"><span>12</span><div><p>RUNTIME INFRASTRUCTURE</p><h2>从 Demo 到生产，还需要哪些运行基础设施？</h2></div></div><div className="engineering-stack"><article><span>RUN SERVICE</span><b>Run ID · Thread ID · Parent Run · Status Machine</b><small>统一描述 Running、Waiting、Succeeded、Failed、Canceled</small></article><article><span>DURABLE EXECUTION</span><b>Checkpoint · Queue · Worker · Lease · Resume</b><small>进程重启、超时或人工审批后能够继续</small></article><article><span>MODEL GATEWAY</span><b>Provider Routing · Timeout · Retry · Rate Limit</b><small>统一模型接入、成本统计和回退策略</small></article><article><span>TOOL EXECUTOR</span><b>Auth Context · Sandbox · Idempotency · Transaction</b><small>模型与真实权限之间的安全执行层</small></article><article><span>DATA PLANE</span><b>State Store · Memory · Artifact · Event Log</b><small>区分可变状态、长期信息、产物和不可变证据</small></article><article><span>OBSERVABILITY</span><b>Trace · Metrics · Logs · Evaluation Samples</b><small>把每个 Run 变成可定位、可复现的数据</small></article></div><p>长任务不应该依赖一个持续占用的 HTTP 请求。常见做法是 API 创建 Run 后立即返回 Run ID，后台 Worker 执行；前端通过 SSE、WebSocket 或轮询接收事件。等待用户审批时释放 Worker，状态写入 Checkpoint；获得审批后由新 Worker 恢复。</p><aside className="text-note"><b>并发控制</b><p>同一 Thread、同一业务对象或同一外部事务可能被多个 Runs 同时修改。除了数据库事务，还需要 Version、Lease、Compare-and-Set 或业务幂等键，不能指望模型自行避免竞态。</p></aside></section>

      <section className="prose-section" id="chapter-13"><div className="prose-heading"><span>13</span><div><p>TRACE THE TRAJECTORY</p><h2>Agent 应该怎样调试和评测？</h2></div></div><p>Agent 的输出是整条轨迹共同产生的。只保存最终答案，无法判断失败来自 Context、模型决策、Tool Schema、权限、外部服务、State 更新还是停止条件。</p><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>Trace Span</th><th>至少记录什么</th><th>典型问题</th></tr></thead><tbody><tr><td>Run</td><td>目标、身份 Scope、版本、最终状态、总成本</td><td>是否真正完成任务？</td></tr><tr><td>Model Call</td><td>Prompt/Context 版本、模型、Items、Tokens、延迟</td><td>模型为什么选择了这个动作？</td></tr><tr><td>Tool Call</td><td>Call ID、参数、权限、Result、外部事务 ID</td><td>是选择错误、参数错误还是执行失败？</td></tr><tr><td>State Transition</td><td>前后状态、Node、Checkpoint、并发版本</td><td>为什么重复或跳过步骤？</td></tr><tr><td>Guardrail / Approval</td><td>规则、Decision、Reviewer、修改内容</td><td>高风险动作是否被正确拦截？</td></tr><tr><td>Handoff</td><td>From/To、原因、传递上下文、所有权</td><td>任务为什么被错误路由？</td></tr></tbody></table></div><div className="norm-table-wrap"><table className="norm-table"><thead><tr><th>评测层</th><th>指标示例</th></tr></thead><tbody><tr><td>Outcome</td><td>Task Success、业务闭环率、Grounded Correctness</td></tr><tr><td>Trajectory</td><td>Tool Selection、参数准确率、无效步骤、重复调用</td></tr><tr><td>Efficiency</td><td>Model Calls、Tool Calls、Tokens、Cost、P50/P95 Latency</td></tr><tr><td>Reliability</td><td>恢复率、超时率、重复副作用、Handoff 失败率</td></tr><tr><td>Safety</td><td>越权、审批绕过、敏感数据泄露、Injection 成功率</td></tr></tbody></table></div><p>评测集应包含正常任务、歧义输入、Tool 故障、权限不足、过期数据、Prompt Injection、超时、并发和中途审批。Agent 的回归测试不是只比较一段文本，而是检查允许的轨迹边界和最终环境状态。</p></section>

      <section className="prose-section" id="chapter-14"><div className="prose-heading"><span>14</span><div><p>PRODUCTION BLUEPRINT</p><h2>以客服 Agent 为例，怎样把这些组件组合起来？</h2></div></div><div className="agent-architecture-board" role="img" aria-label="客服 Agent 的生产架构案例"><div className="agent-arch-layer"><strong>CHANNELS</strong><div><article><b>App / Web / Voice</b><small>用户身份、消息与流式事件</small></article><article><b>Conversation API</b><small>Thread、Run、附件与反馈</small></article></div></div><div className="agent-arch-layer"><strong>CONTROL</strong><div><article><b>Triage</b><small>问答、订单、售后、人工路由</small></article><article><b>Support Agent</b><small>选择下一步与生成用户响应</small></article><article><b>Policy Workflow</b><small>退款规则、审批、风险与升级</small></article></div></div><div className="agent-arch-layer"><strong>CAPABILITIES</strong><div><article><b>Knowledge Search</b><small>政策与产品知识</small></article><article><b>Order Query</b><small>只读订单与物流状态</small></article><article><b>Refund Proposal</b><small>生成待审批的退款方案</small></article><article><b>Refund Commit</b><small>审批后执行并返回事务回执</small></article></div></div><div className="agent-arch-layer"><strong>STATE</strong><div><article><b>Thread Checkpoint</b><small>对话与当前处理状态</small></article><article><b>User Memory</b><small>授权保存的长期偏好</small></article><article><b>Ticket / Order DB</b><small>真实业务 Source of Truth</small></article><article><b>Trace Store</b><small>完整执行轨迹和证据</small></article></div></div></div><p>这里的关键设计是把“查询”和“提交”拆开：模型可以自由查询订单、检索政策并生成退款 Proposal；真实退款必须经过确定性规则与必要审批，使用幂等键提交，并以支付系统回执作为完成证据。</p><h3>设计一个新 Agent 时的最小清单</h3><div className="agent-checklist"><article><span>01</span><h3>目标与成功条件</h3><p>系统怎样知道任务完成，而不是只生成了一段看似完成的话？</p></article><article><span>02</span><h3>控制权边界</h3><p>哪些决策交给模型，哪些步骤必须由代码固定？</p></article><article><span>03</span><h3>Tool Contracts</h3><p>每个 Tool 的权限、Schema、错误、副作用和幂等语义是什么？</p></article><article><span>04</span><h3>State Model</h3><p>Run、Thread、Memory、Artifact 和业务事实分别保存在哪里？</p></article><article><span>05</span><h3>停止与恢复</h3><p>何时成功、失败、澄清、审批、转人工，崩溃后怎样恢复？</p></article><article><span>06</span><h3>Trace 与 Evals</h3><p>能否重现每个 Model Call、Tool Result 和 State Transition？</p></article></div><aside className="answer-first"><span>推荐的建设顺序</span><p><b>先做单 Agent + 少量高质量 Tools + 明确 State + 完整 Trace。</b>只有评测证明瓶颈来自上下文、任务分解或权限隔离时，再增加长期 Memory、Planner、多 Agent 或更复杂框架。</p></aside></section>

      <section className="prose-section rms-qa" id="qa"><div className="prose-heading"><span>15</span><div><p>QUESTIONS AS CONNECTIONS</p><h2>关联 QA</h2></div></div><div className="qa-list">
        <details id="qa-1" open><summary><span>Q1</span>一次 LLM 调用算 Agent 吗？</summary><div><p>通常不算完整 Agent。一次调用没有动作执行后的环境反馈和继续决策；它可以是 Agent Runtime 中的一个 Model Node。</p></div></details>
        <details id="qa-2"><summary><span>Q2</span>Agent 与 Workflow 的根本区别是什么？</summary><div><p>Workflow 的主要路径由代码预先定义；Agent 让模型根据中间 Observation 动态选择下一步。生产系统常在固定 Workflow 的局部节点加入 Agent 决策。</p></div></details>
        <details id="qa-3"><summary><span>Q3</span>RAG 系统算 Agent 吗？</summary><div><p>固定的“检索一次再生成”通常是 Workflow，不一定是 Agent。若模型能决定是否检索、改写 Query、选择不同数据源、根据结果继续行动，它才更接近 Agentic Retrieval。</p></div></details>
        <details id="qa-4"><summary><span>Q4</span>为什么不应该把所有 LLM 应用都做成 Agent？</summary><div><p>Agent 会增加模型调用、延迟、成本、状态和错误路径。若 Single Call、RAG 或固定 Workflow 已能稳定完成，开放式循环没有额外价值。</p></div></details>
        <details id="qa-5"><summary><span>Q5</span>Tool Calling 等于 Tool 已执行吗？</summary><div><p>不等于。Tool Call 只是模型提出的结构化动作意图；Runtime 校验并真正调用外部系统后返回的 Tool Result，才是执行观察。</p></div></details>
        <details id="qa-6"><summary><span>Q6</span>Structured Output 与 Tool Calling 有什么区别？</summary><div><p>Structured Output 约束模型交付可解析数据；Tool Calling 请求 Runtime 执行能力。前者不自动产生真实世界副作用。</p></div></details>
        <details id="qa-7"><summary><span>Q7</span>MCP 是 Agent 框架吗？</summary><div><p>不是。MCP 是 Host、Client 与 Server 之间发现和交换 Tools、Resources、Prompts 的协议。Planning、State、权限、循环与停止条件仍属于 Agent Host 或 Runtime。</p></div></details>
        <details id="qa-8"><summary><span>Q8</span>State、Context 与 <a className="term-link" href="/agents/memory">Memory</a> 有什么区别？</summary><div><p>Context 是一次模型调用看见的内容；State 是当前 Run 或 Thread 的结构化进度；Memory 是选择性持久化、未来跨任务可召回的信息。</p></div></details>
        <details id="qa-9"><summary><span>Q9</span>什么时候需要 Planning？</summary><div><p>当任务依赖关系长、需要追踪多个子目标或执行过程中可能重规划时。短 Tool Loop 不必先生成长计划，高风险步骤更应由代码固定。</p></div></details>
        <details id="qa-10"><summary><span>Q10</span>什么时候值得使用多 Agent？</summary><div><p>当 Instructions、Tool Surface、Context、权限或任务所有权确实需要隔离时。仅仅并行调用多个 API 不需要多个 Agents。</p></div></details>
        <details id="qa-11"><summary><span>Q11</span>Manager 与 Handoff 有什么区别？</summary><div><p>Manager 把 Specialists 当 Tools 调用并保持最终控制；Handoff 把任务所有权转给新的活跃 Agent。</p></div></details>
        <details id="qa-12"><summary><span>Q12</span>LangChain 与 LangGraph 有什么区别？</summary><div><p>LangChain 提供较高层的模型、Tools、Middleware 和常见 Agent Loop；LangGraph 提供 State、Nodes、Edges、Checkpoint、HITL 与 Durable Execution 等低层编排能力。LangChain Agents 构建在 LangGraph 之上。</p></div></details>
        <details id="qa-13"><summary><span>Q13</span>一定要使用 Agent 框架吗？</summary><div><p>不需要。小型 Tool Loop 可以直接用 Provider SDK 编写。需要复杂分支、暂停恢复、统一 Tracing、多 Agent 或部署治理时，框架才更有价值。</p></div></details>
        <details id="qa-14"><summary><span>Q14</span>怎样防止 Agent 无限循环？</summary><div><p>Runtime 设置最大 Model Calls、Tool Calls、总步数、时间和成本；检测重复 Tool Signature 和无进展状态；对错误分类并限制重试，必要时转人工。</p></div></details>
        <details id="qa-15"><summary><span>Q15</span>为什么最终答案正确仍可能是失败？</summary><div><p>系统可能越权读取数据、重复执行副作用、跳过审批或依赖伪造结果。Agent 必须同时满足结果、轨迹、效率和安全要求。</p></div></details>
        <details id="qa-16"><summary><span>Q16</span>一个 Agent 上线前最少要具备什么？</summary><div><p>清楚的成功条件、受限 Tools、业务校验、停止预算、Checkpoint、幂等、高风险审批、完整 Trace，以及覆盖正常、故障、越权和 Injection 情形的评测集。</p></div></details>
      </div></section>

      <section className="sources-section rms-sources"><div><p className="mini-label">ARCHITECTURE REFERENCES</p><h2>官方平台文档与开源实现</h2></div><ol><li><a href="https://www.anthropic.com/engineering/building-effective-agents" target="_blank" rel="noreferrer">Anthropic · Building Effective Agents</a><span>Patterns</span></li><li><a href="https://github.com/langchain-ai/langgraph" target="_blank" rel="noreferrer">LangGraph · Stateful Agent Orchestration</a><span>GitHub</span></li><li><a href="https://github.com/openai/openai-agents-python" target="_blank" rel="noreferrer">OpenAI Agents SDK · Agents, Tools, Handoffs and Tracing</a><span>GitHub</span></li><li><a href="https://github.com/microsoft/agent-framework" target="_blank" rel="noreferrer">Microsoft Agent Framework</a><span>GitHub</span></li><li><a href="https://github.com/google/adk-python" target="_blank" rel="noreferrer">Google Agent Development Kit</a><span>GitHub</span></li><li><a href="https://modelcontextprotocol.io/docs/learn/architecture" target="_blank" rel="noreferrer">Model Context Protocol · Architecture</a><span>Official</span></li><li><a href="https://developers.openai.com/api/docs/guides/function-calling" target="_blank" rel="noreferrer">OpenAI API · Function Calling</a><span>Official</span></li></ol></section>
      <footer className="article-footer"><div><span>继续连接知识</span><strong>Agent Runtime 建立执行闭环；<a className="term-link" href="/agents/tools">Tools</a> 连接外部能力；<a className="term-link" href="/agents/memory">Memory</a> 负责让被选择的信息跨 Run 和跨 Thread 延续。</strong></div><div className="footer-links"><a href="/agents/tools">Agent Tools ↗</a><a href="/agents/memory">Agent Memory ↗</a><a href="/architecture/decoder-only">Decoder-only ↗</a><a href="/training/reasoning-rl">Reasoning RL ↗</a></div></footer>
    </main>
    <aside className="right-rail" aria-label="本页目录"><p>本页目录</p>{chapters.map(([no, label]) => <a href={no === "15" ? "#qa" : `#chapter-${Number(no)}`} key={no}><span>{no}</span>{label}</a>)}<RightQaIndex questions={qaQuestions} /><div className="reading-note"><span>15 章</span><div><i></i></div><small>工程架构 · 综述</small></div></aside>
  </div>;
}
